#!/usr/bin/env bash
# Tessera — LIVE differential test for the second MMU variant (MIPS decode).
#
# The Rocq model transcribes QEMU's `compute_pagemask` (mips_qemu_oracle.v,
# `compute_mask_level_conforms`) and pins six decode vectors by `vm_compute`.
# This script closes the loop the *other* way: it extracts `compute_pagemask`
# — and the `extract32`/`ctz32`/`cto32` primitives it uses — **verbatim** from
# the live QEMU source, compiles them, and runs the *same* six vectors,
# checking that real QEMU code agrees with the model:
#
#   compute_mask_level val esp        QEMU compute_pagemask
#   ----------------------------      ----------------------
#   Some 0  (lvl0)                    accept, maskbits 0
#   Some 2  (lvl2)                    accept, maskbits 2
#   Some 4  (lvl4)                    accept, maskbits 4
#   None    (odd)                     reject
#   None    (nonrun)                  reject
#   Some 2  (esp_l2)                  accept, maskbits 2
#
# Nothing here is a hand transcription: the four functions are `sed`-extracted
# from QEMU on every run, so a QEMU change fails this test loudly instead of
# silently drifting from the model.
#
# Skipped (exit 0) when QEMU's source is not present or `cc` is missing, so it
# is safe to wire into CI on machines without ~/src/QEMU.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QEMU="${QEMU:-$HOME/src/QEMU}"

CP0="$QEMU/target/mips/tcg/system/cp0_helper.c"
HU="$QEMU/include/qemu/host-utils.h"
BO="$QEMU/include/qemu/bitops.h"

for f in "$CP0" "$HU" "$BO"; do
  if [ ! -f "$f" ]; then
    echo "SKIP: QEMU source not found at $f (set QEMU=/path/to/qemu)" >&2
    exit 0
  fi
done
if ! command -v cc >/dev/null 2>&1; then
  echo "SKIP: no C compiler (cc) available" >&2
  exit 0
fi

# --- extract the four functions verbatim (top-level fn -> matching `}`) ---
compute_pagemask_body="$(sed -n '/^uint32_t compute_pagemask(/,/^}/p' "$CP0")"
cto32_body="$(sed -n '/^static inline int cto32(/,/^}/p' "$HU")"
ctz32_body="$(sed -n '/^static inline int ctz32(/,/^}/p' "$HU")"
extract32_body="$(sed -n '/^static inline uint32_t extract32(/,/^}/p' "$BO")"

for name in compute_pagemask_body cto32_body ctz32_body extract32_body; do
  if [ -z "${!name}" ]; then
    echo "FAIL: could not extract $name from QEMU source" >&2
    exit 1
  fi
done

# --- assemble a self-contained C harness ---
OUT="$(mktemp /tmp/mips_decode_diff.XXXXXX.c)"
BIN="$(mktemp /tmp/mips_decode_diff.XXXXXX)"
trap 'rm -f "$OUT" "$BIN"' EXIT

cat > "$OUT" <<EOF
/* Generated by hardware/qemu-diff/run_mips_decode_diff.sh.
   The four functions below are extracted verbatim from QEMU. */
#include <stdint.h>
#include <stdbool.h>
#include <assert.h>
#include <stdio.h>

#define CP0C3_SP    4
#define CP0PG_ESP   28
#define CP0PM_MASK  13
#define CP0PM_MASKX 11

typedef struct CPUMIPSState { uint32_t CP0_Config3; uint64_t CP0_PageGrain; } CPUMIPSState;

$extract32_body

$ctz32_body

$cto32_body

$compute_pagemask_body

int main(void)
{
    struct { const char *name; uint32_t val; int esp; } vecs[] = {
        { "lvl0",   0x00000, 0 },   /* 0 ones  -> 4 KiB,  Some 0 */
        { "lvl2",   0x06000, 0 },   /* 2 ones  -> 16 KiB, Some 2 */
        { "lvl4",   0x1E000, 0 },   /* 4 ones  -> 64 KiB, Some 4 */
        { "odd",    0x02000, 0 },   /* 1 one   -> reject */
        { "nonrun", 0x0A000, 0 },   /* 0b101   -> reject */
        { "esp_l2", 0x01800, 1 },   /* ESP: 2 ones -> 4 KiB, Some 2 */
    };
    int i;
    for (i = 0; i < (int)(sizeof(vecs)/sizeof(vecs[0])); i++) {
        struct CPUMIPSState env = { 0 };
        if (vecs[i].esp) {
            env.CP0_Config3  = 1 << CP0C3_SP;
            env.CP0_PageGrain = 1 << CP0PG_ESP;
        }
        uint32_t pm = compute_pagemask(&env, vecs[i].val);
        int lsb = vecs[i].esp ? CP0PM_MASKX : CP0PM_MASK;
        int width = vecs[i].esp ? 18 : 16;
        uint32_t mask = extract32(vecs[i].val, lsb, width);
        int maskbits = cto32(mask);
        int accept = (mask >> maskbits) == 0 && (maskbits & 1) == 0;
        if (accept) {
            printf("%-7s pm=0x%05x accept %d\n", vecs[i].name, pm, maskbits);
        } else {
            printf("%-7s pm=0x%05x reject\n", vecs[i].name, pm);
        }
    }
    return 0;
}
EOF

# --- compile + run ---
cc -O2 -Wall -Wextra -o "$BIN" "$OUT"
ACTUAL="$("$BIN")"

EXPECTED='lvl0    pm=0x00000 accept 0
lvl2    pm=0x06000 accept 2
lvl4    pm=0x1e000 accept 4
odd     pm=0x00000 reject
nonrun  pm=0x00000 reject
esp_l2  pm=0x01800 accept 2'

if [ "$ACTUAL" = "$EXPECTED" ]; then
  echo "PASS: QEMU compute_pagemask agrees with the Rocq model on all 6 decode vectors"
  printf '%s\n' "$ACTUAL" | sed 's/^/  /'
  exit 0
fi

echo "FAIL: QEMU compute_pagemask disagrees with the Rocq model" >&2
diff <(printf '%s\n' "$EXPECTED") <(printf '%s\n' "$ACTUAL") >&2 || true
exit 1
