#!/usr/bin/env bash
# Tessera — LIVE differential test for the third MMU variant (LoongArch).
#
# Complements the Rocq oracle (hardware/rocq/loongarch_qemu_oracle.v) the other
# way: `check_ps` is `sed`-extracted **verbatim** from QEMU's loongarch64 TCG
# and compiled + run; the pair match and PA formulas are transcribed to C with
# exact line citations (they are inline in the struct-heavy
# `loongarch_tlb_search_cb` / `loongarch_check_pte`, so they cannot be cleanly
# extracted whole).  Both are run on the *same* vectors the Rocq model pins by
# `vm_compute` (`loongarch_tlb_proofs.v` test_vector_la_* / the oracle's
# diff_la_*), so real QEMU logic (check_ps) and an independent C transcription
# of the match/PA agree with the model:
#
#   check_ps:   ps 12/14/16 valid, 13/64 invalid (mock CSR_PRCFG2)
#   match:      4KiB even/odd = 1, next-pair = 0; 16KiB even/odd = 1, next = 0
#   pa:         4KiB even/odd = 0x100234/0x200234; 16KiB = 0x101234/0x200678
#
# Skipped (exit 0) when QEMU's source is not present or `cc` is missing.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QEMU="${QEMU:-$HOME/src/QEMU}"

TLB="$QEMU/target/loongarch/tcg/tlb_helper.c"
BO="$QEMU/include/qemu/bitops.h"

for f in "$TLB" "$BO"; do
  if [ ! -f "$f" ]; then
    echo "SKIP: QEMU source not found at $f (set QEMU=/path/to/qemu)" >&2
    exit 0
  fi
done
if ! command -v cc >/dev/null 2>&1; then
  echo "SKIP: no C compiler (cc) available" >&2
  exit 0
fi

# --- extract check_ps and BIT_ULL verbatim ---
check_ps_body="$(sed -n '/^bool check_ps(/,/^}/p' "$TLB")"
bit_ull_macro="$(sed -n 's/^#define BIT_ULL(nr).*/#define BIT_ULL(nr) (1ULL << (nr))/p' "$BO" | head -1)"

if [ -z "$check_ps_body" ] || [ -z "$bit_ull_macro" ]; then
  echo "FAIL: could not extract check_ps / BIT_ULL from QEMU source" >&2
  exit 1
fi

OUT="$(mktemp /tmp/loongarch_diff.XXXXXX.c)"
BIN="$(mktemp /tmp/loongarch_diff.XXXXXX)"
trap 'rm -f "$OUT" "$BIN"' EXIT

cat > "$OUT" <<EOF
/* Generated by hardware/qemu-diff/run_loongarch_diff.sh. */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>

$bit_ull_macro

typedef struct CPULoongArchState { uint64_t CSR_PRCFG2; } CPULoongArchState;

$check_ps_body

/* --- pair match, transcribed from loongarch_tlb_search_cb
   (target/loongarch/tcg/tlb_helper.c, the MTLB loop):
     compare_shift = tlb_ps + 1 - R_TLB_MISC_VPPN_SHIFT;  // VPPN_SHIFT = 13
     vpn = (vaddr & TARGET_VIRT_MASK) >> (tlb_ps + 1);
     match = (vpn == (tlb_vppn >> compare_shift));
   TARGET_VIRT_MASK = (1ULL << 48) - 1 for LA64. --- */
static int qemu_la_match(uint64_t vppn, int ps, uint64_t vaddr)
{
    int compare_shift = ps + 1 - 13;
    uint64_t vpn = (vaddr & ((1ULL << 48) - 1)) >> (ps + 1);
    return vpn == (vppn >> compare_shift);
}

/* --- PA, transcribed from loongarch_map_tlb_entry / loongarch_check_pte
   (tlb_helper.c / cpu_helper.c):
     n = (addr >> ps) & 1;                  // odd/even half
     tlb_ppn = pfn & ~(((1 << (ps - 12)) - 1));   // clear software bits
     physical = (tlb_ppn << R_TLBENTRY_64_PPN_SHIFT) | (addr & ((1 << ps) - 1));
   R_TLBENTRY_64_PPN_SHIFT = 12. --- */
static uint64_t qemu_la_pa(uint64_t pfn0, uint64_t pfn1, int ps, uint64_t vaddr)
{
    int n = (vaddr >> ps) & 1;
    uint64_t pfn = n ? pfn1 : pfn0;
    uint64_t tlb_ppn = pfn & ~(((1ULL << (ps - 12)) - 1));
    return (tlb_ppn << 12) | (vaddr & ((1ULL << ps) - 1));
}

int main(void)
{
    struct CPULoongArchState env;
    /* CSR_PRCFG2 advertises 4KiB (12), 16KiB (14), 64KiB (16). */
    env.CSR_PRCFG2 = (1ULL << 12) | (1ULL << 14) | (1ULL << 16);

    printf("check_ps12=%d\n", check_ps(&env, 12));
    printf("check_ps13=%d\n", check_ps(&env, 13));
    printf("check_ps14=%d\n", check_ps(&env, 14));
    printf("check_ps16=%d\n", check_ps(&env, 16));
    printf("check_ps64=%d\n", check_ps(&env, 64));

    printf("match_4k_even=%d\n",  qemu_la_match(1, 12, 0x2234));
    printf("match_4k_odd=%d\n",   qemu_la_match(1, 12, 0x3234));
    printf("match_4k_next=%d\n",  qemu_la_match(1, 12, 0x4234));
    printf("match_16k_even=%d\n", qemu_la_match(4, 14, 0x9234));
    printf("match_16k_odd=%d\n",  qemu_la_match(4, 14, 0xC678));
    printf("match_16k_next=%d\n", qemu_la_match(4, 14, 0x10234));

    printf("pa_4k_even=0x%lx\n",  qemu_la_pa(0x100, 0x200, 12, 0x2234));
    printf("pa_4k_odd=0x%lx\n",   qemu_la_pa(0x100, 0x200, 12, 0x3234));
    printf("pa_16k_even=0x%lx\n", qemu_la_pa(0x100, 0x200, 14, 0x9234));
    printf("pa_16k_odd=0x%lx\n",  qemu_la_pa(0x100, 0x200, 14, 0xC678));
    return 0;
}
EOF

cc -O2 -Wall -Wextra -o "$BIN" "$OUT"
ACTUAL="$("$BIN")"

EXPECTED='check_ps12=1
check_ps13=0
check_ps14=1
check_ps16=1
check_ps64=0
match_4k_even=1
match_4k_odd=1
match_4k_next=0
match_16k_even=1
match_16k_odd=1
match_16k_next=0
pa_4k_even=0x100234
pa_4k_odd=0x200234
pa_16k_even=0x101234
pa_16k_odd=0x200678'

if [ "$ACTUAL" = "$EXPECTED" ]; then
  echo "PASS: LoongArch check_ps (verbatim) + match/PA transcription agree with the Rocq model"
  printf '%s\n' "$ACTUAL" | sed 's/^/  /'
  exit 0
fi

echo "FAIL: LoongArch diff-test disagreed with the Rocq model" >&2
diff <(printf '%s\n' "$EXPECTED") <(printf '%s\n' "$ACTUAL") >&2 || true
exit 1
