(*Generated by Sail from aarch64_tlb.*)
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.
Require Import aarch64_tlb_types.
Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.


Definition neq_int (x : Z) (y : Z) : bool := negb ((Z.eqb (x) (y))).

Definition neq_bool (x : bool) (y : bool) : bool := negb ((Bool.eqb (x) (y))).

Definition __id (x : Z) : Z := x.

Definition _shl_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shl_int (m) (n) else shr_int (m) ((Z.opp (n))).

Definition _shr_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shr_int (m) (n) else shl_int (m) ((Z.opp (n))).

Definition fdiv_int (n : Z) (m : Z) : Z :=
   if andb ((Z.ltb (n) (0))) ((Z.gtb (m) (0))) then Z.sub ((Z.quot ((Z.add (n) (1))) (m))) (1)
   else if andb ((Z.gtb (n) (0))) ((Z.ltb (m) (0))) then Z.sub ((Z.quot ((Z.sub (n) (1))) (m))) (1)
   else Z.quot (n) (m).

Definition fmod_int (n : Z) (m : Z) : Z := Z.sub (n) ((Z.mul (m) ((fdiv_int (n) (m))))).

Definition sail_mask {v0 : Z} (len : Z) (v : mword v0) (*(len >=? 0) && (v0 >=? 0)*) : mword len :=
   if Z.leb (len) v0 then vector_truncate (v) (len) else zero_extend (v) (len).

Definition sail_ones (n : Z) (*n >=? 0*) : mword n := not_vec ((zeros (n))).

Definition slice_mask (n : Z) (i : Z) (l : Z) (*n >=? 0*) : mword n :=
   if Z.geb (l) (n) then shiftl ((sail_ones (n))) (i)
   else
     let one : bits n := sail_mask (n) ((('b"1")  : bits 1)) in
     shiftl ((sub_vec ((shiftl (one) (l))) (one))) (i).

Definition to_bytes_le (n : Z) (b : mword (8 * n)) (*n >? 0*) : vec (mword 8) n :=
   let res := vector_init (n) ((zeros (8))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       vec_update_dec (res) (i)
         ((autocast (T := mword)
           (subrange_vec_dec (b) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))))))).

Definition from_bytes_le (n : Z) (v : vec (mword 8) n) (*n >? 0*) : mword (8 * n) :=
   let res := zeros ((Z.mul (8) (n))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       update_subrange_vec_dec (res) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))
         ((autocast (T := mword)
           (vec_access_dec (v) (i)))))).

Definition is_none {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => false | None => true end.

Definition is_some {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => true | None => false end.

Definition concat_str_bits {n : Z} (str : string) (x : mword n) : string :=
   String.append (str) ((string_of_bits (x))).

Definition concat_str_dec (str : string) (x : Z) : string := String.append (str) ((dec_str (x))).

Definition undefined_TGx '(tt : unit) : M (TGx) :=
   (internal_pick ([TGx_4KB; TGx_16KB; TGx_64KB]))  : M (TGx).

Definition tgx_granule_bits (tgx : TGx) : Z :=
   match tgx with | TGx_4KB => 12 | TGx_16KB => 14 | TGx_64KB => 16 end.

Definition desc_size_log2 (d128 : bool) : Z := if d128 then 4 else 3.

Definition translation_size (d128 : bool) (tgx : TGx) (level : Z) : Z :=
   let granulebits := tgx_granule_bits (tgx) in
   let descsizelog2 := desc_size_log2 (d128) in
   Z.add (granulebits) ((Z.mul ((Z.sub (3) (level))) ((Z.sub (granulebits) (descsizelog2))))).

Definition contiguous_size (d128 : bool) (tgx : TGx) (level : Z) : Z :=
   if d128 then
     match tgx with
     | TGx_4KB =>
        if Z.eqb (level) (1) then 2
        else if orb ((Z.eqb (level) (2))) ((Z.eqb (level) (3))) then 4
        else 0
     | TGx_16KB =>
        if Z.eqb (level) (1) then 2
        else if Z.eqb (level) (2) then 4
        else if Z.eqb (level) (3) then 6
        else 0
     | TGx_64KB => if Z.eqb (level) (2) then 6 else if Z.eqb (level) (3) then 4 else 0
     end
   else
     match tgx with
     | TGx_4KB =>
        if orb ((Z.eqb (level) (1))) ((orb ((Z.eqb (level) (2))) ((Z.eqb (level) (3))))) then 4
        else 0
     | TGx_16KB => if Z.eqb (level) (2) then 5 else if Z.eqb (level) (3) then 7 else 0
     | TGx_64KB => if orb ((Z.eqb (level) (2))) ((Z.eqb (level) (3))) then 5 else 0
     end.

Definition undefined_AaEntry '(tt : unit) : M (AaEntry) :=
   (undefined_bitvector (44)) >>= fun (w__0 : mword 44) =>
   (undefined_bitvector (44)) >>= fun (w__1 : mword 44) =>
   (undefined_TGx (tt)) >>= fun (w__2 : TGx) =>
   (undefined_int (tt)) >>= fun (w__3 : Z) =>
   (undefined_bool (tt)) >>= fun (w__4 : bool) =>
   (undefined_bool (tt)) >>= fun (w__5 : bool) =>
   returnM (({| AaEntry_vatag := w__0;
                AaEntry_oabase := w__1;
                AaEntry_tgx := w__2;
                AaEntry_level := w__3;
                AaEntry_d128 := w__4;
                AaEntry_contig := w__5 |})).

Definition aa_ia_msb (e : AaEntry) : Z :=
   let tsize := translation_size (e.(AaEntry_d128)) (e.(AaEntry_tgx)) (e.(AaEntry_level)) in
   let csize :=
     if e.(AaEntry_contig) then
       contiguous_size (e.(AaEntry_d128)) (e.(AaEntry_tgx)) (e.(AaEntry_level))
     else 0 in
   Z.add (tsize) (csize).

Definition aa_covers (e : AaEntry) (va : mword 64) : bool :=
   let ia_msb := aa_ia_msb (e) in
   eq_vec ((shiftr (va) (ia_msb)))
     ((shiftr ((shiftl ((zero_extend (e.(AaEntry_vatag)) (64))) (12))) (ia_msb))).

Definition aa_pa (e : AaEntry) (va : mword 64) : mword 56 :=
   let ia_msb := aa_ia_msb (e) in
   let oa_hi := shiftr ((shiftl ((zero_extend (e.(AaEntry_oabase)) (56))) (12))) (ia_msb) in
   let off := shiftr ((shiftl (va) ((Z.sub (64) (ia_msb))))) ((Z.sub (64) (ia_msb))) in
   or_vec ((shiftl (oa_hi) (ia_msb))) ((zero_extend ((subrange_vec_dec (off) (55) (0))) (56))).

Definition aa_refill (e : AaEntry) (tlb : list AaEntry) : list AaEntry := e :: tlb.

Fixpoint aa_flush (va : mword 64) (tlb : list AaEntry) : list AaEntry :=
   match tlb with
   | [] => []
   | e :: rest => if aa_covers (e) (va) then aa_flush (va) (rest) else e :: (aa_flush (va) (rest))
   end.

Fixpoint aa_lookup (tlb : list AaEntry) (va : mword 64) : option (mword 56) :=
   match tlb with
   | [] => None
   | e :: rest => if aa_covers (e) (va) then Some ((aa_pa (e) (va))) else aa_lookup (rest) (va)
   end.

Definition initialize_registers '(tt : unit) : unit := tt.

Definition sail_model_init (_ : unit) : unit := initialize_registers (tt).



