(*Generated by Sail from intc.*)
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.
Require Import intc_types.
Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.


Definition neq_int (x : Z) (y : Z) : bool := negb ((Z.eqb (x) (y))).

Definition neq_bool (x : bool) (y : bool) : bool := negb ((Bool.eqb (x) (y))).

Definition __id (x : Z) : Z := x.

Definition _shl_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shl_int (m) (n) else shr_int (m) ((Z.opp (n))).

Definition _shr_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shr_int (m) (n) else shl_int (m) ((Z.opp (n))).

Definition fdiv_int (n : Z) (m : Z) : Z :=
   if andb ((Z.ltb (n) (0))) ((Z.gtb (m) (0))) then Z.sub ((Z.quot ((Z.add (n) (1))) (m))) (1)
   else if andb ((Z.gtb (n) (0))) ((Z.ltb (m) (0))) then Z.sub ((Z.quot ((Z.sub (n) (1))) (m))) (1)
   else Z.quot (n) (m).

Definition fmod_int (n : Z) (m : Z) : Z := Z.sub (n) ((Z.mul (m) ((fdiv_int (n) (m))))).

Definition sail_mask {v0 : Z} (len : Z) (v : mword v0) (*(len >=? 0) && (v0 >=? 0)*) : mword len :=
   if Z.leb (len) v0 then vector_truncate (v) (len) else zero_extend (v) (len).

Definition sail_ones (n : Z) (*n >=? 0*) : mword n := not_vec ((zeros (n))).

Definition slice_mask (n : Z) (i : Z) (l : Z) (*n >=? 0*) : mword n :=
   if Z.geb (l) (n) then shiftl ((sail_ones (n))) (i)
   else
     let one : bits n := sail_mask (n) ((('b"1")  : bits 1)) in
     shiftl ((sub_vec ((shiftl (one) (l))) (one))) (i).

Definition to_bytes_le (n : Z) (b : mword (8 * n)) (*n >? 0*) : vec (mword 8) n :=
   let res := vector_init (n) ((zeros (8))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       vec_update_dec (res) (i)
         ((autocast (T := mword)
           (subrange_vec_dec (b) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))))))).

Definition from_bytes_le (n : Z) (v : vec (mword 8) n) (*n >? 0*) : mword (8 * n) :=
   let res := zeros ((Z.mul (8) (n))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       update_subrange_vec_dec (res) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))
         ((autocast (T := mword)
           (vec_access_dec (v) (i)))))).

Definition is_none {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => false | None => true end.

Definition is_some {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => true | None => false end.

Definition concat_str_bits {n : Z} (str : string) (x : mword n) : string :=
   String.append (str) ((string_of_bits (x))).

Definition concat_str_dec (str : string) (x : Z) : string := String.append (str) ((dec_str (x))).

Fixpoint intc_set_bit (l : list bool) (i : Z) (v : bool) : list bool :=
   match (l, i) with
   | (g__1 :: rest, l__0) =>
      if Z.eqb (l__0) (0) then v :: rest else g__1 :: (intc_set_bit (rest) ((Z.sub (l__0) (1))) (v))
   | ([], _) => []
   end.

Fixpoint intc_get_bit (l : list bool) (i : Z) (d : bool) : bool :=
   match (l, i) with
   | (x :: g__0, l__0) =>
      if Z.eqb (l__0) (0) then x else intc_get_bit (g__0) ((Z.sub (l__0) (1))) (d)
   | ([], _) => d
   end.

Definition intc_send (ic : Intc) (i : Z) : Intc :=
   {| Intc_pending := intc_set_bit (ic.(Intc_pending)) (i) (true);
      Intc_masked := ic.(Intc_masked);
      Intc_delivery := ic.(Intc_delivery);
      Intc_ipi := ic.(Intc_ipi) |}.

Definition intc_mask (ic : Intc) (i : Z) : Intc :=
   {| Intc_pending := ic.(Intc_pending);
      Intc_masked := intc_set_bit (ic.(Intc_masked)) (i) (true);
      Intc_delivery := ic.(Intc_delivery);
      Intc_ipi := ic.(Intc_ipi) |}.

Definition intc_unmask (ic : Intc) (i : Z) : Intc :=
   {| Intc_pending := ic.(Intc_pending);
      Intc_masked := intc_set_bit (ic.(Intc_masked)) (i) (false);
      Intc_delivery := ic.(Intc_delivery);
      Intc_ipi := ic.(Intc_ipi) |}.

Definition intc_enter_context (ic : Intc) (i : Z) : Intc :=
   {| Intc_pending := ic.(Intc_pending);
      Intc_masked := ic.(Intc_masked);
      Intc_delivery := intc_set_bit (ic.(Intc_delivery)) (i) (false);
      Intc_ipi := ic.(Intc_ipi) |}.

Definition intc_exit_context (ic : Intc) (i : Z) : Intc :=
   {| Intc_pending := ic.(Intc_pending);
      Intc_masked := ic.(Intc_masked);
      Intc_delivery := intc_set_bit (ic.(Intc_delivery)) (i) (true);
      Intc_ipi := ic.(Intc_ipi) |}.

Definition intc_ack (ic : Intc) (i : Z) : Intc :=
   let delivered :=
     andb ((intc_get_bit (ic.(Intc_pending)) (i) (false)))
       ((andb ((negb ((intc_get_bit (ic.(Intc_masked)) (i) (false)))))
           ((intc_get_bit (ic.(Intc_delivery)) (i) (false))))) in
   if delivered then
     {| Intc_pending := intc_set_bit (ic.(Intc_pending)) (i) (false);
        Intc_masked := ic.(Intc_masked);
        Intc_delivery := ic.(Intc_delivery);
        Intc_ipi := intc_set_bit (ic.(Intc_ipi)) (i) (true) |}
   else ic.

Definition initialize_registers '(tt : unit) : unit := tt.

Definition sail_model_init (_ : unit) : unit := initialize_registers (tt).



