(* Tessera — SSG-3: the interrupt controller (intc.sail) realizes the IPI
   mailbox of machine.sail.

   machine.sail's IPI is a pure mailbox (`Machine.ipi`, `deliver_ipi`/
   `receive_ipi`): the leader marks core i's delivered bit and the remote only
   flushes once delivered (S2.3, hardware/rocq/ipi.v).  intc.sail models the
   *device* that produces those bits — a GIC-SGI / RISC-V-AIA-IPI subset with
   the three stages of a real controller:

     - `intc_send`   — the originator's MMIO write (GICD_SGIR / the per-hart
                       IPI address / IMSIC setipnum); the distributor latches
                       the per-core pending line ("generated by a write to an
                       SGI register in the GIC", IHI0069 2.1.2; "a machine
                       with multiple harts must provide for each hart an
                       implementation-defined memory address that can be
                       written to signal a machine-level software interrupt",
                       riscv-aia IPIs.adoc).
     - `intc_mask`/`intc_unmask` — GICD_ISENABLER0/ICENABLER0 (or mie.MSIE);
                       a masked interrupt stays pending but is not signalled.
     - `intc_ack`    — the PE reads its interrupt (ICC_IAR / mip): if pending
                       and unmasked, the pending state is cleared *for that PE*
                       (IHI0069 2.1.2) and the doorbell rings — ipi[i] := true.

   What is proved here:

   1. **The doorbell only rings on ack** — `intc_send_preserves_ipi`; and the
      pending line is latched by send (`intc_send_sets_pending`).
   2. **Masking** — a masked ack is a spurious no-op (`intc_ack_masked_noop`:
      the interrupt is held pending, nothing is delivered); unmasking then
      acking delivers (`intc_unmask_then_ack_delivers`).
   3. **Reification** — `intc_send_ack_refines_deliver_ipi`: when the
      controller's mailbox agrees with `Machine.ipi`, one send+ack performs
      exactly `deliver_ipi`'s update (the bridge lemmas
      `intc_set_bit_eq_list_update_bool`/`intc_get_bit_eq_list_nth_bool` make
      the two list encodings literally equal).
   4. **Delivery precedes ack, by construction** — `intc_delivery_enables_receive_ipi`
      composes (3) with ipi.v's `receive_ipi_after_delivery_sfences`: a machine
      whose mailbox was produced by the interrupt controller flushes exactly
      core i on `receive_ipi`.

   See doc/system-state-goals.md (SSG-3) and doc/interrupt-controller.md. *)

From Stdlib Require Import ZArith.
From Stdlib Require Import Lia.
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.
Require Import SailStdpp.Operators_mwords.
Require Import machine_types.
Require Import machine.
Require intc.        (* qualified: intc.intc_send, intc.intc_set_bit, ... — the
                        generated scaffolding (register/regstate) would clash with machine's *)
Require intc_types.  (* qualified: the Intc record and its projections live in
                        intc_types.v, not intc.v, so they qualify as intc_types.Intc *)
Require Import ipi.  (* receive_ipi_after_delivery_sfences *)
Import ListNotations.

(* ============================================================
   The controller's own list ops, with the standard in-range lemmas.
   ============================================================ *)

(* in-range set then get at the same index returns the new value *)
Lemma intc_set_bit_get_self (l : list bool) (i : nat) (v d : bool) :
  Nat.lt i (length l) ->
  intc.intc_get_bit (intc.intc_set_bit l (Z.of_nat i) v) (Z.of_nat i) d = v.
Proof.
  revert i. induction l as [| b bs IH]; intros [| i] H; cbn [intc.intc_get_bit intc.intc_set_bit length].
  - cbn in H. lia.
  - cbn in H. lia.
  - reflexivity.
  - cbn [length] in H.
    destruct (Z.eqb (Z.of_nat (S i)) 0) eqn:E.
    + apply Z.eqb_eq in E. lia.
    + cbn [intc.intc_get_bit intc.intc_set_bit]. rewrite E.
      replace (Z.sub (Z.of_nat (S i)) 1) with (Z.of_nat i) by lia.
      apply IH. lia.
Qed.

(* set at i leaves the bit at j <> i alone *)
Lemma intc_get_bit_set_other (l : list bool) (i j : nat) (v d : bool) :
  i <> j ->
  intc.intc_get_bit (intc.intc_set_bit l (Z.of_nat i) v) (Z.of_nat j) d =
  intc.intc_get_bit l (Z.of_nat j) d.
Proof.
  revert i j. induction l as [| b bs IH]; intros [| i] [| j] H; cbn [intc.intc_get_bit intc.intc_set_bit].
  - reflexivity.
  - reflexivity.
  - reflexivity.
  - reflexivity.
  - exfalso. apply H. reflexivity.
  - cbn. destruct (Z.eqb (Z.of_nat (S j)) 0) eqn:E.
    + apply Z.eqb_eq in E. lia.
    + reflexivity.
  - destruct (Z.eqb (Z.of_nat (S i)) 0) eqn:E.
    + apply Z.eqb_eq in E. lia.
    + cbn. reflexivity.
  - destruct (Z.eqb (Z.of_nat (S i)) 0) eqn:E.
    + apply Z.eqb_eq in E. lia.
    + cbn [intc.intc_get_bit].
      destruct (Z.eqb (Z.of_nat (S j)) 0) eqn:E2.
      * apply Z.eqb_eq in E2. lia.
      * replace (Z.sub (Z.of_nat (S i)) 1) with (Z.of_nat i) by lia.
        replace (Z.sub (Z.of_nat (S j)) 1) with (Z.of_nat j) by lia.
        apply IH. intros Hj. apply H. lia.
Qed.

(* the two list encodings are literally the same function: intc's ops vs the
   machine's ops on Machine.ipi.  This is what makes the reification below an
   equality rather than a simulation. *)
Lemma intc_set_bit_eq_list_update_bool (l : list bool) (i : Z) (v : bool) :
  intc.intc_set_bit l i v = list_update_bool l i v.
Proof.
  revert i v. induction l as [| b bs IH]; intros i v; cbn [intc.intc_set_bit list_update_bool].
  - reflexivity.
  - destruct (Z.eqb i 0) eqn:E; cbn; [reflexivity | f_equal; apply IH].
Qed.

Lemma intc_get_bit_eq_list_nth_bool (l : list bool) (i : Z) (d : bool) :
  intc.intc_get_bit l i d = list_nth_bool l i d.
Proof.
  revert i d. induction l as [| b bs IH]; intros i d; cbn [intc.intc_get_bit list_nth_bool].
  - reflexivity.
  - destruct (Z.eqb i 0) eqn:E; cbn; [reflexivity | apply IH].
Qed.

(* ============================================================
   1. The send transition: latch the pending line, ring nothing.
   ============================================================ *)

(* send records the interrupt for core i: the pending line goes high. *)
Lemma intc_send_sets_pending (ic : intc_types.Intc) (i : nat)
  (H : Nat.lt i (length (intc_types.Intc_pending ic))) :
  intc.intc_get_bit (intc_types.Intc_pending (intc.intc_send ic (Z.of_nat i))) (Z.of_nat i) false = true.
Proof.
  unfold intc.intc_send.
  apply intc_set_bit_get_self with (v := true) (d := false).
  exact H.
Qed.

(* send does not touch the mailbox: the doorbell rings only on ack. *)
Lemma intc_send_preserves_ipi (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_ipi (intc.intc_send ic i) = intc_types.Intc_ipi ic.
Proof. reflexivity. Qed.

Lemma intc_send_preserves_masked (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_masked (intc.intc_send ic i) = intc_types.Intc_masked ic.
Proof. reflexivity. Qed.

(* ============================================================
   2. The mask transitions.
   ============================================================ *)

Lemma intc_mask_sets_masked (ic : intc_types.Intc) (i : nat)
  (H : Nat.lt i (length (intc_types.Intc_masked ic))) :
  intc.intc_get_bit (intc_types.Intc_masked (intc.intc_mask ic (Z.of_nat i))) (Z.of_nat i) false = true.
Proof.
  unfold intc.intc_mask.
  apply intc_set_bit_get_self with (v := true) (d := false).
  exact H.
Qed.

Lemma intc_unmask_clears_masked (ic : intc_types.Intc) (i : nat)
  (H : Nat.lt i (length (intc_types.Intc_masked ic))) :
  intc.intc_get_bit (intc_types.Intc_masked (intc.intc_unmask ic (Z.of_nat i))) (Z.of_nat i) false = false.
Proof.
  unfold intc.intc_unmask.
  apply intc_set_bit_get_self with (v := false) (d := false).
  exact H.
Qed.

Lemma intc_mask_preserves_pending (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_pending (intc.intc_mask ic i) = intc_types.Intc_pending ic.
Proof. reflexivity. Qed.

Lemma intc_mask_preserves_ipi (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_ipi (intc.intc_mask ic i) = intc_types.Intc_ipi ic.
Proof. reflexivity. Qed.

Lemma intc_unmask_preserves_pending (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_pending (intc.intc_unmask ic i) = intc_types.Intc_pending ic.
Proof. reflexivity. Qed.

Lemma intc_unmask_preserves_ipi (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_ipi (intc.intc_unmask ic i) = intc_types.Intc_ipi ic.
Proof. reflexivity. Qed.

(* ============================================================
   3. The ack transition: pending & unmasked -> clear + ring.
   ============================================================ *)

(* ack on a pending, unmasked interrupt clears the pending line for that PE *)
Lemma intc_ack_unmasked_clears_pending (ic : intc_types.Intc) (i : nat)
  (Hp : intc.intc_get_bit (intc_types.Intc_pending ic) (Z.of_nat i) false = true)
  (Hm : intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false = false) :
  intc_types.Intc_pending (intc.intc_ack ic (Z.of_nat i)) =
  intc.intc_set_bit (intc_types.Intc_pending ic) (Z.of_nat i) false.
Proof.
  unfold intc.intc_ack. rewrite Hp, Hm. cbn. reflexivity.
Qed.

(* ... and rings the doorbell: the delivered bit that Machine.ipi consumes *)
Lemma intc_ack_unmasked_rings (ic : intc_types.Intc) (i : nat)
  (Hp : intc.intc_get_bit (intc_types.Intc_pending ic) (Z.of_nat i) false = true)
  (Hm : intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false = false) :
  intc_types.Intc_ipi (intc.intc_ack ic (Z.of_nat i)) =
  intc.intc_set_bit (intc_types.Intc_ipi ic) (Z.of_nat i) true.
Proof.
  unfold intc.intc_ack. rewrite Hp, Hm. cbn. reflexivity.
Qed.

(* a masked ack is a spurious no-op: the interrupt is held pending, the
   doorbell does not ring (GIC: "remains asserted until the interrupt is
   acknowledged by software" — but a masked PE is not signalled, so the read
   returns 1023 and changes nothing). *)
Lemma intc_ack_masked_noop (ic : intc_types.Intc) (i : nat)
  (Hm : intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false = true) :
  intc.intc_ack ic (Z.of_nat i) = ic.
Proof.
  unfold intc.intc_ack. rewrite Hm.
  destruct (intc.intc_get_bit (intc_types.Intc_pending ic) (Z.of_nat i) false); cbn; reflexivity.
Qed.

(* an ack with nothing pending is also a no-op *)
Lemma intc_ack_no_pending_noop (ic : intc_types.Intc) (i : nat)
  (Hp : intc.intc_get_bit (intc_types.Intc_pending ic) (Z.of_nat i) false = false) :
  intc.intc_ack ic (Z.of_nat i) = ic.
Proof.
  unfold intc.intc_ack. rewrite Hp. cbn. reflexivity.
Qed.

(* masked, sent, unmasked, acked: the held interrupt is now delivered *)
Lemma intc_unmask_then_ack_delivers (ic : intc_types.Intc) (i : nat)
  (Hlenp : Nat.lt i (length (intc_types.Intc_pending ic)))
  (Hlenm : Nat.lt i (length (intc_types.Intc_masked ic)))
  (Hleni : Nat.lt i (length (intc_types.Intc_ipi ic))) :
  intc.intc_get_bit
    (intc_types.Intc_ipi (intc.intc_ack (intc.intc_unmask (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i)) (Z.of_nat i)))
    (Z.of_nat i) false = true.
Proof.
  rewrite (intc_ack_unmasked_rings (intc.intc_unmask (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i)) i).
  - rewrite (intc_unmask_preserves_ipi (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i)).
    rewrite (intc_send_preserves_ipi ic (Z.of_nat i)).
    apply intc_set_bit_get_self with (v := true) (d := false).
    exact Hleni.
  - rewrite (intc_unmask_preserves_pending (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i)).
    apply intc_send_sets_pending. exact Hlenp.
  - apply (intc_unmask_clears_masked (intc.intc_send ic (Z.of_nat i)) i).
    rewrite (intc_send_preserves_masked ic (Z.of_nat i)). exact Hlenm.
Qed.

(* ============================================================
   4. Reification: send + ack is exactly deliver_ipi's update.
   ============================================================ *)

(* The controller's send+ack on an unmasked core performs the same mailbox
   update as machine.sail's deliver_ipi: one MMIO write (GICD_SGIR / IPI
   address) plus one ICC_IAR-style read produces Machine.ipi's delivered bit. *)
Lemma intc_send_ack_refines_deliver_ipi (m : Machine) (ic : intc_types.Intc) (i : nat)
  (Hag : intc_types.Intc_ipi ic = Machine_ipi m)
  (Hlen : Nat.lt i (length (intc_types.Intc_pending ic)))
  (Hm : intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false = false) :
  intc_types.Intc_ipi (intc.intc_ack (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i))
  = Machine_ipi (deliver_ipi m (Z.of_nat i)).
Proof.
  unfold deliver_ipi.
  rewrite (intc_ack_unmasked_rings (intc.intc_send ic (Z.of_nat i)) i).
  - rewrite (intc_send_preserves_ipi ic (Z.of_nat i)).
    rewrite Hag.
    cbn [Machine_ipi].
    apply intc_set_bit_eq_list_update_bool.
  - apply intc_send_sets_pending. exact Hlen.
  - rewrite (intc_send_preserves_masked ic (Z.of_nat i)). exact Hm.
Qed.

(* ============================================================
   5. Delivery precedes ack, by construction: the Intc-produced mailbox
      enables the remote's flush (composes with ipi.v).
   ============================================================ *)

(* deliver_ipi preserves the length of the mailbox; already proved in ipi.v and
   imported above, so no local copy is needed here. *)

(* A machine whose mailbox was produced by the controller's send+ack flushes
   exactly core i on receive_ipi — the SSG-3 crux, now with the device in the
   loop instead of a hand-set delivered bit. *)
Lemma intc_delivery_enables_receive_ipi (m : Machine) (ic : intc_types.Intc) (i : nat) (va : mword 64)
  (Hag : intc_types.Intc_ipi ic = Machine_ipi m)
  (Hlen : Nat.lt i (length (intc_types.Intc_pending ic)))
  (Hleni : Nat.lt i (length (intc_types.Intc_ipi ic)))
  (Hlenco : Nat.lt i (length (Machine_cores m)))
  (Hm : intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false = false) :
  let ic' := intc.intc_ack (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i) in
  let m' := {| Machine_cores := Machine_cores m; Machine_mem := Machine_mem m;
               Machine_ram := Machine_ram m; Machine_ipi := intc_types.Intc_ipi ic' |} in
  nth_error (Machine_cores (receive_ipi m' (Z.of_nat i) va)) i =
  option_map (fun c => sfence_vma_va c va) (nth_error (Machine_cores m) i).
Proof.
  intros ic' m'.
  assert (Hipi : intc_types.Intc_ipi ic' = list_update_bool (Machine_ipi m) (Z.of_nat i) true).
  { unfold ic'. rewrite (intc_send_ack_refines_deliver_ipi m ic i Hag Hlen Hm).
    cbn [Machine_ipi deliver_ipi]. reflexivity. }
  assert (Heq : m' = deliver_ipi m (Z.of_nat i)).
  { unfold m', deliver_ipi. f_equal. exact Hipi. }
  rewrite Heq.
  apply receive_ipi_after_delivery_sfences.
  - exact Hlenco.
  - rewrite <- Hag. exact Hleni.
Qed.

(* ============================================================
   Executable vectors (vm_compute) pinning the three stages on a 3-core
   controller.
   ============================================================ *)

Definition intc3 : intc_types.Intc :=
  intc_types.Build_Intc [false; false; false] [false; false; false] [false; false; false].

(* unmasked send+ack to core 1: the doorbell rings (ipi[1] = true). *)
Lemma test_vector_intc_send_ack_delivers :
  intc_types.Intc_ipi (intc.intc_ack (intc.intc_send intc3 1) 1) = [false; true; false].
Proof. vm_compute. reflexivity. Qed.

(* masked send+ack: the interrupt is held, nothing is delivered. *)
Lemma test_vector_intc_masked_holds :
  intc_types.Intc_ipi (intc.intc_ack (intc.intc_send (intc.intc_mask intc3 1) 1) 1) = [false; false; false].
Proof. vm_compute. reflexivity. Qed.

(* mask, send, unmask, ack: the held interrupt is delivered. *)
Lemma test_vector_intc_unmask_delivers :
  intc_types.Intc_ipi
    (intc.intc_ack (intc.intc_unmask (intc.intc_send (intc.intc_mask intc3 1) 1) 1) 1)
  = [false; true; false].
Proof. vm_compute. reflexivity. Qed.

(* ack clears the pending line for the acknowledging PE only. *)
Lemma test_vector_intc_ack_clears_pending :
  intc_types.Intc_pending (intc.intc_ack (intc.intc_send intc3 1) 1) = [false; false; false].
Proof. vm_compute. reflexivity. Qed.
