(* Tessera — SSG-3: the interrupt controller (intc.sail) realizes the IPI
   mailbox of machine.sail.

   machine.sail's IPI is a pure mailbox (`Machine.ipi`, `deliver_ipi`/
   `receive_ipi`): the leader marks core i's delivered bit and the remote only
   flushes once delivered (S2.3, hardware/rocq/ipi.v).  intc.sail models the
   *device* that produces those bits — a GIC-SGI / RISC-V-AIA-IPI subset with
   the three stages of a real controller:

     - `intc_send`   — the originator's MMIO write (ICC_SGI1R_EL1 / the per-hart
                       IPI address / IMSIC seteipnum); the distributor latches
                       the per-core pending line ("generated by a write to an
                       SGI register in the GIC", IHI0069 4.4; "a machine
                       with multiple harts must provide for each hart an
                       implementation-defined memory address that can be
                       written to signal a machine-level software interrupt",
                       riscv-aia IPIs.adoc).
     - `intc_mask`/`intc_unmask` — the *per-interrupt* enable (GICR_ISENABLER0/
                       ICENABLER0, IMSIC `eie`, or mie.MSIE); a masked interrupt
                       stays pending but is not signalled.
     - `intc_enter_context`/`intc_exit_context` — the *per-hart delivery gate*
                       (IMSIC `eidelivery` / sstatus.SIE / the kernel's
                       irq-disable): a hart in interrupt context holds its
                       interrupts pending — it does not drop them — and takes
                       them only after it leaves the context.
     - `intc_ack`    — the PE reads its interrupt (ICC_IAR / mip / *topei): if
                       pending, unmasked and delivery-enabled, the pending state
                       is cleared *for that PE* (IHI0069 1.2 Terminology,
                       Targeted list model) and the doorbell rings — ipi[i] := true.

   What is proved here:

   1. **The doorbell only rings on ack** — `intc_send_preserves_ipi`; and the
      pending line is latched by send (`intc_send_sets_pending`).
   2. **Masking & interrupt context** — a masked ack is a spurious no-op
      (`intc_ack_masked_noop`); unmasking then acking delivers
      (`intc_unmask_then_ack_delivers`); a hart in interrupt context holds its
      interrupt pending (ack is a no-op, `intc_ack_in_context_noop`) and takes
      it only after exiting the context (`test_vector_intc_exit_delivers`).
   3. **Reification** — `intc_send_ack_refines_deliver_ipi`: when the
      controller's mailbox agrees with `Machine.ipi`, one send+ack performs
      exactly `deliver_ipi`'s update (the bridge lemmas
      `intc_set_bit_eq_list_update_bool`/`intc_get_bit_eq_list_nth_bool` make
      the two list encodings literally equal).
   4. **Delivery precedes ack, by construction** — `intc_delivery_enables_receive_ipi`
      composes (3) with ipi.v's `receive_ipi_after_delivery_sfences`: a machine
      whose mailbox was produced by the interrupt controller flushes exactly
      core i on `receive_ipi`.

   See doc/system-state-goals.md (SSG-3) and doc/interrupt-controller.md. *)

From Stdlib Require Import ZArith.
From Stdlib Require Import Lia.
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.
Require Import SailStdpp.Operators_mwords.
Require Import machine_types.
Require Import machine.
Require intc.        (* qualified: intc.intc_send, intc.intc_set_bit, ... — the
                        generated scaffolding (register/regstate) would clash with machine's *)
Require intc_types.  (* qualified: the Intc record and its projections live in
                        intc_types.v, not intc.v, so they qualify as intc_types.Intc *)
Require Import ipi.  (* receive_ipi_after_delivery_sfences *)
Import ListNotations.

(* ============================================================
   The controller's own list ops, with the standard in-range lemmas.
   ============================================================ *)

(* in-range set then get at the same index returns the new value *)
Lemma intc_set_bit_get_self (l : list bool) (i : nat) (v d : bool) :
  Nat.lt i (length l) ->
  intc.intc_get_bit (intc.intc_set_bit l (Z.of_nat i) v) (Z.of_nat i) d = v.
Proof.
  revert i. induction l as [| b bs IH]; intros [| i] H; cbn [intc.intc_get_bit intc.intc_set_bit length].
  - cbn in H. lia.
  - cbn in H. lia.
  - reflexivity.
  - cbn [length] in H.
    destruct (Z.eqb (Z.of_nat (S i)) 0) eqn:E.
    + apply Z.eqb_eq in E. lia.
    + cbn [intc.intc_get_bit intc.intc_set_bit]. rewrite E.
      replace (Z.sub (Z.of_nat (S i)) 1) with (Z.of_nat i) by lia.
      apply IH. lia.
Qed.

(* set at i leaves the bit at j <> i alone *)
Lemma intc_get_bit_set_other (l : list bool) (i j : nat) (v d : bool) :
  i <> j ->
  intc.intc_get_bit (intc.intc_set_bit l (Z.of_nat i) v) (Z.of_nat j) d =
  intc.intc_get_bit l (Z.of_nat j) d.
Proof.
  revert i j. induction l as [| b bs IH]; intros [| i] [| j] H; cbn [intc.intc_get_bit intc.intc_set_bit].
  - reflexivity.
  - reflexivity.
  - reflexivity.
  - reflexivity.
  - exfalso. apply H. reflexivity.
  - cbn. destruct (Z.eqb (Z.of_nat (S j)) 0) eqn:E.
    + apply Z.eqb_eq in E. lia.
    + reflexivity.
  - destruct (Z.eqb (Z.of_nat (S i)) 0) eqn:E.
    + apply Z.eqb_eq in E. lia.
    + cbn. reflexivity.
  - destruct (Z.eqb (Z.of_nat (S i)) 0) eqn:E.
    + apply Z.eqb_eq in E. lia.
    + cbn [intc.intc_get_bit].
      destruct (Z.eqb (Z.of_nat (S j)) 0) eqn:E2.
      * apply Z.eqb_eq in E2. lia.
      * replace (Z.sub (Z.of_nat (S i)) 1) with (Z.of_nat i) by lia.
        replace (Z.sub (Z.of_nat (S j)) 1) with (Z.of_nat j) by lia.
        apply IH. intros Hj. apply H. lia.
Qed.

(* the two list encodings are literally the same function: intc's ops vs the
   machine's ops on Machine.ipi.  This is what makes the reification below an
   equality rather than a simulation. *)
Lemma intc_set_bit_eq_list_update_bool (l : list bool) (i : Z) (v : bool) :
  intc.intc_set_bit l i v = list_update_bool l i v.
Proof.
  revert i v. induction l as [| b bs IH]; intros i v; cbn [intc.intc_set_bit list_update_bool].
  - reflexivity.
  - destruct (Z.eqb i 0) eqn:E; cbn; [reflexivity | f_equal; apply IH].
Qed.

Lemma intc_get_bit_eq_list_nth_bool (l : list bool) (i : Z) (d : bool) :
  intc.intc_get_bit l i d = list_nth_bool l i d.
Proof.
  revert i d. induction l as [| b bs IH]; intros i d; cbn [intc.intc_get_bit list_nth_bool].
  - reflexivity.
  - destruct (Z.eqb i 0) eqn:E; cbn; [reflexivity | apply IH].
Qed.

(* intc_set_bit is structurally recursive on the list, so it preserves length. *)
Lemma intc_set_bit_length (l : list bool) (i : Z) (v : bool) :
  length (intc.intc_set_bit l i v) = length l.
Proof.
  revert i. induction l as [| b bs IH]; intros i; cbn [intc.intc_set_bit length].
  - reflexivity.
  - destruct (Z.eqb i 0); cbn [length]; [reflexivity | f_equal; apply IH].
Qed.

(* ============================================================
   1. The send transition: latch the pending line, ring nothing.
   ============================================================ *)

(* send records the interrupt for core i: the pending line goes high. *)
Lemma intc_send_sets_pending (ic : intc_types.Intc) (i : nat)
  (H : Nat.lt i (length (intc_types.Intc_pending ic))) :
  intc.intc_get_bit (intc_types.Intc_pending (intc.intc_send ic (Z.of_nat i))) (Z.of_nat i) false = true.
Proof.
  unfold intc.intc_send.
  apply intc_set_bit_get_self with (v := true) (d := false).
  exact H.
Qed.

(* send does not touch the mailbox: the doorbell rings only on ack. *)
Lemma intc_send_preserves_ipi (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_ipi (intc.intc_send ic i) = intc_types.Intc_ipi ic.
Proof. reflexivity. Qed.

Lemma intc_send_preserves_masked (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_masked (intc.intc_send ic i) = intc_types.Intc_masked ic.
Proof. reflexivity. Qed.

Lemma intc_send_preserves_delivery (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_delivery (intc.intc_send ic i) = intc_types.Intc_delivery ic.
Proof. reflexivity. Qed.

(* ============================================================
   2. The mask transitions.
   ============================================================ *)

Lemma intc_mask_sets_masked (ic : intc_types.Intc) (i : nat)
  (H : Nat.lt i (length (intc_types.Intc_masked ic))) :
  intc.intc_get_bit (intc_types.Intc_masked (intc.intc_mask ic (Z.of_nat i))) (Z.of_nat i) false = true.
Proof.
  unfold intc.intc_mask.
  apply intc_set_bit_get_self with (v := true) (d := false).
  exact H.
Qed.

Lemma intc_unmask_clears_masked (ic : intc_types.Intc) (i : nat)
  (H : Nat.lt i (length (intc_types.Intc_masked ic))) :
  intc.intc_get_bit (intc_types.Intc_masked (intc.intc_unmask ic (Z.of_nat i))) (Z.of_nat i) false = false.
Proof.
  unfold intc.intc_unmask.
  apply intc_set_bit_get_self with (v := false) (d := false).
  exact H.
Qed.

Lemma intc_mask_preserves_pending (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_pending (intc.intc_mask ic i) = intc_types.Intc_pending ic.
Proof. reflexivity. Qed.

Lemma intc_mask_preserves_ipi (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_ipi (intc.intc_mask ic i) = intc_types.Intc_ipi ic.
Proof. reflexivity. Qed.

Lemma intc_unmask_preserves_pending (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_pending (intc.intc_unmask ic i) = intc_types.Intc_pending ic.
Proof. reflexivity. Qed.

Lemma intc_unmask_preserves_ipi (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_ipi (intc.intc_unmask ic i) = intc_types.Intc_ipi ic.
Proof. reflexivity. Qed.

Lemma intc_mask_preserves_delivery (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_delivery (intc.intc_mask ic i) = intc_types.Intc_delivery ic.
Proof. reflexivity. Qed.

Lemma intc_unmask_preserves_delivery (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_delivery (intc.intc_unmask ic i) = intc_types.Intc_delivery ic.
Proof. reflexivity. Qed.

(* ============================================================
   2.5. The interrupt-context (per-hart delivery gate) transitions.
   ============================================================ *)

(* enter_context clears the delivery gate: the hart no longer takes its
   interrupts, but nothing pending is dropped. *)
Lemma intc_enter_context_clears_delivery (ic : intc_types.Intc) (i : nat)
  (H : Nat.lt i (length (intc_types.Intc_delivery ic))) :
  intc.intc_get_bit (intc_types.Intc_delivery (intc.intc_enter_context ic (Z.of_nat i))) (Z.of_nat i) false = false.
Proof.
  unfold intc.intc_enter_context.
  apply intc_set_bit_get_self with (v := false) (d := false).
  exact H.
Qed.

(* exit_context re-enables delivery for the hart. *)
Lemma intc_exit_context_sets_delivery (ic : intc_types.Intc) (i : nat)
  (H : Nat.lt i (length (intc_types.Intc_delivery ic))) :
  intc.intc_get_bit (intc_types.Intc_delivery (intc.intc_exit_context ic (Z.of_nat i))) (Z.of_nat i) false = true.
Proof.
  unfold intc.intc_exit_context.
  apply intc_set_bit_get_self with (v := true) (d := false).
  exact H.
Qed.

(* enter_context holds the interrupt: the pending line is kept, and the
   doorbell never rings on context entry. *)
Lemma intc_enter_context_preserves_pending (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_pending (intc.intc_enter_context ic i) = intc_types.Intc_pending ic.
Proof. reflexivity. Qed.

Lemma intc_enter_context_preserves_ipi (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_ipi (intc.intc_enter_context ic i) = intc_types.Intc_ipi ic.
Proof. reflexivity. Qed.

(* ============================================================
   3. The ack transition: pending & unmasked & delivery-enabled -> clear + ring.
   ============================================================ *)

(* ack on a pending, unmasked, delivery-enabled interrupt clears the pending
   line for that PE *)
Lemma intc_ack_unmasked_clears_pending (ic : intc_types.Intc) (i : nat)
  (Hp : intc.intc_get_bit (intc_types.Intc_pending ic) (Z.of_nat i) false = true)
  (Hm : intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false = false)
  (Hd : intc.intc_get_bit (intc_types.Intc_delivery ic) (Z.of_nat i) false = true) :
  intc_types.Intc_pending (intc.intc_ack ic (Z.of_nat i)) =
  intc.intc_set_bit (intc_types.Intc_pending ic) (Z.of_nat i) false.
Proof.
  unfold intc.intc_ack. rewrite Hp, Hm, Hd. cbn. reflexivity.
Qed.

(* ... and rings the doorbell: the delivered bit that Machine.ipi consumes *)
Lemma intc_ack_unmasked_rings (ic : intc_types.Intc) (i : nat)
  (Hp : intc.intc_get_bit (intc_types.Intc_pending ic) (Z.of_nat i) false = true)
  (Hm : intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false = false)
  (Hd : intc.intc_get_bit (intc_types.Intc_delivery ic) (Z.of_nat i) false = true) :
  intc_types.Intc_ipi (intc.intc_ack ic (Z.of_nat i)) =
  intc.intc_set_bit (intc_types.Intc_ipi ic) (Z.of_nat i) true.
Proof.
  unfold intc.intc_ack. rewrite Hp, Hm, Hd. cbn. reflexivity.
Qed.

(* a masked ack is a spurious no-op: the interrupt is held pending, the
   doorbell does not ring (GIC: "remains asserted until the interrupt is
   acknowledged by software" — but a masked PE is not signalled, so the read
   returns 1023 and changes nothing). *)
Lemma intc_ack_masked_noop (ic : intc_types.Intc) (i : nat)
  (Hm : intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false = true) :
  intc.intc_ack ic (Z.of_nat i) = ic.
Proof.
  unfold intc.intc_ack. rewrite Hm.
  destruct (intc.intc_get_bit (intc_types.Intc_pending ic) (Z.of_nat i) false); cbn; reflexivity.
Qed.

(* an ack with nothing pending is also a no-op *)
Lemma intc_ack_no_pending_noop (ic : intc_types.Intc) (i : nat)
  (Hp : intc.intc_get_bit (intc_types.Intc_pending ic) (Z.of_nat i) false = false) :
  intc.intc_ack ic (Z.of_nat i) = ic.
Proof.
  unfold intc.intc_ack. rewrite Hp. cbn. reflexivity.
Qed.

(* a hart in interrupt context (delivery disabled) is not signalled: the ack is
   a no-op, the interrupt is held pending, and the doorbell does not ring — the
   "no lost or duplicated shootdown" half of SSG-3. *)
Lemma intc_ack_in_context_noop (ic : intc_types.Intc) (i : nat)
  (Hd : intc.intc_get_bit (intc_types.Intc_delivery ic) (Z.of_nat i) false = false) :
  intc.intc_ack ic (Z.of_nat i) = ic.
Proof.
  unfold intc.intc_ack. rewrite Hd.
  destruct (intc.intc_get_bit (intc_types.Intc_pending ic) (Z.of_nat i) false);
  destruct (intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false);
  cbn; reflexivity.
Qed.

(* exit_context also only touches delivery: it preserves pending/ipi/masked. *)
Lemma intc_exit_context_preserves_pending (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_pending (intc.intc_exit_context ic i) = intc_types.Intc_pending ic.
Proof. reflexivity. Qed.

Lemma intc_exit_context_preserves_ipi (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_ipi (intc.intc_exit_context ic i) = intc_types.Intc_ipi ic.
Proof. reflexivity. Qed.

Lemma intc_exit_context_preserves_masked (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_masked (intc.intc_exit_context ic i) = intc_types.Intc_masked ic.
Proof. reflexivity. Qed.

Lemma intc_enter_context_preserves_masked (ic : intc_types.Intc) (i : Z) :
  intc_types.Intc_masked (intc.intc_enter_context ic i) = intc_types.Intc_masked ic.
Proof. reflexivity. Qed.

(* ============================================================
   2.6. The "no lost or duplicated shootdown" composition.

   A hart in interrupt context (delivery disabled) holds its interrupt pending
   — the in-context ack is a no-op, so nothing is lost — and delivers it exactly
   once after it exits the context.  This is the SSG-3 crux the per-hart delivery
   gate exists for.
   ============================================================ *)

(* exit then ack delivers the held interrupt (generalizes
   test_vector_intc_exit_delivers to any controller, not just intc3). *)
Lemma intc_exit_then_ack_delivers (ic : intc_types.Intc) (i : nat)
  (Hlenp : Nat.lt i (length (intc_types.Intc_pending ic)))
  (Hlenm : Nat.lt i (length (intc_types.Intc_masked ic)))
  (Hlend : Nat.lt i (length (intc_types.Intc_delivery ic)))
  (Hleni : Nat.lt i (length (intc_types.Intc_ipi ic)))
  (Hm : intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false = false) :
  intc.intc_get_bit
    (intc_types.Intc_ipi
       (intc.intc_ack
          (intc.intc_exit_context
             (intc.intc_ack (intc.intc_send (intc.intc_enter_context ic (Z.of_nat i)) (Z.of_nat i))
                            (Z.of_nat i))
             (Z.of_nat i))
          (Z.of_nat i)))
    (Z.of_nat i) false = true.
Proof.
  set (ic0 := intc.intc_enter_context ic (Z.of_nat i)).
  set (ic1 := intc.intc_send ic0 (Z.of_nat i)).
  (* the in-context ack is a no-op: delivery[i] = false after enter+send *)
  assert (Hnoop : intc.intc_ack ic1 (Z.of_nat i) = ic1).
  { apply intc_ack_in_context_noop.
    subst ic1 ic0.
    rewrite (intc_send_preserves_delivery (intc.intc_enter_context ic (Z.of_nat i)) (Z.of_nat i)).
    apply (intc_enter_context_clears_delivery ic i Hlend). }
  subst ic1 ic0.
  rewrite Hnoop.
  (* exit re-enables delivery; ack now rings the doorbell *)
  rewrite (intc_ack_unmasked_rings
             (intc.intc_exit_context (intc.intc_send (intc.intc_enter_context ic (Z.of_nat i)) (Z.of_nat i))
                                     (Z.of_nat i)) i).
  - rewrite (intc_exit_context_preserves_ipi
               (intc.intc_send (intc.intc_enter_context ic (Z.of_nat i)) (Z.of_nat i)) (Z.of_nat i)).
    rewrite (intc_send_preserves_ipi (intc.intc_enter_context ic (Z.of_nat i)) (Z.of_nat i)).
    rewrite (intc_enter_context_preserves_ipi ic (Z.of_nat i)).
    apply (intc_set_bit_get_self (intc_types.Intc_ipi ic) i true false Hleni).
  - (* pending[i] = true: send latches it, exit preserves it *)
    rewrite (intc_exit_context_preserves_pending
               (intc.intc_send (intc.intc_enter_context ic (Z.of_nat i)) (Z.of_nat i)) (Z.of_nat i)).
    apply (intc_send_sets_pending (intc.intc_enter_context ic (Z.of_nat i)) i).
    rewrite (intc_enter_context_preserves_pending ic (Z.of_nat i)). exact Hlenp.
  - (* masked[i] = false: exit/send/enter all preserve the mask *)
    rewrite (intc_exit_context_preserves_masked
               (intc.intc_send (intc.intc_enter_context ic (Z.of_nat i)) (Z.of_nat i)) (Z.of_nat i)).
    rewrite (intc_send_preserves_masked (intc.intc_enter_context ic (Z.of_nat i)) (Z.of_nat i)).
    rewrite (intc_enter_context_preserves_masked ic (Z.of_nat i)).
    exact Hm.
  - (* delivery[i] = true: exit sets it *)
    apply (intc_exit_context_sets_delivery
             (intc.intc_send (intc.intc_enter_context ic (Z.of_nat i)) (Z.of_nat i)) i).
    rewrite (intc_send_preserves_delivery (intc.intc_enter_context ic (Z.of_nat i)) (Z.of_nat i)).
    cbn [intc.intc_enter_context intc_types.Intc_delivery].
    rewrite intc_set_bit_length. exact Hlend.
Qed.

(* The two halves packaged: a shootdown IPI arriving while a hart is in interrupt
   context is held (no loss — pending stays latched, the doorbell stays silent),
   and delivered exactly once the hart exits the context. *)
Lemma intc_no_lost_shootdown (ic : intc_types.Intc) (i : nat)
  (Hlenp : Nat.lt i (length (intc_types.Intc_pending ic)))
  (Hlenm : Nat.lt i (length (intc_types.Intc_masked ic)))
  (Hlend : Nat.lt i (length (intc_types.Intc_delivery ic)))
  (Hleni : Nat.lt i (length (intc_types.Intc_ipi ic)))
  (Hm : intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false = false) :
  intc.intc_ack (intc.intc_send (intc.intc_enter_context ic (Z.of_nat i)) (Z.of_nat i)) (Z.of_nat i)
    = intc.intc_send (intc.intc_enter_context ic (Z.of_nat i)) (Z.of_nat i) /\
  intc.intc_get_bit
    (intc_types.Intc_ipi
       (intc.intc_ack
          (intc.intc_exit_context
             (intc.intc_ack (intc.intc_send (intc.intc_enter_context ic (Z.of_nat i)) (Z.of_nat i))
                            (Z.of_nat i))
             (Z.of_nat i))
          (Z.of_nat i)))
    (Z.of_nat i) false = true.
Proof.
  split.
  - apply intc_ack_in_context_noop.
    rewrite (intc_send_preserves_delivery (intc.intc_enter_context ic (Z.of_nat i)) (Z.of_nat i)).
    apply (intc_enter_context_clears_delivery ic i Hlend).
  - apply (intc_exit_then_ack_delivers ic i Hlenp Hlenm Hlend Hleni Hm).
Qed.

(* masked, sent, unmasked, acked: the held interrupt is now delivered *)
Lemma intc_unmask_then_ack_delivers (ic : intc_types.Intc) (i : nat)
  (Hlenp : Nat.lt i (length (intc_types.Intc_pending ic)))
  (Hlenm : Nat.lt i (length (intc_types.Intc_masked ic)))
  (Hlend : Nat.lt i (length (intc_types.Intc_delivery ic)))
  (Hleni : Nat.lt i (length (intc_types.Intc_ipi ic)))
  (Hd : intc.intc_get_bit (intc_types.Intc_delivery ic) (Z.of_nat i) false = true) :
  intc.intc_get_bit
    (intc_types.Intc_ipi (intc.intc_ack (intc.intc_unmask (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i)) (Z.of_nat i)))
    (Z.of_nat i) false = true.
Proof.
  rewrite (intc_ack_unmasked_rings (intc.intc_unmask (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i)) i).
  - rewrite (intc_unmask_preserves_ipi (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i)).
    rewrite (intc_send_preserves_ipi ic (Z.of_nat i)).
    apply intc_set_bit_get_self with (v := true) (d := false).
    exact Hleni.
  - rewrite (intc_unmask_preserves_pending (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i)).
    apply intc_send_sets_pending. exact Hlenp.
  - apply (intc_unmask_clears_masked (intc.intc_send ic (Z.of_nat i)) i).
    rewrite (intc_send_preserves_masked ic (Z.of_nat i)). exact Hlenm.
  - rewrite (intc_unmask_preserves_delivery (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i)).
    rewrite (intc_send_preserves_delivery ic (Z.of_nat i)). exact Hd.
Qed.

(* ============================================================
   4. Reification: send + ack is exactly deliver_ipi's update.
   ============================================================ *)

(* The controller's send+ack on an unmasked core performs the same mailbox
   update as machine.sail's deliver_ipi: one MMIO write (GICD_SGIR / IPI
   address) plus one ICC_IAR-style read produces Machine.ipi's delivered bit. *)
Lemma intc_send_ack_refines_deliver_ipi (m : Machine) (ic : intc_types.Intc) (i : nat)
  (Hag : intc_types.Intc_ipi ic = Machine_ipi m)
  (Hlen : Nat.lt i (length (intc_types.Intc_pending ic)))
  (Hm : intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false = false)
  (Hd : intc.intc_get_bit (intc_types.Intc_delivery ic) (Z.of_nat i) false = true) :
  intc_types.Intc_ipi (intc.intc_ack (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i))
  = Machine_ipi (deliver_ipi m (Z.of_nat i)).
Proof.
  unfold deliver_ipi.
  rewrite (intc_ack_unmasked_rings (intc.intc_send ic (Z.of_nat i)) i).
  - rewrite (intc_send_preserves_ipi ic (Z.of_nat i)).
    rewrite Hag.
    cbn [Machine_ipi].
    apply intc_set_bit_eq_list_update_bool.
  - apply intc_send_sets_pending. exact Hlen.
  - rewrite (intc_send_preserves_masked ic (Z.of_nat i)). exact Hm.
  - rewrite (intc_send_preserves_delivery ic (Z.of_nat i)). exact Hd.
Qed.

(* ============================================================
   5. Delivery precedes ack, by construction: the Intc-produced mailbox
      enables the remote's flush (composes with ipi.v).
   ============================================================ *)

(* deliver_ipi preserves the length of the mailbox; already proved in ipi.v and
   imported above, so no local copy is needed here. *)

(* A machine whose mailbox was produced by the controller's send+ack flushes
   exactly core i on receive_ipi — the SSG-3 crux, now with the device in the
   loop instead of a hand-set delivered bit. *)
Lemma intc_delivery_enables_receive_ipi (m : Machine) (ic : intc_types.Intc) (i : nat) (va : mword 64)
  (Hag : intc_types.Intc_ipi ic = Machine_ipi m)
  (Hlen : Nat.lt i (length (intc_types.Intc_pending ic)))
  (Hleni : Nat.lt i (length (intc_types.Intc_ipi ic)))
  (Hlenco : Nat.lt i (length (Machine_cores m)))
  (Hm : intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false = false)
  (Hd : intc.intc_get_bit (intc_types.Intc_delivery ic) (Z.of_nat i) false = true) :
  let ic' := intc.intc_ack (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i) in
  let m' := {| Machine_cores := Machine_cores m; Machine_mem := Machine_mem m;
               Machine_ram := Machine_ram m; Machine_ipi := intc_types.Intc_ipi ic';
               Machine_iotlb := Machine_iotlb m; Machine_devtlbs := Machine_devtlbs m; Machine_prireqs := Machine_prireqs m; Machine_ioqueue := Machine_ioqueue m; Machine_stes := Machine_stes m; Machine_cds := Machine_cds m |} in
  nth_error (Machine_cores (receive_ipi m' (Z.of_nat i) va)) i =
  option_map (fun c => sfence_vma_va c va) (nth_error (Machine_cores m) i).
Proof.
  intros ic' m'.
  assert (Hipi : intc_types.Intc_ipi ic' = list_update_bool (Machine_ipi m) (Z.of_nat i) true).
  { unfold ic'. rewrite (intc_send_ack_refines_deliver_ipi m ic i Hag Hlen Hm Hd).
    cbn [Machine_ipi deliver_ipi]. reflexivity. }
  assert (Heq : m' = deliver_ipi m (Z.of_nat i)).
  { unfold m', deliver_ipi. f_equal. exact Hipi. }
  rewrite Heq.
  apply receive_ipi_after_delivery_sfences.
  - exact Hlenco.
  - rewrite <- Hag. exact Hleni.
Qed.

(* ============================================================
   Executable vectors (vm_compute) pinning the three stages on a 3-core
   controller.
   ============================================================ *)

Definition intc3 : intc_types.Intc :=
  intc_types.Build_Intc [false; false; false] [false; false; false]
                        [true; true; true] [false; false; false].

(* unmasked send+ack to core 1: the doorbell rings (ipi[1] = true). *)
Lemma test_vector_intc_send_ack_delivers :
  intc_types.Intc_ipi (intc.intc_ack (intc.intc_send intc3 1) 1) = [false; true; false].
Proof. vm_compute. reflexivity. Qed.

(* masked send+ack: the interrupt is held, nothing is delivered. *)
Lemma test_vector_intc_masked_holds :
  intc_types.Intc_ipi (intc.intc_ack (intc.intc_send (intc.intc_mask intc3 1) 1) 1) = [false; false; false].
Proof. vm_compute. reflexivity. Qed.

(* mask, send, unmask, ack: the held interrupt is delivered. *)
Lemma test_vector_intc_unmask_delivers :
  intc_types.Intc_ipi
    (intc.intc_ack (intc.intc_unmask (intc.intc_send (intc.intc_mask intc3 1) 1) 1) 1)
  = [false; true; false].
Proof. vm_compute. reflexivity. Qed.

(* ack clears the pending line for the acknowledging PE only. *)
Lemma test_vector_intc_ack_clears_pending :
  intc_types.Intc_pending (intc.intc_ack (intc.intc_send intc3 1) 1) = [false; false; false].
Proof. vm_compute. reflexivity. Qed.

(* enter context, send, ack (still in context): the interrupt is held, nothing
   is delivered — no loss, no spurious delivery. *)
Lemma test_vector_intc_context_holds :
  intc_types.Intc_ipi
    (intc.intc_ack (intc.intc_send (intc.intc_enter_context intc3 1) 1) 1)
  = [false; false; false].
Proof. vm_compute. reflexivity. Qed.

(* ...and exiting the context delivers the held interrupt. *)
Lemma test_vector_intc_exit_delivers :
  intc_types.Intc_ipi
    (intc.intc_ack
       (intc.intc_exit_context
          (intc.intc_ack (intc.intc_send (intc.intc_enter_context intc3 1) 1) 1) 1) 1)
  = [false; true; false].
Proof. vm_compute. reflexivity. Qed.

(* ...and while still in context, the pending line stays latched (not lost): the
   shootdown IPI is held, never dropped. *)
Lemma test_vector_intc_context_holds_pending :
  intc_types.Intc_pending
    (intc.intc_ack (intc.intc_send (intc.intc_enter_context intc3 1) 1) 1)
  = [false; true; false].
Proof. vm_compute. reflexivity. Qed.

(* ============================================================
   6. The weak-memory (S2.2c/S2.4) ghost step, realized by the controller.

   S2.4's leader advances its machine ghost by [deliver_ipi] then [receive_ipi]
   (shootdown_weak_broadcast.v, [bc_machine_ipi_step]): the IPI is a bare mailbox
   bit.  SSG-3's device (intc.sail) *produces* that bit — send latches pending,
   ack rings the doorbell.  This section is the pure bridge: the controller's
   send+ack makes [receive_ipi] flush exactly as [deliver_ipi] does, so the
   weak-memory broadcast's per-step IPI delivery is realized by the interrupt
   controller rather than a hand-set mailbox.  (The full device-in-the-loop
   Iris program — remotes gated on the controller's doorbell — is the S2.5
   milestone on top of this bridge.)
   ============================================================ *)

(* Re-point a machine's mailbox, leaving cores/mem/ram untouched. *)
Definition Machine_with_ipi (m : Machine) (ipi : list bool) : Machine :=
  {| Machine_cores := Machine_cores m; Machine_mem := Machine_mem m;
     Machine_ram := Machine_ram m; Machine_ipi := ipi;
     Machine_iotlb := Machine_iotlb m; Machine_devtlbs := Machine_devtlbs m; Machine_prireqs := Machine_prireqs m; Machine_ioqueue := Machine_ioqueue m; Machine_stes := Machine_stes m; Machine_cds := Machine_cds m |}.

(* The controller's send+ack produces the same mailbox as [deliver_ipi], so the
   remote's [receive_ipi] flush is identical: the weak-memory ghost step's IPI
   delivery is realized by the interrupt controller. *)
Lemma intc_receive_ipi_eq_deliver (m : Machine) (ic : intc_types.Intc) (i : nat) (va : mword 64)
  (Hag : intc_types.Intc_ipi ic = Machine_ipi m)
  (Hlen : Nat.lt i (length (intc_types.Intc_pending ic)))
  (Hm : intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false = false)
  (Hd : intc.intc_get_bit (intc_types.Intc_delivery ic) (Z.of_nat i) false = true) :
  receive_ipi
    (Machine_with_ipi m (intc_types.Intc_ipi (intc.intc_ack (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i))))
    (Z.of_nat i) va
  = receive_ipi (deliver_ipi m (Z.of_nat i)) (Z.of_nat i) va.
Proof.
  rewrite (intc_send_ack_refines_deliver_ipi m ic i Hag Hlen Hm Hd).
  reflexivity.
Qed.

(* The same bridge, phrased on what the remote observes: its TLB clear is
   identical whether the IPI was delivered by the controller or by deliver_ipi. *)
Lemma intc_receive_ipi_cores_eq_deliver (m : Machine) (ic : intc_types.Intc) (i : nat) (va : mword 64)
  (Hag : intc_types.Intc_ipi ic = Machine_ipi m)
  (Hlen : Nat.lt i (length (intc_types.Intc_pending ic)))
  (Hm : intc.intc_get_bit (intc_types.Intc_masked ic) (Z.of_nat i) false = false)
  (Hd : intc.intc_get_bit (intc_types.Intc_delivery ic) (Z.of_nat i) false = true) :
  Machine_cores
    (receive_ipi
       (Machine_with_ipi m (intc_types.Intc_ipi (intc.intc_ack (intc.intc_send ic (Z.of_nat i)) (Z.of_nat i))))
       (Z.of_nat i) va)
  = Machine_cores (receive_ipi (deliver_ipi m (Z.of_nat i)) (Z.of_nat i) va).
Proof.
  rewrite (intc_receive_ipi_eq_deliver m ic i va Hag Hlen Hm Hd). reflexivity.
Qed.

(* Executable: on the 3-core [ipi_machine] (mailbox all-false) with the all-false
   controller [intc3], send+ack to core 1 then [receive_ipi] flushes exactly as
   [deliver_ipi] does. *)
Lemma test_vector_intc_receive_ipi_eq_deliver :
  (receive_ipi
     (Machine_with_ipi ipi_machine (intc_types.Intc_ipi (intc.intc_ack (intc.intc_send intc3 1) 1)))
     1 ipi_va).(Machine_cores)
  = (receive_ipi (deliver_ipi ipi_machine 1) 1 ipi_va).(Machine_cores).
Proof. vm_compute. reflexivity. Qed.
