(*Generated by Sail from loongarch_tlb.*)
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.
Require Import loongarch_tlb_types.
Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.


Definition neq_int (x : Z) (y : Z) : bool := negb ((Z.eqb (x) (y))).

Definition neq_bool (x : bool) (y : bool) : bool := negb ((Bool.eqb (x) (y))).

Definition __id (x : Z) : Z := x.

Definition _shl_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shl_int (m) (n) else shr_int (m) ((Z.opp (n))).

Definition _shr_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shr_int (m) (n) else shl_int (m) ((Z.opp (n))).

Definition fdiv_int (n : Z) (m : Z) : Z :=
   if andb ((Z.ltb (n) (0))) ((Z.gtb (m) (0))) then Z.sub ((Z.quot ((Z.add (n) (1))) (m))) (1)
   else if andb ((Z.gtb (n) (0))) ((Z.ltb (m) (0))) then Z.sub ((Z.quot ((Z.sub (n) (1))) (m))) (1)
   else Z.quot (n) (m).

Definition fmod_int (n : Z) (m : Z) : Z := Z.sub (n) ((Z.mul (m) ((fdiv_int (n) (m))))).

Definition sail_mask {v0 : Z} (len : Z) (v : mword v0) (*(len >=? 0) && (v0 >=? 0)*) : mword len :=
   if Z.leb (len) v0 then vector_truncate (v) (len) else zero_extend (v) (len).

Definition sail_ones (n : Z) (*n >=? 0*) : mword n := not_vec ((zeros (n))).

Definition slice_mask (n : Z) (i : Z) (l : Z) (*n >=? 0*) : mword n :=
   if Z.geb (l) (n) then shiftl ((sail_ones (n))) (i)
   else
     let one : bits n := sail_mask (n) ((('b"1")  : bits 1)) in
     shiftl ((sub_vec ((shiftl (one) (l))) (one))) (i).

Definition to_bytes_le (n : Z) (b : mword (8 * n)) (*n >? 0*) : vec (mword 8) n :=
   let res := vector_init (n) ((zeros (8))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       vec_update_dec (res) (i)
         ((autocast (T := mword)
           (subrange_vec_dec (b) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))))))).

Definition from_bytes_le (n : Z) (v : vec (mword 8) n) (*n >? 0*) : mword (8 * n) :=
   let res := zeros ((Z.mul (8) (n))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       update_subrange_vec_dec (res) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))
         ((autocast (T := mword)
           (vec_access_dec (v) (i)))))).

Definition is_none {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => false | None => true end.

Definition is_some {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => true | None => false end.

Definition concat_str_bits {n : Z} (str : string) (x : mword n) : string :=
   String.append (str) ((string_of_bits (x))).

Definition concat_str_dec (str : string) (x : Z) : string := String.append (str) ((dec_str (x))).

Definition undefined_LaEntry '(tt : unit) : M (LaEntry) :=
   (undefined_bitvector (35)) >>= fun (w__0 : mword 35) =>
   (undefined_int (tt)) >>= fun (w__1 : Z) =>
   (undefined_bitvector (36)) >>= fun (w__2 : mword 36) =>
   (undefined_bitvector (36)) >>= fun (w__3 : mword 36) =>
   returnM (({| LaEntry_vppn := w__0;
                LaEntry_ps := w__1;
                LaEntry_pfn0 := w__2;
                LaEntry_pfn1 := w__3 |})).

Definition la_vppn_of (va : mword 64) : mword 35 := subrange_vec_dec (va) (47) (13).

Definition la_covers (e : LaEntry) (va : mword 64) : bool :=
   eq_vec ((shiftr ((subrange_vec_dec (va) (47) (0))) ((Z.add (e.(LaEntry_ps)) (1)))))
     ((shiftr ((shiftl ((zero_extend (e.(LaEntry_vppn)) (48))) (13))) ((Z.add (e.(LaEntry_ps)) (1))))).

Definition la_pa (e : LaEntry) (va : mword 64) : mword 48 :=
   let ps := e.(LaEntry_ps) in
   let odd : bool := eq_vec ((subrange_vec_dec ((shiftr (va) (ps))) (0) (0))) (('b"1")) in
   let pfn : bits 36 := if odd then e.(LaEntry_pfn1) else e.(LaEntry_pfn0) in
   let pfn_hi := shiftr (pfn) ((Z.sub (ps) (12))) in
   let off := shiftr ((shiftl (va) ((Z.sub (64) (ps))))) ((Z.sub (64) (ps))) in
   or_vec ((shiftl ((zero_extend (pfn_hi) (48))) (ps)))
     ((zero_extend ((subrange_vec_dec (off) (47) (0))) (48))).

Definition la_refill (e : LaEntry) (tlb : list LaEntry) : list LaEntry := e :: tlb.

Fixpoint la_flush (va : mword 64) (tlb : list LaEntry) : list LaEntry :=
   match tlb with
   | [] => []
   | e :: rest => if la_covers (e) (va) then la_flush (va) (rest) else e :: (la_flush (va) (rest))
   end.

Fixpoint la_lookup (tlb : list LaEntry) (va : mword 64) : option (mword 48) :=
   match tlb with
   | [] => None
   | e :: rest => if la_covers (e) (va) then Some ((la_pa (e) (va))) else la_lookup (rest) (va)
   end.

Definition initialize_registers '(tt : unit) : unit := tt.

Definition sail_model_init (_ : unit) : unit := initialize_registers (tt).



