(*Generated by Sail from machine.*)
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.
Require Import machine_types.
Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.


Definition neq_int (x : Z) (y : Z) : bool := negb ((Z.eqb (x) (y))).

Definition neq_bool (x : bool) (y : bool) : bool := negb ((Bool.eqb (x) (y))).

Definition __id (x : Z) : Z := x.

Definition _shl_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shl_int (m) (n) else shr_int (m) ((Z.opp (n))).

Definition _shr_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shr_int (m) (n) else shl_int (m) ((Z.opp (n))).

Definition fdiv_int (n : Z) (m : Z) : Z :=
   if andb ((Z.ltb (n) (0))) ((Z.gtb (m) (0))) then Z.sub ((Z.quot ((Z.add (n) (1))) (m))) (1)
   else if andb ((Z.gtb (n) (0))) ((Z.ltb (m) (0))) then Z.sub ((Z.quot ((Z.sub (n) (1))) (m))) (1)
   else Z.quot (n) (m).

Definition fmod_int (n : Z) (m : Z) : Z := Z.sub (n) ((Z.mul (m) ((fdiv_int (n) (m))))).

Definition sail_mask {v0 : Z} (len : Z) (v : mword v0) (*(len >=? 0) && (v0 >=? 0)*) : mword len :=
   if Z.leb (len) v0 then vector_truncate (v) (len) else zero_extend (v) (len).

Definition sail_ones (n : Z) (*n >=? 0*) : mword n := not_vec ((zeros (n))).

Definition slice_mask (n : Z) (i : Z) (l : Z) (*n >=? 0*) : mword n :=
   if Z.geb (l) (n) then shiftl ((sail_ones (n))) (i)
   else
     let one : bits n := sail_mask (n) ((('b"1")  : bits 1)) in
     shiftl ((sub_vec ((shiftl (one) (l))) (one))) (i).

Definition to_bytes_le (n : Z) (b : mword (8 * n)) (*n >? 0*) : vec (mword 8) n :=
   let res := vector_init (n) ((zeros (8))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       vec_update_dec (res) (i)
         ((autocast (T := mword)
           (subrange_vec_dec (b) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))))))).

Definition from_bytes_le (n : Z) (v : vec (mword 8) n) (*n >? 0*) : mword (8 * n) :=
   let res := zeros ((Z.mul (8) (n))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       update_subrange_vec_dec (res) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))
         ((autocast (T := mword)
           (vec_access_dec (v) (i)))))).

Definition is_none {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => false | None => true end.

Definition is_some {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => true | None => false end.

Definition concat_str_bits {n : Z} (str : string) (x : mword n) : string :=
   String.append (str) ((string_of_bits (x))).

Definition concat_str_dec (str : string) (x : Z) : string := String.append (str) ((dec_str (x))).

Definition undefined_Perm '(tt : unit) : M (Perm) :=
   (internal_pick ([None_; Read; ReadWrite]))  : M (Perm).

Definition undefined_Pte '(tt : unit) : M (Pte) :=
   (undefined_bool (tt)) >>= fun (w__0 : bool) =>
   (undefined_bool (tt)) >>= fun (w__1 : bool) =>
   (undefined_bool (tt)) >>= fun (w__2 : bool) =>
   (undefined_bool (tt)) >>= fun (w__3 : bool) =>
   (undefined_bool (tt)) >>= fun (w__4 : bool) =>
   (undefined_bitvector (44)) >>= fun (w__5 : mword 44) =>
   returnM (({| Pte_valid := w__0;
                Pte_read := w__1;
                Pte_write := w__2;
                Pte_exec := w__3;
                Pte_user := w__4;
                Pte_ppn := w__5 |})).

Definition undefined_TlbEntry '(tt : unit) : M (TlbEntry) :=
   (undefined_bitvector (27)) >>= fun (w__0 : mword 27) =>
   (undefined_bitvector (44)) >>= fun (w__1 : mword 44) =>
   (undefined_Perm (tt)) >>= fun (w__2 : Perm) =>
   returnM (({| TlbEntry_vpn := w__0;  TlbEntry_ppn := w__1;  TlbEntry_perm := w__2 |})).

Definition undefined_MemEntry '(tt : unit) : M (MemEntry) :=
   (undefined_bitvector (56)) >>= fun (w__0 : mword 56) =>
   (undefined_Pte (tt)) >>= fun (w__1 : Pte) =>
   returnM (({| MemEntry_addr := w__0;  MemEntry_pte := w__1 |})).

Definition vpn2 (va : mword 64) : mword 9 := subrange_vec_dec (va) (38) (30).

Definition vpn1 (va : mword 64) : mword 9 := subrange_vec_dec (va) (29) (21).

Definition vpn0 (va : mword 64) : mword 9 := subrange_vec_dec (va) (20) (12).

Definition vpn_of (va : mword 64) : mword 27 := subrange_vec_dec (va) (38) (12).

Definition page_offset (va : mword 64) : mword 12 := subrange_vec_dec (va) (11) (0).

Definition pte_address (table_ppn : mword 44) (index : mword 9) : mword 56 :=
   or_vec ((shiftl ((zero_extend (table_ppn) (56))) (12)))
     ((shiftl ((zero_extend (index) (56))) (3))).

Definition phys_addr (ppn : mword 44) (off : mword 12) : mword 56 :=
   or_vec ((shiftl ((zero_extend (ppn) (56))) (12))) ((zero_extend (off) (56))).

Definition is_leaf (pte : Pte) : bool :=
   if pte.(Pte_read) then true
   else if pte.(Pte_write) then true
   else if pte.(Pte_exec) then true
   else false.

Definition perm_of_pte (pte : Pte) : Perm :=
   if pte.(Pte_write) then ReadWrite else if pte.(Pte_read) then Read else None_.

Fixpoint read_pte (mem : list MemEntry) (addr : mword 56) : option Pte :=
   match mem with
   | [] => None
   | e :: rest =>
      if eq_vec (e.(MemEntry_addr)) (addr) then Some (e.(MemEntry_pte)) else read_pte (rest) (addr)
   end.

Definition translate (core : Core) (mem : list MemEntry) (va : mword 64)
: option ((mword 56 * Perm)) :=
   let l2 : option Pte := read_pte (mem) ((pte_address (core.(Core_satp_ppn)) ((vpn2 (va))))) in
   match l2 with
   | None => None
   | Some p2 =>
      if p2.(Pte_valid) then
        if is_leaf (p2) then None
        else
          let l1 : option Pte := read_pte (mem) ((pte_address (p2.(Pte_ppn)) ((vpn1 (va))))) in
          match l1 with
          | None => None
          | Some p1 =>
             if p1.(Pte_valid) then
               if is_leaf (p1) then None
               else
                 let l0 : option Pte := read_pte (mem) ((pte_address (p1.(Pte_ppn)) ((vpn0 (va))))) in
                 match l0 with
                 | None => None
                 | Some p0 =>
                    if p0.(Pte_valid) then
                      if is_leaf (p0) then
                        Some ((phys_addr (p0.(Pte_ppn)) ((page_offset (va))), perm_of_pte (p0)))
                      else None
                    else None
                 end
             else None
          end
      else None
   end.

Fixpoint find_tlb (entries : list TlbEntry) (vpn : mword 27) (off : mword 12)
: option ((mword 56 * Perm)) :=
   match entries with
   | [] => None
   | e :: rest =>
      if eq_vec (e.(TlbEntry_vpn)) (vpn) then
        Some ((phys_addr (e.(TlbEntry_ppn)) (off), e.(TlbEntry_perm)))
      else find_tlb (rest) (vpn) (off)
   end.

Definition tlb_lookup (core : Core) (va : mword 64) : option ((mword 56 * Perm)) :=
   find_tlb (core.(Core_tlb)) ((vpn_of (va))) ((page_offset (va))).

Definition sfence_vma_all (core : Core) : Core :=
   {| Core_satp_ppn := core.(Core_satp_ppn);  Core_tlb := [] |}.

Fixpoint filter_tlb (entries : list TlbEntry) (vpn : mword 27) : list TlbEntry :=
   match entries with
   | [] => []
   | e :: rest =>
      if eq_vec (e.(TlbEntry_vpn)) (vpn) then filter_tlb (rest) (vpn)
      else e :: (filter_tlb (rest) (vpn))
   end.

Definition sfence_vma_va (core : Core) (va : mword 64) : Core :=
   {| Core_satp_ppn := core.(Core_satp_ppn);
      Core_tlb := filter_tlb (core.(Core_tlb)) ((vpn_of (va))) |}.

Definition initialize_registers '(tt : unit) : unit := tt.

Definition sail_model_init (_ : unit) : unit := initialize_registers (tt).



