(*Generated by Sail from machine.*)


From stdpp Require Import base countable pretty.
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.

Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.

Definition bit : Type := mword 1.

Definition bits (n : Z) : Type := mword n.

Definition vaddr_typ : Type := bits 64.

Definition paddr : Type := bits 56.

Inductive Perm := None_ | Read | ReadWrite.
Definition num_of_Perm (arg_ : Perm) : Z :=
   match arg_ with | None_ => 0 | Read => 1 | ReadWrite => 2 end.

Definition Perm_of_num (arg_ : Z) (*(0 <=? arg_) && (arg_ <=? 2)*) : Perm :=
   let l__0 := arg_ in
   if Z.eqb (l__0) (0) then None_
   else if Z.eqb (l__0) (1) then Read
   else ReadWrite.

Lemma Perm_num_of_roundtrip (x : Perm) : Perm_of_num (num_of_Perm x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_Perm_injective (x y : Perm) : num_of_Perm x = num_of_Perm y -> x = y.
  intro.
  rewrite <- (Perm_num_of_roundtrip x).
  rewrite <- (Perm_num_of_roundtrip y).
  congruence.
Qed.
Definition Perm_eq_dec (x y : Perm) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_Perm x) (num_of_Perm y) with
  | left e => left (num_of_Perm_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition Perm_beq (x y : Perm) : bool :=
  Z.eqb (num_of_Perm x) (num_of_Perm y).
Lemma Perm_beq_iff x y : Perm_beq x y = true <-> x = y.
  unfold Perm_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_Perm_injective | congruence].
Qed.
Lemma Perm_beq_refl x : Perm_beq x x = true.
apply Perm_beq_iff; reflexivity.
Qed.
#[export]
Instance Decidable_eq_Perm : EqDecision Perm := Perm_eq_dec.
#[export]
Instance Countable_Perm : Countable Perm.
refine {|
  encode x := encode (num_of_Perm x);
  decode x := z ← decode x; mret (Perm_of_num z);
|}.
abstract (
  intro s; rewrite decode_encode;
  simpl;
  rewrite Perm_num_of_roundtrip;
  reflexivity).
Defined.
#[export]
Instance dummy_Perm : Inhabited Perm := { inhabitant := None_ }.


Record Pte := {
  Pte_valid : bool;
  Pte_read : bool;
  Pte_write : bool;
  Pte_exec : bool;
  Pte_user : bool;
  Pte_napot : bool;
  Pte_ppn : bits 44;
}.
Arguments Pte : clear implicits.
#[export]
Instance Decidable_eq_Pte : EqDecision Pte.
   intros [x0 x1 x2 x3 x4 x5 x6].
   intros [y0 y1 y2 y3 y4 y5 y6].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
  cmp_record_field x2 y2.
  cmp_record_field x3 y3.
  cmp_record_field x4 y4.
  cmp_record_field x5 y5.
  cmp_record_field x6 y6.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_Pte : Countable Pte.
refine {|
  encode x := encode (Pte_valid x, Pte_read x, Pte_write x, Pte_exec x, Pte_user x, Pte_napot x, Pte_ppn x);
  decode x := '(x0, x1, x2, x3, x4, x5, x6) ← decode x;
              mret (Build_Pte x0 x1 x2 x3 x4 x5 x6)
|}.
abstract (
  intros [x0 x1 x2 x3 x4 x5 x6];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'Pte_valid' := e ]}" :=
  match r with Build_Pte _ (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_Pte e f1 f2 f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'Pte_read' := e ]}" :=
  match r with Build_Pte (_ as f0) _ (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_Pte f0 e f2 f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'Pte_write' := e ]}" :=
  match r with Build_Pte (_ as f0) (_ as f1) _ (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_Pte f0 f1 e f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'Pte_exec' := e ]}" :=
  match r with Build_Pte (_ as f0) (_ as f1) (_ as f2) _ (_ as f4) (_ as f5) (_ as f6) =>
    Build_Pte f0 f1 f2 e f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'Pte_user' := e ]}" :=
  match r with Build_Pte (_ as f0) (_ as f1) (_ as f2) (_ as f3) _ (_ as f5) (_ as f6) =>
    Build_Pte f0 f1 f2 f3 e f5 f6 end (at level 0).
Notation "{[ r 'with' 'Pte_napot' := e ]}" :=
  match r with Build_Pte (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) _ (_ as f6) =>
    Build_Pte f0 f1 f2 f3 f4 e f6 end (at level 0).
Notation "{[ r 'with' 'Pte_ppn' := e ]}" :=
  match r with Build_Pte (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) _ =>
    Build_Pte f0 f1 f2 f3 f4 f5 e end (at level 0).
#[export]
Instance dummy_Pte : Inhabited (Pte) := {
  inhabitant := {|
    Pte_valid := inhabitant;
    Pte_read := inhabitant;
    Pte_write := inhabitant;
    Pte_exec := inhabitant;
    Pte_user := inhabitant;
    Pte_napot := inhabitant;
    Pte_ppn := inhabitant
|} }.


Record TlbEntry := {
  TlbEntry_vaddr : vaddr_typ;
  TlbEntry_vpn : bits 27;
  TlbEntry_ppn : bits 44;
  TlbEntry_perm : Perm;
  TlbEntry_napot : bool;
}.
Arguments TlbEntry : clear implicits.
#[export]
Instance Decidable_eq_TlbEntry : EqDecision TlbEntry.
   intros [x0 x1 x2 x3 x4].
   intros [y0 y1 y2 y3 y4].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
  cmp_record_field x2 y2.
  cmp_record_field x3 y3.
  cmp_record_field x4 y4.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_TlbEntry : Countable TlbEntry.
refine {|
  encode x := encode (TlbEntry_vaddr x, TlbEntry_vpn x, TlbEntry_ppn x, TlbEntry_perm x, TlbEntry_napot x);
  decode x := '(x0, x1, x2, x3, x4) ← decode x;
              mret (Build_TlbEntry x0 x1 x2 x3 x4)
|}.
abstract (
  intros [x0 x1 x2 x3 x4];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'TlbEntry_vaddr' := e ]}" :=
  match r with Build_TlbEntry _ (_ as f1) (_ as f2) (_ as f3) (_ as f4) =>
    Build_TlbEntry e f1 f2 f3 f4 end (at level 0).
Notation "{[ r 'with' 'TlbEntry_vpn' := e ]}" :=
  match r with Build_TlbEntry (_ as f0) _ (_ as f2) (_ as f3) (_ as f4) =>
    Build_TlbEntry f0 e f2 f3 f4 end (at level 0).
Notation "{[ r 'with' 'TlbEntry_ppn' := e ]}" :=
  match r with Build_TlbEntry (_ as f0) (_ as f1) _ (_ as f3) (_ as f4) =>
    Build_TlbEntry f0 f1 e f3 f4 end (at level 0).
Notation "{[ r 'with' 'TlbEntry_perm' := e ]}" :=
  match r with Build_TlbEntry (_ as f0) (_ as f1) (_ as f2) _ (_ as f4) =>
    Build_TlbEntry f0 f1 f2 e f4 end (at level 0).
Notation "{[ r 'with' 'TlbEntry_napot' := e ]}" :=
  match r with Build_TlbEntry (_ as f0) (_ as f1) (_ as f2) (_ as f3) _ =>
    Build_TlbEntry f0 f1 f2 f3 e end (at level 0).
#[export]
Instance dummy_TlbEntry : Inhabited (TlbEntry) := {
  inhabitant := {|
    TlbEntry_vaddr := inhabitant;
    TlbEntry_vpn := inhabitant;
    TlbEntry_ppn := inhabitant;
    TlbEntry_perm := inhabitant;
    TlbEntry_napot := inhabitant
|} }.


Record Core := {
  Core_satp_ppn : bits 44;
  Core_tlb : list TlbEntry;
  Core_hart : Z;
  Core_node : Z;
}.
Arguments Core : clear implicits.
#[export]
Instance Decidable_eq_Core : EqDecision Core.
   intros [x0 x1 x2 x3].
   intros [y0 y1 y2 y3].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
  cmp_record_field x2 y2.
  cmp_record_field x3 y3.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_Core : Countable Core.
refine {|
  encode x := encode (Core_satp_ppn x, Core_tlb x, Core_hart x, Core_node x);
  decode x := '(x0, x1, x2, x3) ← decode x;
              mret (Build_Core x0 x1 x2 x3)
|}.
abstract (
  intros [x0 x1 x2 x3];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'Core_satp_ppn' := e ]}" :=
  match r with Build_Core _ (_ as f1) (_ as f2) (_ as f3) => Build_Core e f1 f2 f3 end (at level 0).
Notation "{[ r 'with' 'Core_tlb' := e ]}" :=
  match r with Build_Core (_ as f0) _ (_ as f2) (_ as f3) => Build_Core f0 e f2 f3 end (at level 0).
Notation "{[ r 'with' 'Core_hart' := e ]}" :=
  match r with Build_Core (_ as f0) (_ as f1) _ (_ as f3) => Build_Core f0 f1 e f3 end (at level 0).
Notation "{[ r 'with' 'Core_node' := e ]}" :=
  match r with Build_Core (_ as f0) (_ as f1) (_ as f2) _ => Build_Core f0 f1 f2 e end (at level 0).
#[export]
Instance dummy_Core : Inhabited (Core) := {
  inhabitant := {|
    Core_satp_ppn := inhabitant;
    Core_tlb := inhabitant;
    Core_hart := inhabitant;
    Core_node := inhabitant
|} }.


Record MemEntry := {
  MemEntry_addr : paddr;
  MemEntry_pte : Pte;
}.
Arguments MemEntry : clear implicits.
#[export]
Instance Decidable_eq_MemEntry : EqDecision MemEntry.
   intros [x0 x1].
   intros [y0 y1].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_MemEntry : Countable MemEntry.
refine {|
  encode x := encode (MemEntry_addr x, MemEntry_pte x);
  decode x := '(x0, x1) ← decode x;
              mret (Build_MemEntry x0 x1)
|}.
abstract (
  intros [x0 x1];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'MemEntry_addr' := e ]}" :=
  match r with Build_MemEntry _ (_ as f1) => Build_MemEntry e f1 end (at level 0).
Notation "{[ r 'with' 'MemEntry_pte' := e ]}" :=
  match r with Build_MemEntry (_ as f0) _ => Build_MemEntry f0 e end (at level 0).
#[export]
Instance dummy_MemEntry : Inhabited (MemEntry) := {
  inhabitant := {| MemEntry_addr := inhabitant; MemEntry_pte := inhabitant
|} }.


Definition PageTable : Type := list MemEntry.

Record Byte := {
  Byte_addr : paddr;
  Byte_data : bits 8;
}.
Arguments Byte : clear implicits.
#[export]
Instance Decidable_eq_Byte : EqDecision Byte.
   intros [x0 x1].
   intros [y0 y1].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_Byte : Countable Byte.
refine {|
  encode x := encode (Byte_addr x, Byte_data x);
  decode x := '(x0, x1) ← decode x;
              mret (Build_Byte x0 x1)
|}.
abstract (
  intros [x0 x1];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'Byte_addr' := e ]}" :=
  match r with Build_Byte _ (_ as f1) => Build_Byte e f1 end (at level 0).
Notation "{[ r 'with' 'Byte_data' := e ]}" :=
  match r with Build_Byte (_ as f0) _ => Build_Byte f0 e end (at level 0).
#[export]
Instance dummy_Byte : Inhabited (Byte) := {
  inhabitant := {| Byte_addr := inhabitant; Byte_data := inhabitant
|} }.


Definition Ram : Type := list Byte.

Record IotlbEntry := {
  IotlbEntry_did : Z;
  IotlbEntry_pasid : Z;
  IotlbEntry_iova : vaddr_typ;
  IotlbEntry_pa : paddr;
  IotlbEntry_perm : Perm;
}.
Arguments IotlbEntry : clear implicits.
#[export]
Instance Decidable_eq_IotlbEntry : EqDecision IotlbEntry.
   intros [x0 x1 x2 x3 x4].
   intros [y0 y1 y2 y3 y4].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
  cmp_record_field x2 y2.
  cmp_record_field x3 y3.
  cmp_record_field x4 y4.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_IotlbEntry : Countable IotlbEntry.
refine {|
  encode x := encode (IotlbEntry_did x, IotlbEntry_pasid x, IotlbEntry_iova x, IotlbEntry_pa x, IotlbEntry_perm x);
  decode x := '(x0, x1, x2, x3, x4) ← decode x;
              mret (Build_IotlbEntry x0 x1 x2 x3 x4)
|}.
abstract (
  intros [x0 x1 x2 x3 x4];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'IotlbEntry_did' := e ]}" :=
  match r with Build_IotlbEntry _ (_ as f1) (_ as f2) (_ as f3) (_ as f4) =>
    Build_IotlbEntry e f1 f2 f3 f4 end (at level 0).
Notation "{[ r 'with' 'IotlbEntry_pasid' := e ]}" :=
  match r with Build_IotlbEntry (_ as f0) _ (_ as f2) (_ as f3) (_ as f4) =>
    Build_IotlbEntry f0 e f2 f3 f4 end (at level 0).
Notation "{[ r 'with' 'IotlbEntry_iova' := e ]}" :=
  match r with Build_IotlbEntry (_ as f0) (_ as f1) _ (_ as f3) (_ as f4) =>
    Build_IotlbEntry f0 f1 e f3 f4 end (at level 0).
Notation "{[ r 'with' 'IotlbEntry_pa' := e ]}" :=
  match r with Build_IotlbEntry (_ as f0) (_ as f1) (_ as f2) _ (_ as f4) =>
    Build_IotlbEntry f0 f1 f2 e f4 end (at level 0).
Notation "{[ r 'with' 'IotlbEntry_perm' := e ]}" :=
  match r with Build_IotlbEntry (_ as f0) (_ as f1) (_ as f2) (_ as f3) _ =>
    Build_IotlbEntry f0 f1 f2 f3 e end (at level 0).
#[export]
Instance dummy_IotlbEntry : Inhabited (IotlbEntry) := {
  inhabitant := {|
    IotlbEntry_did := inhabitant;
    IotlbEntry_pasid := inhabitant;
    IotlbEntry_iova := inhabitant;
    IotlbEntry_pa := inhabitant;
    IotlbEntry_perm := inhabitant
|} }.


Record DevTlbEntry := {
  DevTlbEntry_did : Z;
  DevTlbEntry_iova : vaddr_typ;
  DevTlbEntry_pa : paddr;
  DevTlbEntry_perm : Perm;
}.
Arguments DevTlbEntry : clear implicits.
#[export]
Instance Decidable_eq_DevTlbEntry : EqDecision DevTlbEntry.
   intros [x0 x1 x2 x3].
   intros [y0 y1 y2 y3].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
  cmp_record_field x2 y2.
  cmp_record_field x3 y3.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_DevTlbEntry : Countable DevTlbEntry.
refine {|
  encode x := encode (DevTlbEntry_did x, DevTlbEntry_iova x, DevTlbEntry_pa x, DevTlbEntry_perm x);
  decode x := '(x0, x1, x2, x3) ← decode x;
              mret (Build_DevTlbEntry x0 x1 x2 x3)
|}.
abstract (
  intros [x0 x1 x2 x3];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'DevTlbEntry_did' := e ]}" :=
  match r with Build_DevTlbEntry _ (_ as f1) (_ as f2) (_ as f3) =>
    Build_DevTlbEntry e f1 f2 f3 end (at level 0).
Notation "{[ r 'with' 'DevTlbEntry_iova' := e ]}" :=
  match r with Build_DevTlbEntry (_ as f0) _ (_ as f2) (_ as f3) =>
    Build_DevTlbEntry f0 e f2 f3 end (at level 0).
Notation "{[ r 'with' 'DevTlbEntry_pa' := e ]}" :=
  match r with Build_DevTlbEntry (_ as f0) (_ as f1) _ (_ as f3) =>
    Build_DevTlbEntry f0 f1 e f3 end (at level 0).
Notation "{[ r 'with' 'DevTlbEntry_perm' := e ]}" :=
  match r with Build_DevTlbEntry (_ as f0) (_ as f1) (_ as f2) _ =>
    Build_DevTlbEntry f0 f1 f2 e end (at level 0).
#[export]
Instance dummy_DevTlbEntry : Inhabited (DevTlbEntry) := {
  inhabitant := {|
    DevTlbEntry_did := inhabitant;
    DevTlbEntry_iova := inhabitant;
    DevTlbEntry_pa := inhabitant;
    DevTlbEntry_perm := inhabitant
|} }.


Record PriRequest := {
  PriRequest_did : Z;
  PriRequest_iova : vaddr_typ;
}.
Arguments PriRequest : clear implicits.
#[export]
Instance Decidable_eq_PriRequest : EqDecision PriRequest.
   intros [x0 x1].
   intros [y0 y1].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_PriRequest : Countable PriRequest.
refine {|
  encode x := encode (PriRequest_did x, PriRequest_iova x);
  decode x := '(x0, x1) ← decode x;
              mret (Build_PriRequest x0 x1)
|}.
abstract (
  intros [x0 x1];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'PriRequest_did' := e ]}" :=
  match r with Build_PriRequest _ (_ as f1) => Build_PriRequest e f1 end (at level 0).
Notation "{[ r 'with' 'PriRequest_iova' := e ]}" :=
  match r with Build_PriRequest (_ as f0) _ => Build_PriRequest f0 e end (at level 0).
#[export]
Instance dummy_PriRequest : Inhabited (PriRequest) := {
  inhabitant := {| PriRequest_did := inhabitant; PriRequest_iova := inhabitant
|} }.


Record Machine := {
  Machine_cores : list Core;
  Machine_mem : PageTable;
  Machine_ram : Ram;
  Machine_ipi : list bool;
  Machine_iotlb : list IotlbEntry;
  Machine_devtlbs : list DevTlbEntry;
  Machine_prireqs : list PriRequest;
}.
Arguments Machine : clear implicits.
#[export]
Instance Decidable_eq_Machine : EqDecision Machine.
   intros [x0 x1 x2 x3 x4 x5 x6].
   intros [y0 y1 y2 y3 y4 y5 y6].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
  cmp_record_field x2 y2.
  cmp_record_field x3 y3.
  cmp_record_field x4 y4.
  cmp_record_field x5 y5.
  cmp_record_field x6 y6.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_Machine : Countable Machine.
refine {|
  encode x := encode (Machine_cores x, Machine_mem x, Machine_ram x, Machine_ipi x, Machine_iotlb x, Machine_devtlbs x, Machine_prireqs x);
  decode x := '(x0, x1, x2, x3, x4, x5, x6) ← decode x;
              mret (Build_Machine x0 x1 x2 x3 x4 x5 x6)
|}.
abstract (
  intros [x0 x1 x2 x3 x4 x5 x6];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'Machine_cores' := e ]}" :=
  match r with Build_Machine _ (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_Machine e f1 f2 f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'Machine_mem' := e ]}" :=
  match r with Build_Machine (_ as f0) _ (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_Machine f0 e f2 f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'Machine_ram' := e ]}" :=
  match r with Build_Machine (_ as f0) (_ as f1) _ (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_Machine f0 f1 e f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'Machine_ipi' := e ]}" :=
  match r with Build_Machine (_ as f0) (_ as f1) (_ as f2) _ (_ as f4) (_ as f5) (_ as f6) =>
    Build_Machine f0 f1 f2 e f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'Machine_iotlb' := e ]}" :=
  match r with Build_Machine (_ as f0) (_ as f1) (_ as f2) (_ as f3) _ (_ as f5) (_ as f6) =>
    Build_Machine f0 f1 f2 f3 e f5 f6 end (at level 0).
Notation "{[ r 'with' 'Machine_devtlbs' := e ]}" :=
  match r with Build_Machine (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) _ (_ as f6) =>
    Build_Machine f0 f1 f2 f3 f4 e f6 end (at level 0).
Notation "{[ r 'with' 'Machine_prireqs' := e ]}" :=
  match r with Build_Machine (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) _ =>
    Build_Machine f0 f1 f2 f3 f4 f5 e end (at level 0).
#[export]
Instance dummy_Machine : Inhabited (Machine) := {
  inhabitant := {|
    Machine_cores := inhabitant;
    Machine_mem := inhabitant;
    Machine_ram := inhabitant;
    Machine_ipi := inhabitant;
    Machine_iotlb := inhabitant;
    Machine_devtlbs := inhabitant;
    Machine_prireqs := inhabitant
|} }.


Inductive Region := RAM | MMIO.
Definition num_of_Region (arg_ : Region) : Z := match arg_ with | RAM => 0 | MMIO => 1 end.

Definition Region_of_num (arg_ : Z) (*(0 <=? arg_) && (arg_ <=? 1)*) : Region :=
   let l__0 := arg_ in
   if Z.eqb (l__0) (0) then RAM
   else MMIO.

Lemma Region_num_of_roundtrip (x : Region) : Region_of_num (num_of_Region x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_Region_injective (x y : Region) : num_of_Region x = num_of_Region y -> x = y.
  intro.
  rewrite <- (Region_num_of_roundtrip x).
  rewrite <- (Region_num_of_roundtrip y).
  congruence.
Qed.
Definition Region_eq_dec (x y : Region) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_Region x) (num_of_Region y) with
  | left e => left (num_of_Region_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition Region_beq (x y : Region) : bool :=
  Z.eqb (num_of_Region x) (num_of_Region y).
Lemma Region_beq_iff x y : Region_beq x y = true <-> x = y.
  unfold Region_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_Region_injective | congruence].
Qed.
Lemma Region_beq_refl x : Region_beq x x = true.
apply Region_beq_iff; reflexivity.
Qed.
#[export]
Instance Decidable_eq_Region : EqDecision Region := Region_eq_dec.
#[export]
Instance Countable_Region : Countable Region.
refine {|
  encode x := encode (num_of_Region x);
  decode x := z ← decode x; mret (Region_of_num z);
|}.
abstract (
  intro s; rewrite decode_encode;
  simpl;
  rewrite Region_num_of_roundtrip;
  reflexivity).
Defined.
#[export]
Instance dummy_Region : Inhabited Region := { inhabitant := RAM }.







Variant register : Type :=

.

Definition type_of_register (r : register) : Type :=
  match r with

  end.

Instance Decidable_eq_register : EqDecision register := fun r _ => match r with end.

Instance Countable_register : Countable register := {|
  encode _ := 1%positive;
  decode _ := None;
  decode_encode (r : register) := match r with end
|}.

Definition register_transport {P : Type -> Type} {r r' : register} :
  r = r' -> P (type_of_register r) -> P (type_of_register r') :=
  match r, r' with
  end.

Lemma register_transport_sound {P} {r : register} (e : r = r) (p : P (type_of_register r)) : register_transport e p = p.
Proof.
  destruct r.
Qed.


Definition register_beq (r r' : register) : bool :=
  match r, r' with

  | _, _ => false
  end.

Lemma register_beq_refl (r : register) : register_beq r r = true.
destruct r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Definition register_eq_cast (P : Type -> Type) (r r' : register) : P (type_of_register r) -> option (P (type_of_register r')) :=
  match r, r' with

  | _, _ => fun _ => None
  end.

Definition register_list : list (string * register) := List.concat [

].

Definition string_of_register (r : register) : string :=
  match List.find (fun '(_s, r') => register_beq r r') register_list with
  | Some (s, _r) => s
  | None => "<impossible>"
  end.

Instance Pretty_register : Pretty register :=
  fun reg => string_of_register reg.

Definition register_of_string (s : string) : option register :=
  match List.find (fun '(s', _r) => String.eqb s s') register_list with
  | Some (_s, r) => Some r
  | None => None
  end.

Lemma string_of_register_roundtrip (r : register) :
  register_of_string (string_of_register r) = Some r.
case r; intro r'; destruct r'; reflexivity.
Qed.

#[export] Instance string_of_register_inj : Inj (=) (=) string_of_register.
Proof.
  intros r r' H.
  specialize (string_of_register_roundtrip r) as H1.
  specialize (string_of_register_roundtrip r') as H2.
  rewrite H in H1.
  rewrite H2 in H1.
  congruence.
Qed.
#[export] Hint Extern 1 (register _) => assumption : typeclass_instances.
#[export] Instance Decidable_eq_register_values `(r : register) : EqDecision (type_of_register r) | 100 :=
match r with

end.
#[export] Instance Inhabited_register_values `(r : register) : Inhabited (type_of_register r) | 100 :=
  match r with

end.
#[export] Instance Countable_register_values `(r : register) : Countable (type_of_register r) | 100.
refine {|
  encode := match r with

  end;
  decode := match r with

  end;
|}.
abstract (destruct r; apply decode_encode).
Defined.



(* Definitions to support the lifting to the sequential monad *)
Record regstate := {

}.


Definition init_regstate : regstate := Build_regstate

.

Definition register_lookup (reg : register) (rs : regstate) : type_of_register reg :=
  match reg with

  end.

Definition register_set (reg : register) : type_of_register reg -> regstate -> regstate :=
  match reg with

  end.

Lemma register_lookup_set (r : register) regs v: register_lookup r (register_set r v regs) = v.
destruct regs, r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Lemma irrelevant_register_set (r r' : register) regs v:
  register_beq r r' = false ->
  register_lookup r (register_set r' v regs) = register_lookup r regs.
destruct regs, r, r'; simpl; intro EQ; rewrite ?EQ; reflexivity.
Qed.

Arguments register_set : simpl never.
Arguments register_lookup : simpl never.

Definition register_accessors : register_accessors regstate register type_of_register := (@register_lookup, @register_set).


(* Instantiate library definitions with types. *)

Definition read_reg {E} := @read_reg register type_of_register E.
Definition write_reg {E} := @write_reg register type_of_register E.
Definition MR r a := @monadR register type_of_register a r unit.
Definition M a := @monad register type_of_register a unit.
Definition returnM {A:Type} := @returnm register type_of_register A unit.
Definition returnR {A:Type} (R:Type) := @returnm register type_of_register A (R + unit).
Definition register_ref := @register_ref register type_of_register.