(*Generated by Sail from machine.*)
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.
Require Import machine_types.
Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.


Definition neq_int (x : Z) (y : Z) : bool := negb ((Z.eqb (x) (y))).

Definition neq_bool (x : bool) (y : bool) : bool := negb ((Bool.eqb (x) (y))).

Definition __id (x : Z) : Z := x.

Definition _shl_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shl_int (m) (n) else shr_int (m) ((Z.opp (n))).

Definition _shr_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shr_int (m) (n) else shl_int (m) ((Z.opp (n))).

Definition fdiv_int (n : Z) (m : Z) : Z :=
   if andb ((Z.ltb (n) (0))) ((Z.gtb (m) (0))) then Z.sub ((Z.quot ((Z.add (n) (1))) (m))) (1)
   else if andb ((Z.gtb (n) (0))) ((Z.ltb (m) (0))) then Z.sub ((Z.quot ((Z.sub (n) (1))) (m))) (1)
   else Z.quot (n) (m).

Definition fmod_int (n : Z) (m : Z) : Z := Z.sub (n) ((Z.mul (m) ((fdiv_int (n) (m))))).

Definition sail_mask {v0 : Z} (len : Z) (v : mword v0) (*(len >=? 0) && (v0 >=? 0)*) : mword len :=
   if Z.leb (len) v0 then vector_truncate (v) (len) else zero_extend (v) (len).

Definition sail_ones (n : Z) (*n >=? 0*) : mword n := not_vec ((zeros (n))).

Definition slice_mask (n : Z) (i : Z) (l : Z) (*n >=? 0*) : mword n :=
   if Z.geb (l) (n) then shiftl ((sail_ones (n))) (i)
   else
     let one : bits n := sail_mask (n) ((('b"1")  : bits 1)) in
     shiftl ((sub_vec ((shiftl (one) (l))) (one))) (i).

Definition to_bytes_le (n : Z) (b : mword (8 * n)) (*n >? 0*) : vec (mword 8) n :=
   let res := vector_init (n) ((zeros (8))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       vec_update_dec (res) (i)
         ((autocast (T := mword)
           (subrange_vec_dec (b) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))))))).

Definition from_bytes_le (n : Z) (v : vec (mword 8) n) (*n >? 0*) : mword (8 * n) :=
   let res := zeros ((Z.mul (8) (n))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       update_subrange_vec_dec (res) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))
         ((autocast (T := mword)
           (vec_access_dec (v) (i)))))).

Definition is_none {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => false | None => true end.

Definition is_some {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => true | None => false end.

Definition concat_str_bits {n : Z} (str : string) (x : mword n) : string :=
   String.append (str) ((string_of_bits (x))).

Definition concat_str_dec (str : string) (x : Z) : string := String.append (str) ((dec_str (x))).

Definition undefined_Perm '(tt : unit) : M (Perm) :=
   (internal_pick ([None_; Read; ReadWrite]))  : M (Perm).

Definition undefined_Pte '(tt : unit) : M (Pte) :=
   (undefined_bool (tt)) >>= fun (w__0 : bool) =>
   (undefined_bool (tt)) >>= fun (w__1 : bool) =>
   (undefined_bool (tt)) >>= fun (w__2 : bool) =>
   (undefined_bool (tt)) >>= fun (w__3 : bool) =>
   (undefined_bool (tt)) >>= fun (w__4 : bool) =>
   (undefined_bool (tt)) >>= fun (w__5 : bool) =>
   (undefined_bitvector (44)) >>= fun (w__6 : mword 44) =>
   returnM (({| Pte_valid := w__0;
                Pte_read := w__1;
                Pte_write := w__2;
                Pte_exec := w__3;
                Pte_user := w__4;
                Pte_napot := w__5;
                Pte_ppn := w__6 |})).

Definition undefined_TlbEntry '(tt : unit) : M (TlbEntry) :=
   (undefined_bitvector (64)) >>= fun (w__0 : mword 64) =>
   (undefined_bitvector (27)) >>= fun (w__1 : mword 27) =>
   (undefined_bitvector (44)) >>= fun (w__2 : mword 44) =>
   (undefined_Perm (tt)) >>= fun (w__3 : Perm) =>
   (undefined_bool (tt)) >>= fun (w__4 : bool) =>
   returnM (({| TlbEntry_vaddr := w__0;
                TlbEntry_vpn := w__1;
                TlbEntry_ppn := w__2;
                TlbEntry_perm := w__3;
                TlbEntry_napot := w__4 |})).

Definition undefined_MemEntry '(tt : unit) : M (MemEntry) :=
   (undefined_bitvector (56)) >>= fun (w__0 : mword 56) =>
   (undefined_Pte (tt)) >>= fun (w__1 : Pte) =>
   returnM (({| MemEntry_addr := w__0;  MemEntry_pte := w__1 |})).

Definition undefined_Byte '(tt : unit) : M (Byte) :=
   (undefined_bitvector (56)) >>= fun (w__0 : mword 56) =>
   (undefined_bitvector (8)) >>= fun (w__1 : mword 8) =>
   returnM (({| Byte_addr := w__0;  Byte_data := w__1 |})).

Definition undefined_IotlbEntry '(tt : unit) : M (IotlbEntry) :=
   (undefined_int (tt)) >>= fun (w__0 : Z) =>
   (undefined_int (tt)) >>= fun (w__1 : Z) =>
   (undefined_bitvector (64)) >>= fun (w__2 : mword 64) =>
   (undefined_bitvector (56)) >>= fun (w__3 : mword 56) =>
   (undefined_Perm (tt)) >>= fun (w__4 : Perm) =>
   returnM (({| IotlbEntry_did := w__0;
                IotlbEntry_pasid := w__1;
                IotlbEntry_iova := w__2;
                IotlbEntry_pa := w__3;
                IotlbEntry_perm := w__4 |})).

Definition undefined_DevTlbEntry '(tt : unit) : M (DevTlbEntry) :=
   (undefined_int (tt)) >>= fun (w__0 : Z) =>
   (undefined_bitvector (64)) >>= fun (w__1 : mword 64) =>
   (undefined_bitvector (56)) >>= fun (w__2 : mword 56) =>
   (undefined_Perm (tt)) >>= fun (w__3 : Perm) =>
   returnM (({| DevTlbEntry_did := w__0;
                DevTlbEntry_iova := w__1;
                DevTlbEntry_pa := w__2;
                DevTlbEntry_perm := w__3 |})).

Definition undefined_PriRequest '(tt : unit) : M (PriRequest) :=
   (undefined_int (tt)) >>= fun (w__0 : Z) =>
   (undefined_int (tt)) >>= fun (w__1 : Z) =>
   (undefined_bitvector (64)) >>= fun (w__2 : mword 64) =>
   (undefined_bool (tt)) >>= fun (w__3 : bool) =>
   returnM (({| PriRequest_did := w__0;
                PriRequest_pasid := w__1;
                PriRequest_iova := w__2;
                PriRequest_pending := w__3 |})).

Definition undefined_InvalidationCmd '(tt : unit) : M (InvalidationCmd) :=
   (undefined_bool (tt)) >>= fun (w__0 : bool) =>
   (undefined_bitvector (64)) >>= fun (w__1 : mword 64) =>
   returnM (({| InvalidationCmd_is_wait := w__0;  InvalidationCmd_va := w__1 |})).

Definition undefined_Ste '(tt : unit) : M (Ste) :=
   (undefined_bool (tt)) >>= fun (w__0 : bool) =>
   (undefined_bitvector (44)) >>= fun (w__1 : mword 44) =>
   (undefined_int (tt)) >>= fun (w__2 : Z) =>
   returnM (({| Ste_valid := w__0;  Ste_s2_root := w__1;  Ste_cd_ptr := w__2 |})).

Definition undefined_Cd '(tt : unit) : M (Cd) :=
   (undefined_bool (tt)) >>= fun (w__0 : bool) =>
   (undefined_bitvector (44)) >>= fun (w__1 : mword 44) =>
   (undefined_int (tt)) >>= fun (w__2 : Z) =>
   returnM (({| Cd_valid := w__0;  Cd_s1_root := w__1;  Cd_asid := w__2 |})).

Definition undefined_VtdContext '(tt : unit) : M (VtdContext) :=
   (undefined_bool (tt)) >>= fun (w__0 : bool) =>
   (undefined_int (tt)) >>= fun (w__1 : Z) =>
   (undefined_bitvector (44)) >>= fun (w__2 : mword 44) =>
   returnM (({| VtdContext_present := w__0;
                VtdContext_did := w__1;
                VtdContext_sl_root := w__2 |})).

Definition vpn3 (va : mword 64) : mword 9 := subrange_vec_dec (va) (47) (39).

Definition vpn2 (va : mword 64) : mword 9 := subrange_vec_dec (va) (38) (30).

Definition vpn1 (va : mword 64) : mword 9 := subrange_vec_dec (va) (29) (21).

Definition vpn0 (va : mword 64) : mword 9 := subrange_vec_dec (va) (20) (12).

Definition vpn_of (va : mword 64) : mword 27 := subrange_vec_dec (va) (38) (12).

Definition page_offset (va : mword 64) : mword 12 := subrange_vec_dec (va) (11) (0).

Definition pte_address (table_ppn : mword 44) (index : mword 9) : mword 56 :=
   or_vec ((shiftl ((zero_extend (table_ppn) (56))) (12)))
     ((shiftl ((zero_extend (index) (56))) (3))).

Definition phys_addr (ppn : mword 44) (off : mword 12) : mword 56 :=
   or_vec ((shiftl ((zero_extend (ppn) (56))) (12))) ((zero_extend (off) (56))).

Definition napot_guard (ppn : mword 44) : bool :=
   eq_vec ((subrange_vec_dec (ppn) (3) (0))) (('b"1000")).

Definition napot_phys_addr (ppn : mword 44) (va : mword 64) : mword 56 :=
   or_vec ((shiftl ((zero_extend ((subrange_vec_dec (ppn) (43) (4))) (56))) (16)))
     ((zero_extend ((subrange_vec_dec (va) (15) (0))) (56))).

Definition is_leaf (pte : Pte) : bool :=
   if pte.(Pte_read) then true
   else if pte.(Pte_write) then true
   else if pte.(Pte_exec) then true
   else false.

Definition perm_of_pte (pte : Pte) : Perm :=
   if pte.(Pte_write) then ReadWrite else if pte.(Pte_read) then Read else None_.

Fixpoint read_pte (mem : list MemEntry) (addr : mword 56) : option Pte :=
   match mem with
   | [] => None
   | e :: rest =>
      if eq_vec (e.(MemEntry_addr)) (addr) then Some (e.(MemEntry_pte)) else read_pte (rest) (addr)
   end.

Fixpoint read_byte (ram : list Byte) (addr : mword 56) : option (mword 8) :=
   match ram with
   | [] => None
   | b :: rest =>
      if eq_vec (b.(Byte_addr)) (addr) then Some (b.(Byte_data)) else read_byte (rest) (addr)
   end.

Fixpoint write_byte (ram : list Byte) (addr : mword 56) (v : mword 8) : list Byte :=
   match ram with
   | [] => ({| Byte_addr := addr;  Byte_data := v |}) :: []
   | b :: rest =>
      if eq_vec (b.(Byte_addr)) (addr) then ({| Byte_addr := addr;  Byte_data := v |}) :: rest
      else b :: (write_byte (rest) (addr) (v))
   end.

Definition undefined_Region '(tt : unit) : M (Region) :=
   (internal_pick ([RAM; MMIO]))  : M (Region).

Definition decode_addr (pa : mword 56) : Region :=
   if eq_vec ((access_vec_dec (pa) (55))) (('b"0")) then RAM else MMIO.

Definition translate (core : Core) (mem : list MemEntry) (va : mword 64)
: option ((mword 56 * Perm)) :=
   let l2 : option Pte := read_pte (mem) ((pte_address (core.(Core_satp_ppn)) ((vpn2 (va))))) in
   match l2 with
   | None => None
   | Some p2 =>
      if p2.(Pte_valid) then
        if is_leaf (p2) then None
        else if p2.(Pte_napot) then None
        else
          let l1 : option Pte := read_pte (mem) ((pte_address (p2.(Pte_ppn)) ((vpn1 (va))))) in
          match l1 with
          | None => None
          | Some p1 =>
             if p1.(Pte_valid) then
               if is_leaf (p1) then None
               else if p1.(Pte_napot) then None
               else
                 let l0 : option Pte := read_pte (mem) ((pte_address (p1.(Pte_ppn)) ((vpn0 (va))))) in
                 match l0 with
                 | None => None
                 | Some p0 =>
                    if p0.(Pte_valid) then
                      if andb (p0.(Pte_write)) ((negb (p0.(Pte_read)))) then None
                      else if is_leaf (p0) then
                        if p0.(Pte_napot) then
                          if napot_guard (p0.(Pte_ppn)) then
                            Some ((napot_phys_addr (p0.(Pte_ppn)) (va), perm_of_pte (p0)))
                          else None
                        else
                          Some ((phys_addr (p0.(Pte_ppn)) ((page_offset (va))), perm_of_pte (p0)))
                      else None
                    else None
                 end
             else None
          end
      else None
   end.

Definition iommu_walk (root : mword 44) (mem : list MemEntry) (iova : mword 64)
: option ((mword 56 * Perm)) :=
   translate (({| Core_satp_ppn := root;  Core_tlb := [];  Core_hart := 0;  Core_node := 0 |}))
     (mem) (iova).

Definition smmu_walk
(s1_root : mword 44) (s2_root : mword 44) (mem : list MemEntry) (gva : mword 64)
: option ((mword 56 * Perm)) :=
   match translate
           (({| Core_satp_ppn := s1_root;
                Core_tlb := [];
                Core_hart := 0;
                Core_node := 0 |})) (mem) (gva) with
   | None => None
   | Some (gpa, _) =>
      translate
        (({| Core_satp_ppn := s2_root;
             Core_tlb := [];
             Core_hart := 0;
             Core_node := 0 |})) (mem) ((zero_extend (gpa) (64)))
   end.

Definition amdvi_walk (root : mword 44) (mem : list MemEntry) (iova : mword 64)
: option ((mword 56 * Perm)) :=
   match read_pte (mem) ((pte_address (root) ((vpn3 (iova))))) with
   | None => None
   | Some p3 =>
      if andb (p3.(Pte_valid)) ((andb ((negb ((is_leaf (p3))))) ((negb (p3.(Pte_napot)))))) then
        translate
          (({| Core_satp_ppn := p3.(Pte_ppn);
               Core_tlb := [];
               Core_hart := 0;
               Core_node := 0 |})) (mem) (iova)
      else None
   end.

Fixpoint iotlb_lookup (entries : list IotlbEntry) (did : Z) (va : mword 64)
: option ((mword 56 * Perm)) :=
   match entries with
   | [] => None
   | e :: rest =>
      if andb ((Z.eqb (e.(IotlbEntry_did)) (did)))
           ((eq_vec ((vpn_of (e.(IotlbEntry_iova)))) ((vpn_of (va))))) then
        Some ((e.(IotlbEntry_pa), e.(IotlbEntry_perm)))
      else iotlb_lookup (rest) (did) (va)
   end.

Definition amdvi_translate_fill
(root : mword 44) (iotlb : list IotlbEntry) (mem : list MemEntry) (iova : mword 64)
: (option ((mword 56 * Perm)) * list IotlbEntry) :=
   match iotlb_lookup (iotlb) (0) (iova) with
   | Some r => ((Some (r), iotlb))
   | None =>
      match amdvi_walk (root) (mem) (iova) with
      | None => ((None, iotlb))
      | Some (pa, perm) =>
         ((Some ((pa, perm)), ({| IotlbEntry_did := 0;
                                  IotlbEntry_pasid := 0;
                                  IotlbEntry_iova := iova;
                                  IotlbEntry_pa := pa;
                                  IotlbEntry_perm := perm |}) ::
           iotlb))
      end
   end.

Fixpoint ste_lookup (stes : list Ste) (sid : Z) : option Ste :=
   match (stes, sid) with
   | (s :: g__7, l__0) =>
      if Z.eqb (l__0) (0) then Some (s) else ste_lookup (g__7) ((Z.sub (l__0) (1)))
   | ([], _) => None
   end.

Fixpoint cd_lookup (cds : list Cd) (idx : Z) : option Cd :=
   match (cds, idx) with
   | (c :: g__6, l__0) =>
      if Z.eqb (l__0) (0) then Some (c) else cd_lookup (g__6) ((Z.sub (l__0) (1)))
   | ([], _) => None
   end.

Definition smmu_translate
(stes : list Ste) (cds : list Cd) (sid : Z) (mem : list MemEntry) (gva : mword 64)
: option ((mword 56 * Perm)) :=
   match ste_lookup (stes) (sid) with
   | None => None
   | Some s =>
      if s.(Ste_valid) then
        match cd_lookup (cds) (s.(Ste_cd_ptr)) with
        | None => None
        | Some c =>
           if c.(Cd_valid) then smmu_walk (c.(Cd_s1_root)) (s.(Ste_s2_root)) (mem) (gva) else None
        end
      else None
   end.

Definition smmu_translate_fill
(stes : list Ste) (cds : list Cd) (sid : Z) (iotlb : list IotlbEntry) (mem : list MemEntry)
(gva : mword 64)
: (option ((mword 56 * Perm)) * list IotlbEntry) :=
   match iotlb_lookup (iotlb) (sid) (gva) with
   | Some r => ((Some (r), iotlb))
   | None =>
      match smmu_translate (stes) (cds) (sid) (mem) (gva) with
      | None => ((None, iotlb))
      | Some (pa, perm) =>
         ((Some ((pa, perm)), ({| IotlbEntry_did := sid;
                                  IotlbEntry_pasid := 0;
                                  IotlbEntry_iova := gva;
                                  IotlbEntry_pa := pa;
                                  IotlbEntry_perm := perm |}) ::
           iotlb))
      end
   end.

Fixpoint vtd_context_lookup (contexts : list VtdContext) (rid : Z) : option VtdContext :=
   match (contexts, rid) with
   | (c :: g__5, l__0) =>
      if Z.eqb (l__0) (0) then Some (c) else vtd_context_lookup (g__5) ((Z.sub (l__0) (1)))
   | ([], _) => None
   end.

Definition vtd_walk (contexts : list VtdContext) (rid : Z) (mem : list MemEntry) (iova : mword 64)
: option ((mword 56 * Perm)) :=
   match vtd_context_lookup (contexts) (rid) with
   | None => None
   | Some c =>
      if c.(VtdContext_present) then iommu_walk (c.(VtdContext_sl_root)) (mem) (iova) else None
   end.

Definition undefined_VtdPasid '(tt : unit) : M (VtdPasid) :=
   (undefined_bool (tt)) >>= fun (w__0 : bool) =>
   (undefined_bitvector (44)) >>= fun (w__1 : mword 44) =>
   returnM (({| VtdPasid_present := w__0;  VtdPasid_s1_root := w__1 |})).

Fixpoint vtd_pasid_lookup (ptes : list VtdPasid) (pasid : Z) : option VtdPasid :=
   match (ptes, pasid) with
   | (e :: g__4, l__0) =>
      if Z.eqb (l__0) (0) then Some (e) else vtd_pasid_lookup (g__4) ((Z.sub (l__0) (1)))
   | ([], _) => None
   end.

Definition vtd_walk_pasid
(contexts : list VtdContext) (rid : Z) (ptes : list VtdPasid) (pasid : Z) (mem : list MemEntry)
(iova : mword 64)
: option ((mword 56 * Perm)) :=
   match vtd_context_lookup (contexts) (rid) with
   | None => None
   | Some c =>
      if c.(VtdContext_present) then
        match vtd_pasid_lookup (ptes) (pasid) with
        | None => None
        | Some e =>
           if e.(VtdPasid_present) then
             match iommu_walk (e.(VtdPasid_s1_root)) (mem) (iova) with
             | None => None
             | Some (gpa, _) => iommu_walk (c.(VtdContext_sl_root)) (mem) ((zero_extend (gpa) (64)))
             end
           else None
        end
      else None
   end.

Definition undefined_PasidCacheEntry '(tt : unit) : M (PasidCacheEntry) :=
   (undefined_bool (tt)) >>= fun (w__0 : bool) =>
   (undefined_int (tt)) >>= fun (w__1 : Z) =>
   (undefined_int (tt)) >>= fun (w__2 : Z) =>
   (undefined_int (tt)) >>= fun (w__3 : Z) =>
   (undefined_bitvector (44)) >>= fun (w__4 : mword 44) =>
   returnM (({| PasidCacheEntry_present := w__0;
                PasidCacheEntry_did := w__1;
                PasidCacheEntry_pasid := w__2;
                PasidCacheEntry_gen := w__3;
                PasidCacheEntry_s1_root := w__4 |})).

Fixpoint pasid_cache_lookup (cache : list PasidCacheEntry) (dp : (Z * Z)) : option PasidCacheEntry :=
   match cache with
   | [] => None
   | e :: rest =>
      let '((d, p)) := dp in
      if andb ((Z.eqb (e.(PasidCacheEntry_did)) (d))) ((Z.eqb (e.(PasidCacheEntry_pasid)) (p))) then
        Some (e)
      else pasid_cache_lookup (rest) (dp)
   end.

Definition pasid_cached_walk
(contexts : list VtdContext) (rid : Z) (cache : list PasidCacheEntry) (pasid : Z)
(mem : list MemEntry) (iova : mword 64)
: option ((mword 56 * Perm)) :=
   match vtd_context_lookup (contexts) (rid) with
   | None => None
   | Some c =>
      if c.(VtdContext_present) then
        match pasid_cache_lookup (cache) ((rid, pasid)) with
        | None => None
        | Some e =>
           if e.(PasidCacheEntry_present) then
             match iommu_walk (e.(PasidCacheEntry_s1_root)) (mem) (iova) with
             | None => None
             | Some (gpa, _) => iommu_walk (c.(VtdContext_sl_root)) (mem) ((zero_extend (gpa) (64)))
             end
           else None
        end
      else None
   end.

Definition undefined_VtdDeviceEntry '(tt : unit) : M (VtdDeviceEntry) :=
   (undefined_bool (tt)) >>= fun (w__0 : bool) =>
   (undefined_int (tt)) >>= fun (w__1 : Z) =>
   (undefined_int (tt)) >>= fun (w__2 : Z) =>
   (undefined_int (tt)) >>= fun (w__3 : Z) =>
   returnM (({| VtdDeviceEntry_present := w__0;
                VtdDeviceEntry_did := w__1;
                VtdDeviceEntry_ctx_index := w__2;
                VtdDeviceEntry_pasid_tbl := w__3 |})).

Fixpoint vtd_device_lookup (devtbl : list VtdDeviceEntry) (rid : Z) : option VtdDeviceEntry :=
   match (devtbl, rid) with
   | (e :: g__3, l__0) =>
      if Z.eqb (l__0) (0) then Some (e) else vtd_device_lookup (g__3) ((Z.sub (l__0) (1)))
   | ([], _) => None
   end.

Definition vtd_walk_device
(devtbl : list VtdDeviceEntry) (contexts : list VtdContext) (rid : Z) (mem : list MemEntry)
(iova : mword 64)
: option ((mword 56 * Perm)) :=
   match vtd_device_lookup (devtbl) (rid) with
   | None => None
   | Some d =>
      if d.(VtdDeviceEntry_present) then
        match vtd_context_lookup (contexts) (d.(VtdDeviceEntry_ctx_index)) with
        | None => None
        | Some c =>
           if c.(VtdContext_present) then iommu_walk (c.(VtdContext_sl_root)) (mem) (iova) else None
        end
      else None
   end.

Fixpoint pasid_table_lookup (tbls : list (list VtdPasid)) (idx : Z) : option (list VtdPasid) :=
   match (tbls, idx) with
   | (t :: g__2, l__0) =>
      if Z.eqb (l__0) (0) then Some (t) else pasid_table_lookup (g__2) ((Z.sub (l__0) (1)))
   | ([], _) => None
   end.

Definition vtd_walk_device_pasid
(devtbl : list VtdDeviceEntry) (tbls : list (list VtdPasid)) (contexts : list VtdContext) (rid : Z)
(pasid : Z) (mem : list MemEntry) (iova : mword 64)
: option ((mword 56 * Perm)) :=
   match vtd_device_lookup (devtbl) (rid) with
   | None => None
   | Some d =>
      if d.(VtdDeviceEntry_present) then
        match pasid_table_lookup (tbls) (d.(VtdDeviceEntry_pasid_tbl)) with
        | None => None
        | Some ptes =>
           match vtd_pasid_lookup (ptes) (pasid) with
           | None => None
           | Some e =>
              if e.(VtdPasid_present) then
                match iommu_walk (e.(VtdPasid_s1_root)) (mem) (iova) with
                | None => None
                | Some (gpa, _) =>
                   match vtd_context_lookup (contexts) (d.(VtdDeviceEntry_ctx_index)) with
                   | None => None
                   | Some c =>
                      if c.(VtdContext_present) then
                        iommu_walk (c.(VtdContext_sl_root)) (mem) ((zero_extend (gpa) (64)))
                      else None
                   end
                end
              else None
           end
        end
      else None
   end.

Fixpoint pasid_cache_evict_pasid (cache : list PasidCacheEntry) (dp : (Z * Z))
: list PasidCacheEntry :=
   match cache with
   | [] => []
   | e :: rest =>
      let '((d, p)) := dp in
      if andb ((Z.eqb (e.(PasidCacheEntry_did)) (d))) ((Z.eqb (e.(PasidCacheEntry_pasid)) (p))) then
        ({| PasidCacheEntry_present := false;
            PasidCacheEntry_did := e.(PasidCacheEntry_did);
            PasidCacheEntry_pasid := e.(PasidCacheEntry_pasid);
            PasidCacheEntry_gen := e.(PasidCacheEntry_gen);
            PasidCacheEntry_s1_root := e.(PasidCacheEntry_s1_root) |}) ::
          (pasid_cache_evict_pasid (rest) (dp))
      else e :: (pasid_cache_evict_pasid (rest) (dp))
   end.

Fixpoint pasid_cache_evict_all (cache : list PasidCacheEntry) : list PasidCacheEntry :=
   match cache with
   | [] => []
   | e :: rest =>
      ({| PasidCacheEntry_present := false;
          PasidCacheEntry_did := e.(PasidCacheEntry_did);
          PasidCacheEntry_pasid := e.(PasidCacheEntry_pasid);
          PasidCacheEntry_gen := e.(PasidCacheEntry_gen);
          PasidCacheEntry_s1_root := e.(PasidCacheEntry_s1_root) |}) ::
        (pasid_cache_evict_all (rest))
   end.

Fixpoint pasid_cache_evict (cache : list PasidCacheEntry) (did : Z) : list PasidCacheEntry :=
   match cache with
   | [] => []
   | e :: rest =>
      if Z.eqb (e.(PasidCacheEntry_did)) (did) then
        ({| PasidCacheEntry_present := false;
            PasidCacheEntry_did := e.(PasidCacheEntry_did);
            PasidCacheEntry_pasid := e.(PasidCacheEntry_pasid);
            PasidCacheEntry_gen := e.(PasidCacheEntry_gen);
            PasidCacheEntry_s1_root := e.(PasidCacheEntry_s1_root) |}) ::
          (pasid_cache_evict (rest) (did))
      else e :: (pasid_cache_evict (rest) (did))
   end.

Fixpoint pasid_cache_refill (cache : list PasidCacheEntry) (dp : (Z * Z)) (root : mword 44)
: list PasidCacheEntry :=
   match cache with
   | [] =>
      let '((d, p)) := dp in
      ({| PasidCacheEntry_present := true;
          PasidCacheEntry_did := d;
          PasidCacheEntry_pasid := p;
          PasidCacheEntry_gen := 0;
          PasidCacheEntry_s1_root := root |}) ::
        []
   | e :: rest =>
      let '((d, p)) := dp in
      if andb ((Z.eqb (e.(PasidCacheEntry_did)) (d))) ((Z.eqb (e.(PasidCacheEntry_pasid)) (p))) then
        ({| PasidCacheEntry_present := true;
            PasidCacheEntry_did := e.(PasidCacheEntry_did);
            PasidCacheEntry_pasid := e.(PasidCacheEntry_pasid);
            PasidCacheEntry_gen := e.(PasidCacheEntry_gen);
            PasidCacheEntry_s1_root := root |}) ::
          rest
      else e :: (pasid_cache_refill (rest) (dp) (root))
   end.

Fixpoint pasid_cache_lookup_gen (cache : list PasidCacheEntry) (dp : (Z * Z)) (g : Z)
: option PasidCacheEntry :=
   match cache with
   | [] => None
   | e :: rest =>
      let '((d, p)) := dp in
      if andb ((Z.eqb (e.(PasidCacheEntry_did)) (d)))
           ((andb ((Z.eqb (e.(PasidCacheEntry_pasid)) (p))) ((Z.eqb (e.(PasidCacheEntry_gen)) (g)))))
      then
        Some (e)
      else pasid_cache_lookup_gen (rest) (dp) (g)
   end.

Fixpoint pasid_cache_tag_conflict (cache : list PasidCacheEntry) (dp : (Z * Z)) (g : Z) : bool :=
   match cache with
   | [] => false
   | e :: rest =>
      let '((d, p)) := dp in
      if andb ((Z.eqb (e.(PasidCacheEntry_did)) (d)))
           ((andb ((Z.eqb (e.(PasidCacheEntry_pasid)) (p))) (e.(PasidCacheEntry_present)))) then
        if Z.eqb (e.(PasidCacheEntry_gen)) (g) then pasid_cache_tag_conflict (rest) (dp) (g)
        else true
      else pasid_cache_tag_conflict (rest) (dp) (g)
   end.

Fixpoint pasid_cache_refill_gen
(cache : list PasidCacheEntry) (dp : (Z * Z)) (g : Z) (root : mword 44)
: list PasidCacheEntry :=
   match cache with
   | [] =>
      let '((d, p)) := dp in
      ({| PasidCacheEntry_present := true;
          PasidCacheEntry_did := d;
          PasidCacheEntry_pasid := p;
          PasidCacheEntry_gen := g;
          PasidCacheEntry_s1_root := root |}) ::
        []
   | e :: rest =>
      let '((d, p)) := dp in
      if andb ((Z.eqb (e.(PasidCacheEntry_did)) (d))) ((Z.eqb (e.(PasidCacheEntry_pasid)) (p))) then
        ({| PasidCacheEntry_present := true;
            PasidCacheEntry_did := e.(PasidCacheEntry_did);
            PasidCacheEntry_pasid := e.(PasidCacheEntry_pasid);
            PasidCacheEntry_gen := g;
            PasidCacheEntry_s1_root := root |}) ::
          rest
      else e :: (pasid_cache_refill_gen (rest) (dp) (g) (root))
   end.

Fixpoint pasid_cache_evict_gen (cache : list PasidCacheEntry) (dp : (Z * Z)) (g : Z)
: list PasidCacheEntry :=
   match cache with
   | [] => []
   | e :: rest =>
      let '((d, p)) := dp in
      if andb ((Z.eqb (e.(PasidCacheEntry_did)) (d)))
           ((andb ((Z.eqb (e.(PasidCacheEntry_pasid)) (p)))
               ((neq_int (e.(PasidCacheEntry_gen)) (g))))) then
        ({| PasidCacheEntry_present := false;
            PasidCacheEntry_did := e.(PasidCacheEntry_did);
            PasidCacheEntry_pasid := e.(PasidCacheEntry_pasid);
            PasidCacheEntry_gen := e.(PasidCacheEntry_gen);
            PasidCacheEntry_s1_root := e.(PasidCacheEntry_s1_root) |}) ::
          (pasid_cache_evict_gen (rest) (dp) (g))
      else e :: (pasid_cache_evict_gen (rest) (dp) (g))
   end.

Definition pasid_translate_fill
(contexts : list VtdContext) (rid : Z) (ptes : list VtdPasid) (cache : list PasidCacheEntry)
(pasid : Z) (mem : list MemEntry) (iova : mword 64)
: (option ((mword 56 * Perm)) * list PasidCacheEntry) :=
   match pasid_cache_lookup (cache) ((rid, pasid)) with
   | None => ((None, cache))
   | Some e =>
      if e.(PasidCacheEntry_present) then
        ((pasid_cached_walk (contexts) (rid) (cache) (pasid) (mem) (iova), cache))
      else
        match vtd_pasid_lookup (ptes) (pasid) with
        | None => ((None, cache))
        | Some te =>
           if te.(VtdPasid_present) then
             ((vtd_walk_pasid (contexts) (rid) (ptes) (pasid) (mem) (iova), pasid_cache_refill
                                                                              (cache) ((rid, pasid))
                                                                              (te.(VtdPasid_s1_root))))
           else ((None, cache))
        end
   end.

Definition vtd_walk_device_pasid_cached
(devtbl : list VtdDeviceEntry) (tbls : list (list VtdPasid)) (contexts : list VtdContext) (rid : Z)
(pasid : Z) (cache : list PasidCacheEntry) (mem : list MemEntry) (iova : mword 64)
: option ((mword 56 * Perm)) :=
   match vtd_device_lookup (devtbl) (rid) with
   | None => None
   | Some d =>
      if d.(VtdDeviceEntry_present) then
        match pasid_cache_lookup (cache) ((d.(VtdDeviceEntry_did), pasid)) with
        | None => None
        | Some e =>
           if e.(PasidCacheEntry_present) then
             match iommu_walk (e.(PasidCacheEntry_s1_root)) (mem) (iova) with
             | None => None
             | Some (gpa, _) =>
                match vtd_context_lookup (contexts) (d.(VtdDeviceEntry_ctx_index)) with
                | None => None
                | Some c =>
                   if c.(VtdContext_present) then
                     iommu_walk (c.(VtdContext_sl_root)) (mem) ((zero_extend (gpa) (64)))
                   else None
                end
             end
           else None
        end
      else None
   end.

Definition vtd_device_translate_fill
(devtbl : list VtdDeviceEntry) (tbls : list (list VtdPasid)) (contexts : list VtdContext) (rid : Z)
(pasid : Z) (cache : list PasidCacheEntry) (mem : list MemEntry) (iova : mword 64)
: (option ((mword 56 * Perm)) * list PasidCacheEntry) :=
   match vtd_device_lookup (devtbl) (rid) with
   | None => ((None, cache))
   | Some d =>
      if d.(VtdDeviceEntry_present) then
        match pasid_cache_lookup (cache) ((d.(VtdDeviceEntry_did), pasid)) with
        | None => ((None, cache))
        | Some e =>
           if e.(PasidCacheEntry_present) then
             ((vtd_walk_device_pasid_cached (devtbl) (tbls) (contexts) (rid) (pasid) (cache) (mem)
                 (iova), cache))
           else
             match pasid_table_lookup (tbls) (d.(VtdDeviceEntry_pasid_tbl)) with
             | None => ((None, cache))
             | Some ptes =>
                match vtd_pasid_lookup (ptes) (pasid) with
                | None => ((None, cache))
                | Some te =>
                   if te.(VtdPasid_present) then
                     ((vtd_walk_device_pasid (devtbl) (tbls) (contexts) (rid) (pasid) (mem) (iova), pasid_cache_refill
                                                                                                      (cache)
                                                                                                      ((d.(VtdDeviceEntry_did), pasid))
                                                                                                      (te.(VtdPasid_s1_root))))
                   else ((None, cache))
                end
             end
        end
      else ((None, cache))
   end.

Definition undefined_FaultReason '(tt : unit) : M (FaultReason) :=
   (internal_pick
      ([FR_ContextMissing;
      FR_ContextNotPresent;
      FR_PasidMissing;
      FR_PasidNotPresent;
      FR_Stage1Fault;
      FR_Stage2Fault]))
    : M (FaultReason).

Definition undefined_FaultRecord '(tt : unit) : M (FaultRecord) :=
   (undefined_int (tt)) >>= fun (w__0 : Z) =>
   (undefined_int (tt)) >>= fun (w__1 : Z) =>
   (undefined_bitvector (64)) >>= fun (w__2 : mword 64) =>
   (undefined_FaultReason (tt)) >>= fun (w__3 : FaultReason) =>
   returnM (({| FaultRecord_did := w__0;
                FaultRecord_pasid := w__1;
                FaultRecord_iova := w__2;
                FaultRecord_reason := w__3 |})).

Definition vtd_record_fault
(contexts : list VtdContext) (rid : Z) (ptes : list VtdPasid) (pasid : Z) (mem : list MemEntry)
(iova : mword 64)
: option FaultRecord :=
   match vtd_context_lookup (contexts) (rid) with
   | None =>
      Some
        (({| FaultRecord_did := rid;
             FaultRecord_pasid := pasid;
             FaultRecord_iova := iova;
             FaultRecord_reason := FR_ContextMissing |}))
   | Some c =>
      if c.(VtdContext_present) then
        match vtd_pasid_lookup (ptes) (pasid) with
        | None =>
           Some
             (({| FaultRecord_did := rid;
                  FaultRecord_pasid := pasid;
                  FaultRecord_iova := iova;
                  FaultRecord_reason := FR_PasidMissing |}))
        | Some e =>
           if e.(VtdPasid_present) then
             match iommu_walk (e.(VtdPasid_s1_root)) (mem) (iova) with
             | None =>
                Some
                  (({| FaultRecord_did := rid;
                       FaultRecord_pasid := pasid;
                       FaultRecord_iova := iova;
                       FaultRecord_reason := FR_Stage1Fault |}))
             | Some (gpa, _) =>
                match iommu_walk (c.(VtdContext_sl_root)) (mem) ((zero_extend (gpa) (64))) with
                | None =>
                   Some
                     (({| FaultRecord_did := rid;
                          FaultRecord_pasid := pasid;
                          FaultRecord_iova := iova;
                          FaultRecord_reason := FR_Stage2Fault |}))
                | Some _ => None
                end
             end
           else
             Some
               (({| FaultRecord_did := rid;
                    FaultRecord_pasid := pasid;
                    FaultRecord_iova := iova;
                    FaultRecord_reason := FR_PasidNotPresent |}))
        end
      else
        Some
          (({| FaultRecord_did := rid;
               FaultRecord_pasid := pasid;
               FaultRecord_iova := iova;
               FaultRecord_reason := FR_ContextNotPresent |}))
   end.

Definition undefined_FrcdEntry '(tt : unit) : M (FrcdEntry) :=
   (undefined_int (tt)) >>= fun (w__0 : Z) =>
   (undefined_int (tt)) >>= fun (w__1 : Z) =>
   (undefined_bitvector (64)) >>= fun (w__2 : mword 64) =>
   (undefined_FaultReason (tt)) >>= fun (w__3 : FaultReason) =>
   returnM (({| FrcdEntry_did := w__0;
                FrcdEntry_pasid := w__1;
                FrcdEntry_iova := w__2;
                FrcdEntry_reason := w__3 |})).

Definition frcd_record (fr : FaultRecord) (cache : list FrcdEntry) : list FrcdEntry :=
   ({| FrcdEntry_did := fr.(FaultRecord_did);
       FrcdEntry_pasid := fr.(FaultRecord_pasid);
       FrcdEntry_iova := fr.(FaultRecord_iova);
       FrcdEntry_reason := fr.(FaultRecord_reason) |}) ::
     cache.

Definition frcd_matches (e : FrcdEntry) (d : Z) (p : Z) (va : mword 64) : bool :=
   andb ((Z.eqb (e.(FrcdEntry_did)) (d)))
     ((andb ((Z.eqb (e.(FrcdEntry_pasid)) (p))) ((eq_vec (e.(FrcdEntry_iova)) (va))))).

Fixpoint frcd_lookup (cache : list FrcdEntry) (dp : (Z * Z)) (va : mword 64) : option FrcdEntry :=
   match cache with
   | [] => None
   | e :: rest =>
      let '((d, p)) := dp in
      if andb ((Z.eqb (e.(FrcdEntry_did)) (d)))
           ((andb ((Z.eqb (e.(FrcdEntry_pasid)) (p))) ((eq_vec (e.(FrcdEntry_iova)) (va))))) then
        Some (e)
      else frcd_lookup (rest) (dp) (va)
   end.

Definition frcd_pending (cache : list FrcdEntry) : bool :=
   match cache with | [] => false | _ => true end.

Definition fault_msg_did_pasid (e : FrcdEntry) : (Z * Z) :=
   ((e.(FrcdEntry_did), e.(FrcdEntry_pasid))).

Definition frcd_head (cache : list FrcdEntry) : option FrcdEntry :=
   match cache with | [] => None | e :: _ => Some (e) end.

Definition frcd_clear (cache : list FrcdEntry) : list FrcdEntry :=
   match cache with | [] => [] | _ :: rest => rest end.

Fixpoint frcd_drain (cache : list FrcdEntry) : list FrcdEntry :=
   match cache with | [] => [] | _ :: rest => frcd_drain (rest) end.

Fixpoint iotlb_invalidate (entries : list IotlbEntry) (va : mword 64) : list IotlbEntry :=
   match entries with
   | [] => []
   | e :: rest =>
      if eq_vec ((vpn_of (e.(IotlbEntry_iova)))) ((vpn_of (va))) then iotlb_invalidate (rest) (va)
      else e :: (iotlb_invalidate (rest) (va))
   end.

Fixpoint iommu_process_queue (queue : list InvalidationCmd) (iotlb : list IotlbEntry)
: option (list IotlbEntry) :=
   match queue with
   | [] => None
   | c :: rest =>
      if c.(InvalidationCmd_is_wait) then Some (iotlb)
      else iommu_process_queue (rest) ((iotlb_invalidate (iotlb) (c.(InvalidationCmd_va))))
   end.

Definition ats_translate
(iotlb : list IotlbEntry) (devtlbs : list DevTlbEntry) (root : mword 44) (did : Z) (iova : mword 64)
(mem : list MemEntry)
: (list IotlbEntry * list DevTlbEntry) :=
   match iommu_walk (root) (mem) (iova) with
   | None => ((iotlb, devtlbs))
   | Some (pa, perm) =>
      ((({| IotlbEntry_did := did;
            IotlbEntry_pasid := 0;
            IotlbEntry_iova := iova;
            IotlbEntry_pa := pa;
            IotlbEntry_perm := perm |}) ::
        iotlb, ({| DevTlbEntry_did := did;
                   DevTlbEntry_iova := iova;
                   DevTlbEntry_pa := pa;
                   DevTlbEntry_perm := perm |}) ::
        devtlbs))
   end.

Fixpoint ats_invalidate (devtlbs : list DevTlbEntry) (va : mword 64) : list DevTlbEntry :=
   match devtlbs with
   | [] => []
   | e :: rest =>
      if eq_vec ((vpn_of (e.(DevTlbEntry_iova)))) ((vpn_of (va))) then ats_invalidate (rest) (va)
      else e :: (ats_invalidate (rest) (va))
   end.

Definition iotlb_invalidate_all (entries : list IotlbEntry) : list IotlbEntry := [].

Definition ats_invalidate_all (devtlbs : list DevTlbEntry) : list DevTlbEntry := [].

Fixpoint ats_invalidate_domain (devtlbs : list DevTlbEntry) (did : Z) : list DevTlbEntry :=
   match devtlbs with
   | [] => []
   | e :: rest =>
      if Z.eqb (e.(DevTlbEntry_did)) (did) then ats_invalidate_domain (rest) (did)
      else e :: (ats_invalidate_domain (rest) (did))
   end.

Fixpoint iotlb_invalidate_pasid (entries : list IotlbEntry) (asid : Z) : list IotlbEntry :=
   match entries with
   | [] => []
   | e :: rest =>
      if Z.eqb (e.(IotlbEntry_pasid)) (asid) then iotlb_invalidate_pasid (rest) (asid)
      else e :: (iotlb_invalidate_pasid (rest) (asid))
   end.

Fixpoint iotlb_invalidate_domain (entries : list IotlbEntry) (did : Z) : list IotlbEntry :=
   match entries with
   | [] => []
   | e :: rest =>
      if Z.eqb (e.(IotlbEntry_did)) (did) then iotlb_invalidate_domain (rest) (did)
      else e :: (iotlb_invalidate_domain (rest) (did))
   end.

Fixpoint pri_request (prireqs : list PriRequest) (dp : (Z * Z)) (iova : mword 64) : list PriRequest :=
   match prireqs with
   | [] =>
      let '((d, p)) := dp in
      ({| PriRequest_did := d;
          PriRequest_pasid := p;
          PriRequest_iova := iova;
          PriRequest_pending := true |}) ::
        []
   | r :: rest =>
      let '((d, p)) := dp in
      if andb ((Z.eqb (r.(PriRequest_did)) (d)))
           ((andb ((Z.eqb (r.(PriRequest_pasid)) (p))) ((eq_vec (r.(PriRequest_iova)) (iova)))))
      then
        ({| PriRequest_did := r.(PriRequest_did);
            PriRequest_pasid := r.(PriRequest_pasid);
            PriRequest_iova := r.(PriRequest_iova);
            PriRequest_pending := true |}) ::
          rest
      else r :: (pri_request (rest) (dp) (iova))
   end.

Fixpoint pri_lookup (prireqs : list PriRequest) (dp : (Z * Z)) (iova : mword 64) : option PriRequest :=
   match prireqs with
   | [] => None
   | r :: rest =>
      let '((d, p)) := dp in
      if andb ((Z.eqb (r.(PriRequest_did)) (d)))
           ((andb ((Z.eqb (r.(PriRequest_pasid)) (p))) ((eq_vec (r.(PriRequest_iova)) (iova)))))
      then
        Some (r)
      else pri_lookup (rest) (dp) (iova)
   end.

Definition pri_pending (prireqs : list PriRequest) (dp : (Z * Z)) (iova : mword 64) : bool :=
   match pri_lookup (prireqs) (dp) (iova) with
   | None => false
   | Some r => r.(PriRequest_pending)
   end.

Fixpoint pri_resolve (prireqs : list PriRequest) (dp : (Z * Z)) (iova : mword 64) : list PriRequest :=
   match prireqs with
   | [] => []
   | r :: rest =>
      let '((d, p)) := dp in
      if andb ((Z.eqb (r.(PriRequest_did)) (d)))
           ((andb ((Z.eqb (r.(PriRequest_pasid)) (p))) ((eq_vec (r.(PriRequest_iova)) (iova)))))
      then
        ({| PriRequest_did := r.(PriRequest_did);
            PriRequest_pasid := r.(PriRequest_pasid);
            PriRequest_iova := r.(PriRequest_iova);
            PriRequest_pending := false |}) ::
          rest
      else r :: (pri_resolve (rest) (dp) (iova))
   end.

Definition pri_fault_delivers
(prireqs : list PriRequest) (dp : (Z * Z)) (iova : mword 64) (reason : FaultReason)
: option FaultRecord :=
   if pri_pending (prireqs) (dp) (iova) then
     let '((d, p)) := dp in
     Some
       (({| FaultRecord_did := d;
            FaultRecord_pasid := p;
            FaultRecord_iova := iova;
            FaultRecord_reason := reason |}))
   else None.

Definition tag_eq (e : TlbEntry) (vpn : mword 27) : bool :=
   if e.(TlbEntry_napot) then
     eq_vec ((subrange_vec_dec (e.(TlbEntry_vpn)) (26) (4))) ((subrange_vec_dec (vpn) (26) (4)))
   else eq_vec (e.(TlbEntry_vpn)) (vpn).

Definition tlb_pa (e : TlbEntry) (va : mword 64) : mword 56 :=
   if e.(TlbEntry_napot) then napot_phys_addr (e.(TlbEntry_ppn)) (va)
   else phys_addr (e.(TlbEntry_ppn)) ((page_offset (va))).

Fixpoint find_tlb (entries : list TlbEntry) (va : mword 64) : option ((mword 56 * Perm)) :=
   match entries with
   | [] => None
   | e :: rest =>
      if tag_eq (e) ((vpn_of (va))) then Some ((tlb_pa (e) (va), e.(TlbEntry_perm)))
      else find_tlb (rest) (va)
   end.

Definition tlb_lookup (core : Core) (va : mword 64) : option ((mword 56 * Perm)) :=
   find_tlb (core.(Core_tlb)) (va).

Fixpoint find_devtlb (entries : list DevTlbEntry) (iova : mword 64) : option ((mword 56 * Perm)) :=
   match entries with
   | [] => None
   | e :: rest =>
      if eq_vec ((vpn_of (e.(DevTlbEntry_iova)))) ((vpn_of (iova))) then
        Some ((e.(DevTlbEntry_pa), e.(DevTlbEntry_perm)))
      else find_devtlb (rest) (iova)
   end.

Definition sfence_vma_all (core : Core) : Core :=
   {| Core_satp_ppn := core.(Core_satp_ppn);
      Core_tlb := [];
      Core_hart := core.(Core_hart);
      Core_node := core.(Core_node) |}.

Fixpoint filter_tlb (entries : list TlbEntry) (vpn : mword 27) : list TlbEntry :=
   match entries with
   | [] => []
   | e :: rest =>
      if tag_eq (e) (vpn) then filter_tlb (rest) (vpn) else e :: (filter_tlb (rest) (vpn))
   end.

Definition sfence_vma_va (core : Core) (va : mword 64) : Core :=
   {| Core_satp_ppn := core.(Core_satp_ppn);
      Core_tlb := filter_tlb (core.(Core_tlb)) ((vpn_of (va)));
      Core_hart := core.(Core_hart);
      Core_node := core.(Core_node) |}.

Fixpoint list_update_bool (l : list bool) (i : Z) (v : bool) : list bool :=
   match (l, i) with
   | (g__1 :: rest, l__0) =>
      if Z.eqb (l__0) (0) then v :: rest
      else g__1 :: (list_update_bool (rest) ((Z.sub (l__0) (1))) (v))
   | ([], _) => []
   end.

Fixpoint list_nth_bool (l : list bool) (i : Z) (d : bool) : bool :=
   match (l, i) with
   | (x :: g__0, l__0) =>
      if Z.eqb (l__0) (0) then x else list_nth_bool (g__0) ((Z.sub (l__0) (1))) (d)
   | ([], _) => d
   end.

Definition deliver_ipi (m : Machine) (i : Z) : Machine :=
   {| Machine_cores := m.(Machine_cores);
      Machine_mem := m.(Machine_mem);
      Machine_ram := m.(Machine_ram);
      Machine_ipi := list_update_bool (m.(Machine_ipi)) (i) (true);
      Machine_iotlb := m.(Machine_iotlb);
      Machine_devtlbs := m.(Machine_devtlbs);
      Machine_prireqs := m.(Machine_prireqs);
      Machine_ioqueue := m.(Machine_ioqueue);
      Machine_stes := m.(Machine_stes);
      Machine_cds := m.(Machine_cds) |}.

Fixpoint receive_ipi_cores (cores : list Core) (i : Z) (delivered : bool) (va : mword 64)
: list Core :=
   match (cores, i) with
   | (c :: cs, l__0) =>
      if Z.eqb (l__0) (0) then (if delivered then sfence_vma_va (c) (va) else c) :: cs
      else c :: (receive_ipi_cores (cs) ((Z.sub (l__0) (1))) (delivered) (va))
   | ([], _) => []
   end.

Definition receive_ipi (m : Machine) (i : Z) (va : mword 64) : Machine :=
   {| Machine_cores :=
        receive_ipi_cores (m.(Machine_cores)) (i) ((list_nth_bool (m.(Machine_ipi)) (i) (false)))
          (va);
      Machine_mem := m.(Machine_mem);
      Machine_ram := m.(Machine_ram);
      Machine_ipi := m.(Machine_ipi);
      Machine_iotlb := m.(Machine_iotlb);
      Machine_devtlbs := m.(Machine_devtlbs);
      Machine_prireqs := m.(Machine_prireqs);
      Machine_ioqueue := m.(Machine_ioqueue);
      Machine_stes := m.(Machine_stes);
      Machine_cds := m.(Machine_cds) |}.

Definition initialize_registers '(tt : unit) : unit := tt.

Definition sail_model_init (_ : unit) : unit := initialize_registers (tt).



