(*Generated by Sail from mips_tlb.*)
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.
Require Import mips_tlb_types.
Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.


Definition neq_int (x : Z) (y : Z) : bool := negb ((Z.eqb (x) (y))).

Definition neq_bool (x : bool) (y : bool) : bool := negb ((Bool.eqb (x) (y))).

Definition __id (x : Z) : Z := x.

Definition _shl_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shl_int (m) (n) else shr_int (m) ((Z.opp (n))).

Definition _shr_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shr_int (m) (n) else shl_int (m) ((Z.opp (n))).

Definition fdiv_int (n : Z) (m : Z) : Z :=
   if andb ((Z.ltb (n) (0))) ((Z.gtb (m) (0))) then Z.sub ((Z.quot ((Z.add (n) (1))) (m))) (1)
   else if andb ((Z.gtb (n) (0))) ((Z.ltb (m) (0))) then Z.sub ((Z.quot ((Z.sub (n) (1))) (m))) (1)
   else Z.quot (n) (m).

Definition fmod_int (n : Z) (m : Z) : Z := Z.sub (n) ((Z.mul (m) ((fdiv_int (n) (m))))).

Definition sail_mask {v0 : Z} (len : Z) (v : mword v0) (*(len >=? 0) && (v0 >=? 0)*) : mword len :=
   if Z.leb (len) v0 then vector_truncate (v) (len) else zero_extend (v) (len).

Definition sail_ones (n : Z) (*n >=? 0*) : mword n := not_vec ((zeros (n))).

Definition slice_mask (n : Z) (i : Z) (l : Z) (*n >=? 0*) : mword n :=
   if Z.geb (l) (n) then shiftl ((sail_ones (n))) (i)
   else
     let one : bits n := sail_mask (n) ((('b"1")  : bits 1)) in
     shiftl ((sub_vec ((shiftl (one) (l))) (one))) (i).

Definition to_bytes_le (n : Z) (b : mword (8 * n)) (*n >? 0*) : vec (mword 8) n :=
   let res := vector_init (n) ((zeros (8))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       vec_update_dec (res) (i)
         ((autocast (T := mword)
           (subrange_vec_dec (b) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))))))).

Definition from_bytes_le (n : Z) (v : vec (mword 8) n) (*n >? 0*) : mword (8 * n) :=
   let res := zeros ((Z.mul (8) (n))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       update_subrange_vec_dec (res) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))
         ((autocast (T := mword)
           (vec_access_dec (v) (i)))))).

Definition is_none {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => false | None => true end.

Definition is_some {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => true | None => false end.

Definition concat_str_bits {n : Z} (str : string) (x : mword n) : string :=
   String.append (str) ((string_of_bits (x))).

Definition concat_str_dec (str : string) (x : Z) : string := String.append (str) ((dec_str (x))).

Definition even (n : Z) : bool := Z.eqb ((Z.rem (n) (2))) (0).

Definition cto18 (v : mword 18) : Z := count_trailing_zeros ((not_vec (v))).

Definition compute_mask_level (reg : mword 29) (esp : bool) : option Z :=
   let raw : bits 18 := subrange_vec_dec (reg) (28) (11) in
   let field' : bits 18 := if esp then raw else zero_extend ((subrange_vec_dec (raw) (17) (2))) (18) in
   let k := cto18 (field') in
   if andb ((eq_vec ((shiftr (field') (k))) ((zeros (18))))) ((even (k))) then Some (k)
   else None.

Definition mips_base_shift (esp : bool) : Z := if esp then 10 else 12.

Definition mips_page_shift (esp : bool) (level : Z) : Z := Z.add ((mips_base_shift (esp))) (level).

Definition undefined_MipsEntry '(tt : unit) : M (MipsEntry) :=
   (undefined_bitvector (30)) >>= fun (w__0 : mword 30) =>
   (undefined_bitvector (44)) >>= fun (w__1 : mword 44) =>
   (undefined_int (tt)) >>= fun (w__2 : Z) =>
   (undefined_bool (tt)) >>= fun (w__3 : bool) =>
   returnM (({| MipsEntry_vpn := w__0;
                MipsEntry_pfn := w__1;
                MipsEntry_level := w__2;
                MipsEntry_esp := w__3 |})).

Definition mips_vpn_of (va : mword 64) : Z := uint ((subrange_vec_dec (va) (39) (10))).

Definition mips_vpn2x (va : mword 64) : mword 2 := subrange_vec_dec (va) (12) (11).

Definition mips_covers (e : MipsEntry) (va : mword 64) : bool :=
   let shift := Z.add (e.(MipsEntry_level)) ((Z.sub ((mips_base_shift (e.(MipsEntry_esp)))) (10))) in
   eq_vec ((shiftr (e.(MipsEntry_vpn)) (shift)))
     ((shiftr ((subrange_vec_dec (va) (39) (10))) (shift))).

Definition mips_pa (e : MipsEntry) (va : mword 64) : mword 56 :=
   let ps := mips_page_shift (e.(MipsEntry_esp)) (e.(MipsEntry_level)) in
   let pfn_hi := shiftr (e.(MipsEntry_pfn)) (e.(MipsEntry_level)) in
   let off := shiftr ((shiftl (va) ((Z.sub (64) (ps))))) ((Z.sub (64) (ps))) in
   or_vec ((shiftl ((zero_extend (pfn_hi) (56))) (ps)))
     ((zero_extend ((subrange_vec_dec (off) (55) (0))) (56))).

Definition mips_refill (e : MipsEntry) (tlb : list MipsEntry) : list MipsEntry := e :: tlb.

Fixpoint mips_lookup (tlb : list MipsEntry) (va : mword 64) : option (mword 56) :=
   match tlb with
   | [] => None
   | e :: rest =>
      if mips_covers (e) (va) then Some ((mips_pa (e) (va))) else mips_lookup (rest) (va)
   end.

Definition initialize_registers '(tt : unit) : unit := tt.

Definition sail_model_init (_ : unit) : unit := initialize_registers (tt).



