(*Generated by Sail from net.*)


From stdpp Require Import base countable pretty.
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.

Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.

Definition bit : Type := mword 1.

Definition bits (n : Z) : Type := mword n.

Record DmaDesc := {
  DmaDesc_addr : bits 48;
  DmaDesc_len : bits 16;
  DmaDesc_flags : bits 8;
  DmaDesc_status : bits 8;
}.
Arguments DmaDesc : clear implicits.
#[export]
Instance Decidable_eq_DmaDesc : EqDecision DmaDesc.
   intros [x0 x1 x2 x3].
   intros [y0 y1 y2 y3].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
  cmp_record_field x2 y2.
  cmp_record_field x3 y3.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_DmaDesc : Countable DmaDesc.
refine {|
  encode x := encode (DmaDesc_addr x, DmaDesc_len x, DmaDesc_flags x, DmaDesc_status x);
  decode x := '(x0, x1, x2, x3) ← decode x;
              mret (Build_DmaDesc x0 x1 x2 x3)
|}.
abstract (
  intros [x0 x1 x2 x3];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'DmaDesc_addr' := e ]}" :=
  match r with Build_DmaDesc _ (_ as f1) (_ as f2) (_ as f3) =>
    Build_DmaDesc e f1 f2 f3 end (at level 0).
Notation "{[ r 'with' 'DmaDesc_len' := e ]}" :=
  match r with Build_DmaDesc (_ as f0) _ (_ as f2) (_ as f3) =>
    Build_DmaDesc f0 e f2 f3 end (at level 0).
Notation "{[ r 'with' 'DmaDesc_flags' := e ]}" :=
  match r with Build_DmaDesc (_ as f0) (_ as f1) _ (_ as f3) =>
    Build_DmaDesc f0 f1 e f3 end (at level 0).
Notation "{[ r 'with' 'DmaDesc_status' := e ]}" :=
  match r with Build_DmaDesc (_ as f0) (_ as f1) (_ as f2) _ =>
    Build_DmaDesc f0 f1 f2 e end (at level 0).
#[export]
Instance dummy_DmaDesc : Inhabited (DmaDesc) := {
  inhabitant := {|
    DmaDesc_addr := inhabitant;
    DmaDesc_len := inhabitant;
    DmaDesc_flags := inhabitant;
    DmaDesc_status := inhabitant
|} }.


Record NetRegs := {
  NetRegs_tx_ring_base : bits 48;
  NetRegs_tx_ring_len : bits 16;
  NetRegs_tx_head : bits 16;
  NetRegs_tx_tail : bits 16;
  NetRegs_rx_ring_base : bits 48;
  NetRegs_rx_ring_len : bits 16;
  NetRegs_rx_head : bits 16;
  NetRegs_rx_tail : bits 16;
  NetRegs_ctrl : bits 32;
  NetRegs_status : bits 32;
  NetRegs_irq_status : bits 32;
}.
Arguments NetRegs : clear implicits.
#[export]
Instance Decidable_eq_NetRegs : EqDecision NetRegs.
   intros [x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10].
   intros [y0 y1 y2 y3 y4 y5 y6 y7 y8 y9 y10].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
  cmp_record_field x2 y2.
  cmp_record_field x3 y3.
  cmp_record_field x4 y4.
  cmp_record_field x5 y5.
  cmp_record_field x6 y6.
  cmp_record_field x7 y7.
  cmp_record_field x8 y8.
  cmp_record_field x9 y9.
  cmp_record_field x10 y10.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_NetRegs : Countable NetRegs.
refine {|
  encode x := encode (NetRegs_tx_ring_base x, NetRegs_tx_ring_len x, NetRegs_tx_head x, NetRegs_tx_tail x, NetRegs_rx_ring_base x, NetRegs_rx_ring_len x, NetRegs_rx_head x, NetRegs_rx_tail x, NetRegs_ctrl x, NetRegs_status x, NetRegs_irq_status x);
  decode x := '(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10) ← decode x;
              mret (Build_NetRegs x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10)
|}.
abstract (
  intros [x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'NetRegs_tx_ring_base' := e ]}" :=
  match r with Build_NetRegs _ (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) =>
    Build_NetRegs e f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 end (at level 0).
Notation "{[ r 'with' 'NetRegs_tx_ring_len' := e ]}" :=
  match r with Build_NetRegs (_ as f0) _ (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) =>
    Build_NetRegs f0 e f2 f3 f4 f5 f6 f7 f8 f9 f10 end (at level 0).
Notation "{[ r 'with' 'NetRegs_tx_head' := e ]}" :=
  match r with Build_NetRegs (_ as f0) (_ as f1) _ (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) =>
    Build_NetRegs f0 f1 e f3 f4 f5 f6 f7 f8 f9 f10 end (at level 0).
Notation "{[ r 'with' 'NetRegs_tx_tail' := e ]}" :=
  match r with Build_NetRegs (_ as f0) (_ as f1) (_ as f2) _ (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) =>
    Build_NetRegs f0 f1 f2 e f4 f5 f6 f7 f8 f9 f10 end (at level 0).
Notation "{[ r 'with' 'NetRegs_rx_ring_base' := e ]}" :=
  match r with Build_NetRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) _ (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) =>
    Build_NetRegs f0 f1 f2 f3 e f5 f6 f7 f8 f9 f10 end (at level 0).
Notation "{[ r 'with' 'NetRegs_rx_ring_len' := e ]}" :=
  match r with Build_NetRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) _ (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) =>
    Build_NetRegs f0 f1 f2 f3 f4 e f6 f7 f8 f9 f10 end (at level 0).
Notation "{[ r 'with' 'NetRegs_rx_head' := e ]}" :=
  match r with Build_NetRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) _ (_ as f7) (_ as f8) (_ as f9) (_ as f10) =>
    Build_NetRegs f0 f1 f2 f3 f4 f5 e f7 f8 f9 f10 end (at level 0).
Notation "{[ r 'with' 'NetRegs_rx_tail' := e ]}" :=
  match r with Build_NetRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) _ (_ as f8) (_ as f9) (_ as f10) =>
    Build_NetRegs f0 f1 f2 f3 f4 f5 f6 e f8 f9 f10 end (at level 0).
Notation "{[ r 'with' 'NetRegs_ctrl' := e ]}" :=
  match r with Build_NetRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) _ (_ as f9) (_ as f10) =>
    Build_NetRegs f0 f1 f2 f3 f4 f5 f6 f7 e f9 f10 end (at level 0).
Notation "{[ r 'with' 'NetRegs_status' := e ]}" :=
  match r with Build_NetRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) _ (_ as f10) =>
    Build_NetRegs f0 f1 f2 f3 f4 f5 f6 f7 f8 e f10 end (at level 0).
Notation "{[ r 'with' 'NetRegs_irq_status' := e ]}" :=
  match r with Build_NetRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) _ =>
    Build_NetRegs f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 e end (at level 0).
#[export]
Instance dummy_NetRegs : Inhabited (NetRegs) := {
  inhabitant := {|
    NetRegs_tx_ring_base := inhabitant;
    NetRegs_tx_ring_len := inhabitant;
    NetRegs_tx_head := inhabitant;
    NetRegs_tx_tail := inhabitant;
    NetRegs_rx_ring_base := inhabitant;
    NetRegs_rx_ring_len := inhabitant;
    NetRegs_rx_head := inhabitant;
    NetRegs_rx_tail := inhabitant;
    NetRegs_ctrl := inhabitant;
    NetRegs_status := inhabitant;
    NetRegs_irq_status := inhabitant
|} }.







Variant register : Type :=

.

Definition type_of_register (r : register) : Type :=
  match r with

  end.

Instance Decidable_eq_register : EqDecision register := fun r _ => match r with end.

Instance Countable_register : Countable register := {|
  encode _ := 1%positive;
  decode _ := None;
  decode_encode (r : register) := match r with end
|}.

Definition register_transport {P : Type -> Type} {r r' : register} :
  r = r' -> P (type_of_register r) -> P (type_of_register r') :=
  match r, r' with
  end.

Lemma register_transport_sound {P} {r : register} (e : r = r) (p : P (type_of_register r)) : register_transport e p = p.
Proof.
  destruct r.
Qed.


Definition register_beq (r r' : register) : bool :=
  match r, r' with

  | _, _ => false
  end.

Lemma register_beq_refl (r : register) : register_beq r r = true.
destruct r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Definition register_eq_cast (P : Type -> Type) (r r' : register) : P (type_of_register r) -> option (P (type_of_register r')) :=
  match r, r' with

  | _, _ => fun _ => None
  end.

Definition register_list : list (string * register) := List.concat [

].

Definition string_of_register (r : register) : string :=
  match List.find (fun '(_s, r') => register_beq r r') register_list with
  | Some (s, _r) => s
  | None => "<impossible>"
  end.

Instance Pretty_register : Pretty register :=
  fun reg => string_of_register reg.

Definition register_of_string (s : string) : option register :=
  match List.find (fun '(s', _r) => String.eqb s s') register_list with
  | Some (_s, r) => Some r
  | None => None
  end.

Lemma string_of_register_roundtrip (r : register) :
  register_of_string (string_of_register r) = Some r.
case r; intro r'; destruct r'; reflexivity.
Qed.

#[export] Instance string_of_register_inj : Inj (=) (=) string_of_register.
Proof.
  intros r r' H.
  specialize (string_of_register_roundtrip r) as H1.
  specialize (string_of_register_roundtrip r') as H2.
  rewrite H in H1.
  rewrite H2 in H1.
  congruence.
Qed.
#[export] Hint Extern 1 (register _) => assumption : typeclass_instances.
#[export] Instance Decidable_eq_register_values `(r : register) : EqDecision (type_of_register r) | 100 :=
match r with

end.
#[export] Instance Inhabited_register_values `(r : register) : Inhabited (type_of_register r) | 100 :=
  match r with

end.
#[export] Instance Countable_register_values `(r : register) : Countable (type_of_register r) | 100.
refine {|
  encode := match r with

  end;
  decode := match r with

  end;
|}.
abstract (destruct r; apply decode_encode).
Defined.



(* Definitions to support the lifting to the sequential monad *)
Record regstate := {

}.


Definition init_regstate : regstate := Build_regstate

.

Definition register_lookup (reg : register) (rs : regstate) : type_of_register reg :=
  match reg with

  end.

Definition register_set (reg : register) : type_of_register reg -> regstate -> regstate :=
  match reg with

  end.

Lemma register_lookup_set (r : register) regs v: register_lookup r (register_set r v regs) = v.
destruct regs, r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Lemma irrelevant_register_set (r r' : register) regs v:
  register_beq r r' = false ->
  register_lookup r (register_set r' v regs) = register_lookup r regs.
destruct regs, r, r'; simpl; intro EQ; rewrite ?EQ; reflexivity.
Qed.

Arguments register_set : simpl never.
Arguments register_lookup : simpl never.

Definition register_accessors : register_accessors regstate register type_of_register := (@register_lookup, @register_set).


(* Instantiate library definitions with types. *)

Definition read_reg {E} := @read_reg register type_of_register E.
Definition write_reg {E} := @write_reg register type_of_register E.
Definition MR r a := @monadR register type_of_register a r unit.
Definition M a := @monad register type_of_register a unit.
Definition returnM {A:Type} := @returnm register type_of_register A unit.
Definition returnR {A:Type} (R:Type) := @returnm register type_of_register A (R + unit).
Definition register_ref := @register_ref register type_of_register.