(*Generated by Sail from riscv_inverted_pt.*)
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.
Require Import riscv_inverted_pt_types.
Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.


Definition neq_int (x : Z) (y : Z) : bool := negb ((Z.eqb (x) (y))).

Definition neq_bool (x : bool) (y : bool) : bool := negb ((Bool.eqb (x) (y))).

Definition __id (x : Z) : Z := x.

Definition _shl_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shl_int (m) (n) else shr_int (m) ((Z.opp (n))).

Definition _shr_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shr_int (m) (n) else shl_int (m) ((Z.opp (n))).

Definition fdiv_int (n : Z) (m : Z) : Z :=
   if andb ((Z.ltb (n) (0))) ((Z.gtb (m) (0))) then Z.sub ((Z.quot ((Z.add (n) (1))) (m))) (1)
   else if andb ((Z.gtb (n) (0))) ((Z.ltb (m) (0))) then Z.sub ((Z.quot ((Z.sub (n) (1))) (m))) (1)
   else Z.quot (n) (m).

Definition fmod_int (n : Z) (m : Z) : Z := Z.sub (n) ((Z.mul (m) ((fdiv_int (n) (m))))).

Definition sail_mask {v0 : Z} (len : Z) (v : mword v0) (*(len >=? 0) && (v0 >=? 0)*) : mword len :=
   if Z.leb (len) v0 then vector_truncate (v) (len) else zero_extend (v) (len).

Definition sail_ones (n : Z) (*n >=? 0*) : mword n := not_vec ((zeros (n))).

Definition slice_mask (n : Z) (i : Z) (l : Z) (*n >=? 0*) : mword n :=
   if Z.geb (l) (n) then shiftl ((sail_ones (n))) (i)
   else
     let one : bits n := sail_mask (n) ((('b"1")  : bits 1)) in
     shiftl ((sub_vec ((shiftl (one) (l))) (one))) (i).

Definition to_bytes_le (n : Z) (b : mword (8 * n)) (*n >? 0*) : vec (mword 8) n :=
   let res := vector_init (n) ((zeros (8))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       vec_update_dec (res) (i)
         ((autocast (T := mword)
           (subrange_vec_dec (b) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))))))).

Definition from_bytes_le (n : Z) (v : vec (mword 8) n) (*n >? 0*) : mword (8 * n) :=
   let res := zeros ((Z.mul (8) (n))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       update_subrange_vec_dec (res) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))
         ((autocast (T := mword)
           (vec_access_dec (v) (i)))))).

Definition is_none {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => false | None => true end.

Definition is_some {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => true | None => false end.

Definition concat_str_bits {n : Z} (str : string) (x : mword n) : string :=
   String.append (str) ((string_of_bits (x))).

Definition concat_str_dec (str : string) (x : Z) : string := String.append (str) ((dec_str (x))).

Definition sz_to_int (sz : mword 6) : Z :=
   let p0_ := sz in
   if eq_vec (p0_) (('b"000000")) then 0
   else if eq_vec (p0_) (('b"000001")) then 1
   else if eq_vec (p0_) (('b"000010")) then 2
   else if eq_vec (p0_) (('b"000011")) then 3
   else if eq_vec (p0_) (('b"000100")) then 4
   else if eq_vec (p0_) (('b"000101")) then 5
   else if eq_vec (p0_) (('b"000110")) then 6
   else if eq_vec (p0_) (('b"000111")) then 7
   else if eq_vec (p0_) (('b"001000")) then 8
   else if eq_vec (p0_) (('b"001001")) then 9
   else if eq_vec (p0_) (('b"001010")) then 10
   else if eq_vec (p0_) (('b"001011")) then 11
   else if eq_vec (p0_) (('b"001100")) then 12
   else if eq_vec (p0_) (('b"001101")) then 13
   else if eq_vec (p0_) (('b"001110")) then 14
   else if eq_vec (p0_) (('b"001111")) then 15
   else if eq_vec (p0_) (('b"010000")) then 16
   else if eq_vec (p0_) (('b"010001")) then 17
   else if eq_vec (p0_) (('b"010010")) then 18
   else if eq_vec (p0_) (('b"010011")) then 19
   else if eq_vec (p0_) (('b"010100")) then 20
   else if eq_vec (p0_) (('b"010101")) then 21
   else if eq_vec (p0_) (('b"010110")) then 22
   else if eq_vec (p0_) (('b"010111")) then 23
   else if eq_vec (p0_) (('b"011000")) then 24
   else if eq_vec (p0_) (('b"011001")) then 25
   else if eq_vec (p0_) (('b"011010")) then 26
   else if eq_vec (p0_) (('b"011011")) then 27
   else if eq_vec (p0_) (('b"011100")) then 28
   else if eq_vec (p0_) (('b"011101")) then 29
   else if eq_vec (p0_) (('b"011110")) then 30
   else if eq_vec (p0_) (('b"011111")) then 31
   else if eq_vec (p0_) (('b"100000")) then 32
   else if eq_vec (p0_) (('b"100001")) then 33
   else if eq_vec (p0_) (('b"100010")) then 34
   else if eq_vec (p0_) (('b"100011")) then 35
   else if eq_vec (p0_) (('b"100100")) then 36
   else if eq_vec (p0_) (('b"100101")) then 37
   else if eq_vec (p0_) (('b"100110")) then 38
   else if eq_vec (p0_) (('b"100111")) then 39
   else if eq_vec (p0_) (('b"101000")) then 40
   else if eq_vec (p0_) (('b"101001")) then 41
   else if eq_vec (p0_) (('b"101010")) then 42
   else if eq_vec (p0_) (('b"101011")) then 43
   else if eq_vec (p0_) (('b"101100")) then 44
   else if eq_vec (p0_) (('b"101101")) then 45
   else if eq_vec (p0_) (('b"101110")) then 46
   else if eq_vec (p0_) (('b"101111")) then 47
   else if eq_vec (p0_) (('b"110000")) then 48
   else if eq_vec (p0_) (('b"110001")) then 49
   else if eq_vec (p0_) (('b"110010")) then 50
   else if eq_vec (p0_) (('b"110011")) then 51
   else if eq_vec (p0_) (('b"110100")) then 52
   else if eq_vec (p0_) (('b"110101")) then 53
   else if eq_vec (p0_) (('b"110110")) then 54
   else if eq_vec (p0_) (('b"110111")) then 55
   else 55.

Definition sp_vpn_of (va : mword 64) (sz : mword 6) : mword 56 :=
   let shifted : bits 64 := shiftr ((zero_extend (va) (64))) ((sz_to_int (sz))) in
   subrange_vec_dec (shifted) (55) (0).

Definition page_offset_of (va : mword 64) (sz : mword 6) : mword 56 :=
   let all_ones : bits 56 := (Ox"FFFFFFFFFFFFFF") in
   let mask : bits 56 := shiftr (all_ones) ((Z.sub (56) ((sz_to_int (sz))))) in
   and_vec ((subrange_vec_dec (va) (55) (0))) (mask).

Definition mk_phys (ppn : mword 52) (va : mword 64) (sz : mword 6) : mword 56 :=
   let ppn56 : bits 56 := zero_extend (ppn) (56) in
   or_vec ((shiftl (ppn56) ((sz_to_int (sz))))) ((page_offset_of (va) (sz))).

Definition partition_of (sz : mword 6) : mword 2 := subrange_vec_dec (sz) (1) (0).

Definition phipt_hash (sp : mword 56) (part : mword 2) : mword 26 :=
   let lo : bits 26 := subrange_vec_dec (sp) (25) (0) in
   let mid : bits 26 := subrange_vec_dec (sp) (51) (26) in
   let hi : bits 26 :=
     concat_vec ((concat_vec (('b"00000000000000000000")) (part)))
       ((subrange_vec_dec (sp) (55) (52))) in
   add_vec ((add_vec (lo) (mid))) (hi).

Definition undefined_SlbEntry '(tt : unit) : M (SlbEntry) :=
   (undefined_bool (tt)) >>= fun (w__0 : bool) =>
   (undefined_bitvector (36)) >>= fun (w__1 : mword 36) =>
   (undefined_bitvector (20)) >>= fun (w__2 : mword 20) =>
   (undefined_bitvector (4)) >>= fun (w__3 : mword 4) =>
   (undefined_bitvector (4)) >>= fun (w__4 : mword 4) =>
   (undefined_bool (tt)) >>= fun (w__5 : bool) =>
   (undefined_bitvector (16)) >>= fun (w__6 : mword 16) =>
   returnM (({| SlbEntry_valid := w__0;
                SlbEntry_vsid := w__1;
                SlbEntry_ppn := w__2;
                SlbEntry_size := w__3;
                SlbEntry_perms := w__4;
                SlbEntry_global := w__5;
                SlbEntry_asid := w__6 |})).

Fixpoint slb_lookup (slb : list SlbEntry) (va : mword 64) (asid : mword 16) : option SlbEntry :=
   match slb with
   | [] => None
   | e :: rest =>
      if andb (e.(SlbEntry_valid))
           ((andb ((eq_vec (e.(SlbEntry_vsid)) ((subrange_vec_dec (va) (63) (28)))))
               ((orb (e.(SlbEntry_global)) ((eq_vec (e.(SlbEntry_asid)) (asid))))))) then
        Some (e)
      else slb_lookup (rest) (va) (asid)
   end.

Definition undefined_PhiPtEntry '(tt : unit) : M (PhiPtEntry) :=
   (undefined_bool (tt)) >>= fun (w__0 : bool) =>
   (undefined_bitvector (56)) >>= fun (w__1 : mword 56) =>
   (undefined_bitvector (52)) >>= fun (w__2 : mword 52) =>
   (undefined_bitvector (6)) >>= fun (w__3 : mword 6) =>
   (undefined_bitvector (4)) >>= fun (w__4 : mword 4) =>
   (undefined_bool (tt)) >>= fun (w__5 : bool) =>
   (undefined_bitvector (16)) >>= fun (w__6 : mword 16) =>
   returnM (({| PhiPtEntry_valid := w__0;
                PhiPtEntry_sp_vpn := w__1;
                PhiPtEntry_ppn := w__2;
                PhiPtEntry_size := w__3;
                PhiPtEntry_perms := w__4;
                PhiPtEntry_global := w__5;
                PhiPtEntry_asid := w__6 |})).

Fixpoint phipt_probe
(entries : list PhiPtEntry) (sp : mword 56) (sz : mword 6) (asid : mword 16) (depth : Z)
: option PhiPtEntry :=
   match entries with
   | [] => None
   | e :: rest =>
      if Z.geb (depth) (64) then None
      else if andb (e.(PhiPtEntry_valid))
                ((andb ((eq_vec (e.(PhiPtEntry_sp_vpn)) (sp)))
                    ((andb ((eq_vec (e.(PhiPtEntry_size)) (sz)))
                        ((orb (e.(PhiPtEntry_global)) ((eq_vec (e.(PhiPtEntry_asid)) (asid)))))))))
      then
        Some (e)
      else phipt_probe (rest) (sp) (sz) (asid) ((Z.add (depth) (1)))
   end.

Definition phipt_lookup (pt : PhiPt) (va : mword 64) (sz : mword 6) (asid : mword 16)
: option PhiPtEntry :=
   let sp : sp_vpn_typ := sp_vpn_of (va) (sz) in
   phipt_probe (pt.(PhiPt_entries)) (sp) (sz) (asid) (0).

Definition phipt_insert (pt : PhiPt) (entry : PhiPtEntry) : PhiPt :=
   {| PhiPt_entries := entry :: pt.(PhiPt_entries);  PhiPt_log_size := pt.(PhiPt_log_size) |}.

Fixpoint phipt_filter (entries : list PhiPtEntry) (va : mword 64) (asid : mword 16)
: list PhiPtEntry :=
   match entries with
   | [] => []
   | e :: rest =>
      if andb (e.(PhiPtEntry_valid))
           ((andb ((eq_vec ((sp_vpn_of (va) (e.(PhiPtEntry_size)))) (e.(PhiPtEntry_sp_vpn))))
               ((orb (e.(PhiPtEntry_global)) ((eq_vec (e.(PhiPtEntry_asid)) (asid))))))) then
        phipt_filter (rest) (va) (asid)
      else e :: (phipt_filter (rest) (va) (asid))
   end.

Definition phipt_invalidate (pt : PhiPt) (va : mword 64) (asid : mword 16) : PhiPt :=
   {| PhiPt_entries := phipt_filter (pt.(PhiPt_entries)) (va) (asid);
      PhiPt_log_size := pt.(PhiPt_log_size) |}.

Definition all_sizes (_ : unit) : list (mword 6) :=
   ('b"110111") ::
     (('b"110110") ::
       (('b"110101") ::
         (('b"110100") ::
           (('b"110011") ::
             (('b"110010") ::
               (('b"110001") ::
                 (('b"110000") ::
                   (('b"101111") ::
                     (('b"101110") ::
                       (('b"101101") ::
                         (('b"101100") ::
                           (('b"101011") ::
                             (('b"101010") ::
                               (('b"101001") ::
                                 (('b"101000") ::
                                   (('b"100111") ::
                                     (('b"100110") ::
                                       (('b"100101") ::
                                         (('b"100100") ::
                                           (('b"100011") ::
                                             (('b"100010") ::
                                               (('b"100001") ::
                                                 (('b"100000") ::
                                                   (('b"011111") ::
                                                     (('b"011110") ::
                                                       (('b"011101") ::
                                                         (('b"011100") ::
                                                           (('b"011011") ::
                                                             (('b"011010") ::
                                                               (('b"011001") ::
                                                                 (('b"011000") ::
                                                                   (('b"010111") ::
                                                                     (('b"010110") ::
                                                                       (('b"010101") ::
                                                                         (('b"010100") ::
                                                                           (('b"010011") ::
                                                                             (('b"010010") ::
                                                                               (('b"010001") ::
                                                                                 (('b"010000") ::
                                                                                   (('b"001111") ::
                                                                                     (('b"001110") ::
                                                                                       (('b"001101") ::
                                                                                         (('b"001100") ::
                                                                                           (('b"001011") ::
                                                                                             (('b"001010") ::
                                                                                               (('b"001001") ::
                                                                                                 (('b"001000") ::
                                                                                                   (('b"000111") ::
                                                                                                     (('b"000110") ::
                                                                                                       (('b"000101") ::
                                                                                                         (('b"000100") ::
                                                                                                           (('b"000011") ::
                                                                                                             (('b"000010") ::
                                                                                                               (('b"000001") ::
                                                                                                                 (('b"000000") ::
                                                                                                                   []))))))))))))))))))))))))))))))))))))))))))))))))))))))).

Fixpoint phipt_search_list (pt : PhiPt) (va : mword 64) (asid : mword 16) (sizes : list (mword 6))
: option PhiPtEntry :=
   match sizes with
   | [] => None
   | sz :: rest =>
      match phipt_lookup (pt) (va) (sz) (asid) with
      | Some e => Some (e)
      | None => phipt_search_list (pt) (va) (asid) (rest)
      end
   end.

Definition undefined_PhiTlbEntry '(tt : unit) : M (PhiTlbEntry) :=
   (undefined_bool (tt)) >>= fun (w__0 : bool) =>
   (undefined_bitvector (56)) >>= fun (w__1 : mword 56) =>
   (undefined_bitvector (52)) >>= fun (w__2 : mword 52) =>
   (undefined_bitvector (6)) >>= fun (w__3 : mword 6) =>
   (undefined_bitvector (4)) >>= fun (w__4 : mword 4) =>
   (undefined_bitvector (16)) >>= fun (w__5 : mword 16) =>
   (undefined_bitvector (2)) >>= fun (w__6 : mword 2) =>
   returnM (({| PhiTlbEntry_valid := w__0;
                PhiTlbEntry_sp_vpn := w__1;
                PhiTlbEntry_ppn := w__2;
                PhiTlbEntry_size := w__3;
                PhiTlbEntry_perms := w__4;
                PhiTlbEntry_asid := w__5;
                PhiTlbEntry_partition := w__6 |})).

Definition phi_covers (e : PhiTlbEntry) (va : mword 64) : bool :=
   eq_vec ((sp_vpn_of (va) (e.(PhiTlbEntry_size)))) (e.(PhiTlbEntry_sp_vpn)).

Fixpoint phi_tlb_find_best
(tlb : list PhiTlbEntry) (va : mword 64) (asid : mword 16) (best : option PhiTlbEntry)
: option PhiTlbEntry :=
   match tlb with
   | [] => best
   | e :: rest =>
      if andb (e.(PhiTlbEntry_valid))
           ((andb ((phi_covers (e) (va))) ((eq_vec (e.(PhiTlbEntry_asid)) (asid))))) then
        let best' : option PhiTlbEntry :=
          match best with
          | None => Some (e)
          | Some b =>
             if Z.gtb ((sz_to_int (e.(PhiTlbEntry_size)))) ((sz_to_int (b.(PhiTlbEntry_size)))) then
               Some (e)
             else Some (b)
          end in
        phi_tlb_find_best (rest) (va) (asid) (best')
      else phi_tlb_find_best (rest) (va) (asid) (best)
   end.

Definition phi_tlb_lookup (tlb : list PhiTlbEntry) (va : mword 64) (asid : mword 16)
: option PhiTlbEntry :=
   phi_tlb_find_best (tlb) (va) (asid) (None).

Fixpoint phi_tlb_flush (tlb : list PhiTlbEntry) (va : mword 64) (asid : mword 16) : list PhiTlbEntry :=
   match tlb with
   | [] => []
   | e :: rest =>
      if andb (e.(PhiTlbEntry_valid))
           ((andb ((phi_covers (e) (va))) ((eq_vec (e.(PhiTlbEntry_asid)) (asid))))) then
        phi_tlb_flush (rest) (va) (asid)
      else e :: (phi_tlb_flush (rest) (va) (asid))
   end.

Definition riscv_inverted_translate
(slb : list SlbEntry) (pt : PhiPt) (tlb : list PhiTlbEntry) (va : mword 64) (asid : mword 16)
: option ((mword 56 * mword 4)) :=
   match phi_tlb_lookup (tlb) (va) (asid) with
   | Some e =>
      Some ((mk_phys (e.(PhiTlbEntry_ppn)) (va) (e.(PhiTlbEntry_size)), e.(PhiTlbEntry_perms)))
   | None =>
      match slb_lookup (slb) (va) (asid) with
      | Some _seg =>
         match phipt_search_list (pt) (va) (asid) ((all_sizes (tt))) with
         | Some e =>
            Some ((mk_phys (e.(PhiPtEntry_ppn)) (va) (e.(PhiPtEntry_size)), e.(PhiPtEntry_perms)))
         | None => None
         end
      | None =>
         match phipt_search_list (pt) (va) (asid) ((all_sizes (tt))) with
         | Some e =>
            Some ((mk_phys (e.(PhiPtEntry_ppn)) (va) (e.(PhiPtEntry_size)), e.(PhiPtEntry_perms)))
         | None => None
         end
      end
   end.

Definition initialize_registers '(tt : unit) : unit := tt.

Definition sail_model_init (_ : unit) : unit := initialize_registers (tt).



