(*Generated by Sail from riscv_inverted_pt.*)


From stdpp Require Import base countable pretty.
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.

Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.

Definition bit : Type := mword 1.

Definition bits (n : Z) : Type := mword n.

Definition vaddr : Type := bits 64.

Definition paddr : Type := bits 56.

Definition size_log2 : Type := bits 6.

Definition partition_typ : Type := bits 2.

Definition sp_vpn_typ : Type := bits 56.

Record SlbEntry := {
  SlbEntry_valid : bool;
  SlbEntry_vsid : bits 36;
  SlbEntry_ppn : bits 20;
  SlbEntry_size : bits 4;
  SlbEntry_perms : bits 4;
  SlbEntry_global : bool;
  SlbEntry_asid : bits 16;
}.
Arguments SlbEntry : clear implicits.
#[export]
Instance Decidable_eq_SlbEntry : EqDecision SlbEntry.
   intros [x0 x1 x2 x3 x4 x5 x6].
   intros [y0 y1 y2 y3 y4 y5 y6].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
  cmp_record_field x2 y2.
  cmp_record_field x3 y3.
  cmp_record_field x4 y4.
  cmp_record_field x5 y5.
  cmp_record_field x6 y6.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_SlbEntry : Countable SlbEntry.
refine {|
  encode x := encode (SlbEntry_valid x, SlbEntry_vsid x, SlbEntry_ppn x, SlbEntry_size x, SlbEntry_perms x, SlbEntry_global x, SlbEntry_asid x);
  decode x := '(x0, x1, x2, x3, x4, x5, x6) ← decode x;
              mret (Build_SlbEntry x0 x1 x2 x3 x4 x5 x6)
|}.
abstract (
  intros [x0 x1 x2 x3 x4 x5 x6];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'SlbEntry_valid' := e ]}" :=
  match r with Build_SlbEntry _ (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_SlbEntry e f1 f2 f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'SlbEntry_vsid' := e ]}" :=
  match r with Build_SlbEntry (_ as f0) _ (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_SlbEntry f0 e f2 f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'SlbEntry_ppn' := e ]}" :=
  match r with Build_SlbEntry (_ as f0) (_ as f1) _ (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_SlbEntry f0 f1 e f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'SlbEntry_size' := e ]}" :=
  match r with Build_SlbEntry (_ as f0) (_ as f1) (_ as f2) _ (_ as f4) (_ as f5) (_ as f6) =>
    Build_SlbEntry f0 f1 f2 e f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'SlbEntry_perms' := e ]}" :=
  match r with Build_SlbEntry (_ as f0) (_ as f1) (_ as f2) (_ as f3) _ (_ as f5) (_ as f6) =>
    Build_SlbEntry f0 f1 f2 f3 e f5 f6 end (at level 0).
Notation "{[ r 'with' 'SlbEntry_global' := e ]}" :=
  match r with Build_SlbEntry (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) _ (_ as f6) =>
    Build_SlbEntry f0 f1 f2 f3 f4 e f6 end (at level 0).
Notation "{[ r 'with' 'SlbEntry_asid' := e ]}" :=
  match r with Build_SlbEntry (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) _ =>
    Build_SlbEntry f0 f1 f2 f3 f4 f5 e end (at level 0).
#[export]
Instance dummy_SlbEntry : Inhabited (SlbEntry) := {
  inhabitant := {|
    SlbEntry_valid := inhabitant;
    SlbEntry_vsid := inhabitant;
    SlbEntry_ppn := inhabitant;
    SlbEntry_size := inhabitant;
    SlbEntry_perms := inhabitant;
    SlbEntry_global := inhabitant;
    SlbEntry_asid := inhabitant
|} }.


Definition Slb : Type := list SlbEntry.

Record PhiPtEntry := {
  PhiPtEntry_valid : bool;
  PhiPtEntry_sp_vpn : sp_vpn_typ;
  PhiPtEntry_ppn : bits 52;
  PhiPtEntry_size : size_log2;
  PhiPtEntry_perms : bits 4;
  PhiPtEntry_global : bool;
  PhiPtEntry_asid : bits 16;
}.
Arguments PhiPtEntry : clear implicits.
#[export]
Instance Decidable_eq_PhiPtEntry : EqDecision PhiPtEntry.
   intros [x0 x1 x2 x3 x4 x5 x6].
   intros [y0 y1 y2 y3 y4 y5 y6].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
  cmp_record_field x2 y2.
  cmp_record_field x3 y3.
  cmp_record_field x4 y4.
  cmp_record_field x5 y5.
  cmp_record_field x6 y6.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_PhiPtEntry : Countable PhiPtEntry.
refine {|
  encode x := encode (PhiPtEntry_valid x, PhiPtEntry_sp_vpn x, PhiPtEntry_ppn x, PhiPtEntry_size x, PhiPtEntry_perms x, PhiPtEntry_global x, PhiPtEntry_asid x);
  decode x := '(x0, x1, x2, x3, x4, x5, x6) ← decode x;
              mret (Build_PhiPtEntry x0 x1 x2 x3 x4 x5 x6)
|}.
abstract (
  intros [x0 x1 x2 x3 x4 x5 x6];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'PhiPtEntry_valid' := e ]}" :=
  match r with Build_PhiPtEntry _ (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_PhiPtEntry e f1 f2 f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'PhiPtEntry_sp_vpn' := e ]}" :=
  match r with Build_PhiPtEntry (_ as f0) _ (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_PhiPtEntry f0 e f2 f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'PhiPtEntry_ppn' := e ]}" :=
  match r with Build_PhiPtEntry (_ as f0) (_ as f1) _ (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_PhiPtEntry f0 f1 e f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'PhiPtEntry_size' := e ]}" :=
  match r with Build_PhiPtEntry (_ as f0) (_ as f1) (_ as f2) _ (_ as f4) (_ as f5) (_ as f6) =>
    Build_PhiPtEntry f0 f1 f2 e f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'PhiPtEntry_perms' := e ]}" :=
  match r with Build_PhiPtEntry (_ as f0) (_ as f1) (_ as f2) (_ as f3) _ (_ as f5) (_ as f6) =>
    Build_PhiPtEntry f0 f1 f2 f3 e f5 f6 end (at level 0).
Notation "{[ r 'with' 'PhiPtEntry_global' := e ]}" :=
  match r with Build_PhiPtEntry (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) _ (_ as f6) =>
    Build_PhiPtEntry f0 f1 f2 f3 f4 e f6 end (at level 0).
Notation "{[ r 'with' 'PhiPtEntry_asid' := e ]}" :=
  match r with Build_PhiPtEntry (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) _ =>
    Build_PhiPtEntry f0 f1 f2 f3 f4 f5 e end (at level 0).
#[export]
Instance dummy_PhiPtEntry : Inhabited (PhiPtEntry) := {
  inhabitant := {|
    PhiPtEntry_valid := inhabitant;
    PhiPtEntry_sp_vpn := inhabitant;
    PhiPtEntry_ppn := inhabitant;
    PhiPtEntry_size := inhabitant;
    PhiPtEntry_perms := inhabitant;
    PhiPtEntry_global := inhabitant;
    PhiPtEntry_asid := inhabitant
|} }.


Record PhiPt := {
  PhiPt_entries : list PhiPtEntry;
  PhiPt_log_size : bits 26;
}.
Arguments PhiPt : clear implicits.
#[export]
Instance Decidable_eq_PhiPt : EqDecision PhiPt.
   intros [x0 x1].
   intros [y0 y1].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_PhiPt : Countable PhiPt.
refine {|
  encode x := encode (PhiPt_entries x, PhiPt_log_size x);
  decode x := '(x0, x1) ← decode x;
              mret (Build_PhiPt x0 x1)
|}.
abstract (
  intros [x0 x1];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'PhiPt_entries' := e ]}" :=
  match r with Build_PhiPt _ (_ as f1) => Build_PhiPt e f1 end (at level 0).
Notation "{[ r 'with' 'PhiPt_log_size' := e ]}" :=
  match r with Build_PhiPt (_ as f0) _ => Build_PhiPt f0 e end (at level 0).
#[export]
Instance dummy_PhiPt : Inhabited (PhiPt) := {
  inhabitant := {| PhiPt_entries := inhabitant; PhiPt_log_size := inhabitant
|} }.


Record PhiTlbEntry := {
  PhiTlbEntry_valid : bool;
  PhiTlbEntry_sp_vpn : sp_vpn_typ;
  PhiTlbEntry_ppn : bits 52;
  PhiTlbEntry_size : size_log2;
  PhiTlbEntry_perms : bits 4;
  PhiTlbEntry_asid : bits 16;
  PhiTlbEntry_partition : partition_typ;
}.
Arguments PhiTlbEntry : clear implicits.
#[export]
Instance Decidable_eq_PhiTlbEntry : EqDecision PhiTlbEntry.
   intros [x0 x1 x2 x3 x4 x5 x6].
   intros [y0 y1 y2 y3 y4 y5 y6].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
  cmp_record_field x2 y2.
  cmp_record_field x3 y3.
  cmp_record_field x4 y4.
  cmp_record_field x5 y5.
  cmp_record_field x6 y6.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_PhiTlbEntry : Countable PhiTlbEntry.
refine {|
  encode x := encode (PhiTlbEntry_valid x, PhiTlbEntry_sp_vpn x, PhiTlbEntry_ppn x, PhiTlbEntry_size x, PhiTlbEntry_perms x, PhiTlbEntry_asid x, PhiTlbEntry_partition x);
  decode x := '(x0, x1, x2, x3, x4, x5, x6) ← decode x;
              mret (Build_PhiTlbEntry x0 x1 x2 x3 x4 x5 x6)
|}.
abstract (
  intros [x0 x1 x2 x3 x4 x5 x6];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'PhiTlbEntry_valid' := e ]}" :=
  match r with Build_PhiTlbEntry _ (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_PhiTlbEntry e f1 f2 f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'PhiTlbEntry_sp_vpn' := e ]}" :=
  match r with Build_PhiTlbEntry (_ as f0) _ (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_PhiTlbEntry f0 e f2 f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'PhiTlbEntry_ppn' := e ]}" :=
  match r with Build_PhiTlbEntry (_ as f0) (_ as f1) _ (_ as f3) (_ as f4) (_ as f5) (_ as f6) =>
    Build_PhiTlbEntry f0 f1 e f3 f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'PhiTlbEntry_size' := e ]}" :=
  match r with Build_PhiTlbEntry (_ as f0) (_ as f1) (_ as f2) _ (_ as f4) (_ as f5) (_ as f6) =>
    Build_PhiTlbEntry f0 f1 f2 e f4 f5 f6 end (at level 0).
Notation "{[ r 'with' 'PhiTlbEntry_perms' := e ]}" :=
  match r with Build_PhiTlbEntry (_ as f0) (_ as f1) (_ as f2) (_ as f3) _ (_ as f5) (_ as f6) =>
    Build_PhiTlbEntry f0 f1 f2 f3 e f5 f6 end (at level 0).
Notation "{[ r 'with' 'PhiTlbEntry_asid' := e ]}" :=
  match r with Build_PhiTlbEntry (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) _ (_ as f6) =>
    Build_PhiTlbEntry f0 f1 f2 f3 f4 e f6 end (at level 0).
Notation "{[ r 'with' 'PhiTlbEntry_partition' := e ]}" :=
  match r with Build_PhiTlbEntry (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) _ =>
    Build_PhiTlbEntry f0 f1 f2 f3 f4 f5 e end (at level 0).
#[export]
Instance dummy_PhiTlbEntry : Inhabited (PhiTlbEntry) := {
  inhabitant := {|
    PhiTlbEntry_valid := inhabitant;
    PhiTlbEntry_sp_vpn := inhabitant;
    PhiTlbEntry_ppn := inhabitant;
    PhiTlbEntry_size := inhabitant;
    PhiTlbEntry_perms := inhabitant;
    PhiTlbEntry_asid := inhabitant;
    PhiTlbEntry_partition := inhabitant
|} }.


Definition PhiTlb : Type := list PhiTlbEntry.






Variant register : Type :=

.

Definition type_of_register (r : register) : Type :=
  match r with

  end.

Instance Decidable_eq_register : EqDecision register := fun r _ => match r with end.

Instance Countable_register : Countable register := {|
  encode _ := 1%positive;
  decode _ := None;
  decode_encode (r : register) := match r with end
|}.

Definition register_transport {P : Type -> Type} {r r' : register} :
  r = r' -> P (type_of_register r) -> P (type_of_register r') :=
  match r, r' with
  end.

Lemma register_transport_sound {P} {r : register} (e : r = r) (p : P (type_of_register r)) : register_transport e p = p.
Proof.
  destruct r.
Qed.


Definition register_beq (r r' : register) : bool :=
  match r, r' with

  | _, _ => false
  end.

Lemma register_beq_refl (r : register) : register_beq r r = true.
destruct r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Definition register_eq_cast (P : Type -> Type) (r r' : register) : P (type_of_register r) -> option (P (type_of_register r')) :=
  match r, r' with

  | _, _ => fun _ => None
  end.

Definition register_list : list (string * register) := List.concat [

].

Definition string_of_register (r : register) : string :=
  match List.find (fun '(_s, r') => register_beq r r') register_list with
  | Some (s, _r) => s
  | None => "<impossible>"
  end.

Instance Pretty_register : Pretty register :=
  fun reg => string_of_register reg.

Definition register_of_string (s : string) : option register :=
  match List.find (fun '(s', _r) => String.eqb s s') register_list with
  | Some (_s, r) => Some r
  | None => None
  end.

Lemma string_of_register_roundtrip (r : register) :
  register_of_string (string_of_register r) = Some r.
case r; intro r'; destruct r'; reflexivity.
Qed.

#[export] Instance string_of_register_inj : Inj (=) (=) string_of_register.
Proof.
  intros r r' H.
  specialize (string_of_register_roundtrip r) as H1.
  specialize (string_of_register_roundtrip r') as H2.
  rewrite H in H1.
  rewrite H2 in H1.
  congruence.
Qed.
#[export] Hint Extern 1 (register _) => assumption : typeclass_instances.
#[export] Instance Decidable_eq_register_values `(r : register) : EqDecision (type_of_register r) | 100 :=
match r with

end.
#[export] Instance Inhabited_register_values `(r : register) : Inhabited (type_of_register r) | 100 :=
  match r with

end.
#[export] Instance Countable_register_values `(r : register) : Countable (type_of_register r) | 100.
refine {|
  encode := match r with

  end;
  decode := match r with

  end;
|}.
abstract (destruct r; apply decode_encode).
Defined.



(* Definitions to support the lifting to the sequential monad *)
Record regstate := {

}.


Definition init_regstate : regstate := Build_regstate

.

Definition register_lookup (reg : register) (rs : regstate) : type_of_register reg :=
  match reg with

  end.

Definition register_set (reg : register) : type_of_register reg -> regstate -> regstate :=
  match reg with

  end.

Lemma register_lookup_set (r : register) regs v: register_lookup r (register_set r v regs) = v.
destruct regs, r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Lemma irrelevant_register_set (r r' : register) regs v:
  register_beq r r' = false ->
  register_lookup r (register_set r' v regs) = register_lookup r regs.
destruct regs, r, r'; simpl; intro EQ; rewrite ?EQ; reflexivity.
Qed.

Arguments register_set : simpl never.
Arguments register_lookup : simpl never.

Definition register_accessors : register_accessors regstate register type_of_register := (@register_lookup, @register_set).


(* Instantiate library definitions with types. *)

Definition read_reg {E} := @read_reg register type_of_register E.
Definition write_reg {E} := @write_reg register type_of_register E.
Definition MR r a := @monadR register type_of_register a r unit.
Definition M a := @monad register type_of_register a unit.
Definition returnM {A:Type} := @returnm register type_of_register A unit.
Definition returnR {A:Type} (R:Type) := @returnm register type_of_register A (R + unit).
Definition register_ref := @register_ref register type_of_register.