(*Generated by Sail from sail_arm_tlb.*)


From stdpp Require Import base countable pretty.
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.

Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.

Definition bit : Type := mword 1.

Definition bits (n : Z) : Type := mword n.

Definition vaddr : Type := bits 64.

Definition paddr : Type := bits 56.

Inductive SaTGx := SaTGx_4KB | SaTGx_16KB | SaTGx_64KB.
Definition num_of_SaTGx (arg_ : SaTGx) : Z :=
   match arg_ with | SaTGx_4KB => 0 | SaTGx_16KB => 1 | SaTGx_64KB => 2 end.

Definition SaTGx_of_num (arg_ : Z) (*(0 <=? arg_) && (arg_ <=? 2)*) : SaTGx :=
   let l__0 := arg_ in
   if Z.eqb (l__0) (0) then SaTGx_4KB
   else if Z.eqb (l__0) (1) then SaTGx_16KB
   else SaTGx_64KB.

Lemma SaTGx_num_of_roundtrip (x : SaTGx) : SaTGx_of_num (num_of_SaTGx x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_SaTGx_injective (x y : SaTGx) : num_of_SaTGx x = num_of_SaTGx y -> x = y.
  intro.
  rewrite <- (SaTGx_num_of_roundtrip x).
  rewrite <- (SaTGx_num_of_roundtrip y).
  congruence.
Qed.
Definition SaTGx_eq_dec (x y : SaTGx) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_SaTGx x) (num_of_SaTGx y) with
  | left e => left (num_of_SaTGx_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition SaTGx_beq (x y : SaTGx) : bool :=
  Z.eqb (num_of_SaTGx x) (num_of_SaTGx y).
Lemma SaTGx_beq_iff x y : SaTGx_beq x y = true <-> x = y.
  unfold SaTGx_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_SaTGx_injective | congruence].
Qed.
Lemma SaTGx_beq_refl x : SaTGx_beq x x = true.
apply SaTGx_beq_iff; reflexivity.
Qed.
#[export]
Instance Decidable_eq_SaTGx : EqDecision SaTGx := SaTGx_eq_dec.
#[export]
Instance Countable_SaTGx : Countable SaTGx.
refine {|
  encode x := encode (num_of_SaTGx x);
  decode x := z ← decode x; mret (SaTGx_of_num z);
|}.
abstract (
  intro s; rewrite decode_encode;
  simpl;
  rewrite SaTGx_num_of_roundtrip;
  reflexivity).
Defined.
#[export]
Instance dummy_SaTGx : Inhabited SaTGx := { inhabitant := SaTGx_4KB }.







Variant register : Type :=

.

Definition type_of_register (r : register) : Type :=
  match r with

  end.

Instance Decidable_eq_register : EqDecision register := fun r _ => match r with end.

Instance Countable_register : Countable register := {|
  encode _ := 1%positive;
  decode _ := None;
  decode_encode (r : register) := match r with end
|}.

Definition register_transport {P : Type -> Type} {r r' : register} :
  r = r' -> P (type_of_register r) -> P (type_of_register r') :=
  match r, r' with
  end.

Lemma register_transport_sound {P} {r : register} (e : r = r) (p : P (type_of_register r)) : register_transport e p = p.
Proof.
  destruct r.
Qed.


Definition register_beq (r r' : register) : bool :=
  match r, r' with

  | _, _ => false
  end.

Lemma register_beq_refl (r : register) : register_beq r r = true.
destruct r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Definition register_eq_cast (P : Type -> Type) (r r' : register) : P (type_of_register r) -> option (P (type_of_register r')) :=
  match r, r' with

  | _, _ => fun _ => None
  end.

Definition register_list : list (string * register) := List.concat [

].

Definition string_of_register (r : register) : string :=
  match List.find (fun '(_s, r') => register_beq r r') register_list with
  | Some (s, _r) => s
  | None => "<impossible>"
  end.

Instance Pretty_register : Pretty register :=
  fun reg => string_of_register reg.

Definition register_of_string (s : string) : option register :=
  match List.find (fun '(s', _r) => String.eqb s s') register_list with
  | Some (_s, r) => Some r
  | None => None
  end.

Lemma string_of_register_roundtrip (r : register) :
  register_of_string (string_of_register r) = Some r.
case r; intro r'; destruct r'; reflexivity.
Qed.

#[export] Instance string_of_register_inj : Inj (=) (=) string_of_register.
Proof.
  intros r r' H.
  specialize (string_of_register_roundtrip r) as H1.
  specialize (string_of_register_roundtrip r') as H2.
  rewrite H in H1.
  rewrite H2 in H1.
  congruence.
Qed.
#[export] Hint Extern 1 (register _) => assumption : typeclass_instances.
#[export] Instance Decidable_eq_register_values `(r : register) : EqDecision (type_of_register r) | 100 :=
match r with

end.
#[export] Instance Inhabited_register_values `(r : register) : Inhabited (type_of_register r) | 100 :=
  match r with

end.
#[export] Instance Countable_register_values `(r : register) : Countable (type_of_register r) | 100.
refine {|
  encode := match r with

  end;
  decode := match r with

  end;
|}.
abstract (destruct r; apply decode_encode).
Defined.



(* Definitions to support the lifting to the sequential monad *)
Record regstate := {

}.


Definition init_regstate : regstate := Build_regstate

.

Definition register_lookup (reg : register) (rs : regstate) : type_of_register reg :=
  match reg with

  end.

Definition register_set (reg : register) : type_of_register reg -> regstate -> regstate :=
  match reg with

  end.

Lemma register_lookup_set (r : register) regs v: register_lookup r (register_set r v regs) = v.
destruct regs, r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Lemma irrelevant_register_set (r r' : register) regs v:
  register_beq r r' = false ->
  register_lookup r (register_set r' v regs) = register_lookup r regs.
destruct regs, r, r'; simpl; intro EQ; rewrite ?EQ; reflexivity.
Qed.

Arguments register_set : simpl never.
Arguments register_lookup : simpl never.

Definition register_accessors : register_accessors regstate register type_of_register := (@register_lookup, @register_set).


(* Instantiate library definitions with types. *)

Definition read_reg {E} := @read_reg register type_of_register E.
Definition write_reg {E} := @write_reg register type_of_register E.
Definition MR r a := @monadR register type_of_register a r unit.
Definition M a := @monad register type_of_register a unit.
Definition returnM {A:Type} := @returnm register type_of_register A unit.
Definition returnR {A:Type} (R:Type) := @returnm register type_of_register A (R + unit).
Definition register_ref := @register_ref register type_of_register.