(*Generated by Sail from uart.*)


From stdpp Require Import base countable pretty.
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.

Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.

Definition bit : Type := mword 1.

Definition bits (n : Z) : Type := mword n.

Record UartRegs := {
  UartRegs_thr : bits 8;
  UartRegs_rbr : bits 8;
  UartRegs_ier : bits 4;
  UartRegs_iir : bits 4;
  UartRegs_fcr : bits 4;
  UartRegs_lcr : bits 8;
  UartRegs_mcr : bits 5;
  UartRegs_lsr : bits 8;
  UartRegs_msr : bits 8;
  UartRegs_scr : bits 8;
  UartRegs_dll : bits 8;
  UartRegs_dlh : bits 8;
  UartRegs_tx_ready : bool;
  UartRegs_rx_ready : bool;
}.
Arguments UartRegs : clear implicits.
#[export]
Instance Decidable_eq_UartRegs : EqDecision UartRegs.
   intros [x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13].
   intros [y0 y1 y2 y3 y4 y5 y6 y7 y8 y9 y10 y11 y12 y13].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
  cmp_record_field x2 y2.
  cmp_record_field x3 y3.
  cmp_record_field x4 y4.
  cmp_record_field x5 y5.
  cmp_record_field x6 y6.
  cmp_record_field x7 y7.
  cmp_record_field x8 y8.
  cmp_record_field x9 y9.
  cmp_record_field x10 y10.
  cmp_record_field x11 y11.
  cmp_record_field x12 y12.
  cmp_record_field x13 y13.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_UartRegs : Countable UartRegs.
refine {|
  encode x := encode (UartRegs_thr x, UartRegs_rbr x, UartRegs_ier x, UartRegs_iir x, UartRegs_fcr x, UartRegs_lcr x, UartRegs_mcr x, UartRegs_lsr x, UartRegs_msr x, UartRegs_scr x, UartRegs_dll x, UartRegs_dlh x, UartRegs_tx_ready x, UartRegs_rx_ready x);
  decode x := '(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13) ← decode x;
              mret (Build_UartRegs x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13)
|}.
abstract (
  intros [x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'UartRegs_thr' := e ]}" :=
  match r with Build_UartRegs _ (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) (_ as f11) (_ as f12) (_ as f13) =>
    Build_UartRegs e f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 end (at level 0).
Notation "{[ r 'with' 'UartRegs_rbr' := e ]}" :=
  match r with Build_UartRegs (_ as f0) _ (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) (_ as f11) (_ as f12) (_ as f13) =>
    Build_UartRegs f0 e f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 end (at level 0).
Notation "{[ r 'with' 'UartRegs_ier' := e ]}" :=
  match r with Build_UartRegs (_ as f0) (_ as f1) _ (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) (_ as f11) (_ as f12) (_ as f13) =>
    Build_UartRegs f0 f1 e f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 end (at level 0).
Notation "{[ r 'with' 'UartRegs_iir' := e ]}" :=
  match r with Build_UartRegs (_ as f0) (_ as f1) (_ as f2) _ (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) (_ as f11) (_ as f12) (_ as f13) =>
    Build_UartRegs f0 f1 f2 e f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 end (at level 0).
Notation "{[ r 'with' 'UartRegs_fcr' := e ]}" :=
  match r with Build_UartRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) _ (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) (_ as f11) (_ as f12) (_ as f13) =>
    Build_UartRegs f0 f1 f2 f3 e f5 f6 f7 f8 f9 f10 f11 f12 f13 end (at level 0).
Notation "{[ r 'with' 'UartRegs_lcr' := e ]}" :=
  match r with Build_UartRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) _ (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) (_ as f11) (_ as f12) (_ as f13) =>
    Build_UartRegs f0 f1 f2 f3 f4 e f6 f7 f8 f9 f10 f11 f12 f13 end (at level 0).
Notation "{[ r 'with' 'UartRegs_mcr' := e ]}" :=
  match r with Build_UartRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) _ (_ as f7) (_ as f8) (_ as f9) (_ as f10) (_ as f11) (_ as f12) (_ as f13) =>
    Build_UartRegs f0 f1 f2 f3 f4 f5 e f7 f8 f9 f10 f11 f12 f13 end (at level 0).
Notation "{[ r 'with' 'UartRegs_lsr' := e ]}" :=
  match r with Build_UartRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) _ (_ as f8) (_ as f9) (_ as f10) (_ as f11) (_ as f12) (_ as f13) =>
    Build_UartRegs f0 f1 f2 f3 f4 f5 f6 e f8 f9 f10 f11 f12 f13 end (at level 0).
Notation "{[ r 'with' 'UartRegs_msr' := e ]}" :=
  match r with Build_UartRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) _ (_ as f9) (_ as f10) (_ as f11) (_ as f12) (_ as f13) =>
    Build_UartRegs f0 f1 f2 f3 f4 f5 f6 f7 e f9 f10 f11 f12 f13 end (at level 0).
Notation "{[ r 'with' 'UartRegs_scr' := e ]}" :=
  match r with Build_UartRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) _ (_ as f10) (_ as f11) (_ as f12) (_ as f13) =>
    Build_UartRegs f0 f1 f2 f3 f4 f5 f6 f7 f8 e f10 f11 f12 f13 end (at level 0).
Notation "{[ r 'with' 'UartRegs_dll' := e ]}" :=
  match r with Build_UartRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) _ (_ as f11) (_ as f12) (_ as f13) =>
    Build_UartRegs f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 e f11 f12 f13 end (at level 0).
Notation "{[ r 'with' 'UartRegs_dlh' := e ]}" :=
  match r with Build_UartRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) _ (_ as f12) (_ as f13) =>
    Build_UartRegs f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 e f12 f13 end (at level 0).
Notation "{[ r 'with' 'UartRegs_tx_ready' := e ]}" :=
  match r with Build_UartRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) (_ as f11) _ (_ as f13) =>
    Build_UartRegs f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 e f13 end (at level 0).
Notation "{[ r 'with' 'UartRegs_rx_ready' := e ]}" :=
  match r with Build_UartRegs (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) (_ as f6) (_ as f7) (_ as f8) (_ as f9) (_ as f10) (_ as f11) (_ as f12) _ =>
    Build_UartRegs f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 e end (at level 0).
#[export]
Instance dummy_UartRegs : Inhabited (UartRegs) := {
  inhabitant := {|
    UartRegs_thr := inhabitant;
    UartRegs_rbr := inhabitant;
    UartRegs_ier := inhabitant;
    UartRegs_iir := inhabitant;
    UartRegs_fcr := inhabitant;
    UartRegs_lcr := inhabitant;
    UartRegs_mcr := inhabitant;
    UartRegs_lsr := inhabitant;
    UartRegs_msr := inhabitant;
    UartRegs_scr := inhabitant;
    UartRegs_dll := inhabitant;
    UartRegs_dlh := inhabitant;
    UartRegs_tx_ready := inhabitant;
    UartRegs_rx_ready := inhabitant
|} }.







Variant register : Type :=

.

Definition type_of_register (r : register) : Type :=
  match r with

  end.

Instance Decidable_eq_register : EqDecision register := fun r _ => match r with end.

Instance Countable_register : Countable register := {|
  encode _ := 1%positive;
  decode _ := None;
  decode_encode (r : register) := match r with end
|}.

Definition register_transport {P : Type -> Type} {r r' : register} :
  r = r' -> P (type_of_register r) -> P (type_of_register r') :=
  match r, r' with
  end.

Lemma register_transport_sound {P} {r : register} (e : r = r) (p : P (type_of_register r)) : register_transport e p = p.
Proof.
  destruct r.
Qed.


Definition register_beq (r r' : register) : bool :=
  match r, r' with

  | _, _ => false
  end.

Lemma register_beq_refl (r : register) : register_beq r r = true.
destruct r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Definition register_eq_cast (P : Type -> Type) (r r' : register) : P (type_of_register r) -> option (P (type_of_register r')) :=
  match r, r' with

  | _, _ => fun _ => None
  end.

Definition register_list : list (string * register) := List.concat [

].

Definition string_of_register (r : register) : string :=
  match List.find (fun '(_s, r') => register_beq r r') register_list with
  | Some (s, _r) => s
  | None => "<impossible>"
  end.

Instance Pretty_register : Pretty register :=
  fun reg => string_of_register reg.

Definition register_of_string (s : string) : option register :=
  match List.find (fun '(s', _r) => String.eqb s s') register_list with
  | Some (_s, r) => Some r
  | None => None
  end.

Lemma string_of_register_roundtrip (r : register) :
  register_of_string (string_of_register r) = Some r.
case r; intro r'; destruct r'; reflexivity.
Qed.

#[export] Instance string_of_register_inj : Inj (=) (=) string_of_register.
Proof.
  intros r r' H.
  specialize (string_of_register_roundtrip r) as H1.
  specialize (string_of_register_roundtrip r') as H2.
  rewrite H in H1.
  rewrite H2 in H1.
  congruence.
Qed.
#[export] Hint Extern 1 (register _) => assumption : typeclass_instances.
#[export] Instance Decidable_eq_register_values `(r : register) : EqDecision (type_of_register r) | 100 :=
match r with

end.
#[export] Instance Inhabited_register_values `(r : register) : Inhabited (type_of_register r) | 100 :=
  match r with

end.
#[export] Instance Countable_register_values `(r : register) : Countable (type_of_register r) | 100.
refine {|
  encode := match r with

  end;
  decode := match r with

  end;
|}.
abstract (destruct r; apply decode_encode).
Defined.



(* Definitions to support the lifting to the sequential monad *)
Record regstate := {

}.


Definition init_regstate : regstate := Build_regstate

.

Definition register_lookup (reg : register) (rs : regstate) : type_of_register reg :=
  match reg with

  end.

Definition register_set (reg : register) : type_of_register reg -> regstate -> regstate :=
  match reg with

  end.

Lemma register_lookup_set (r : register) regs v: register_lookup r (register_set r v regs) = v.
destruct regs, r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Lemma irrelevant_register_set (r r' : register) regs v:
  register_beq r r' = false ->
  register_lookup r (register_set r' v regs) = register_lookup r regs.
destruct regs, r, r'; simpl; intro EQ; rewrite ?EQ; reflexivity.
Qed.

Arguments register_set : simpl never.
Arguments register_lookup : simpl never.

Definition register_accessors : register_accessors regstate register type_of_register := (@register_lookup, @register_set).


(* Instantiate library definitions with types. *)

Definition read_reg {E} := @read_reg register type_of_register E.
Definition write_reg {E} := @write_reg register type_of_register E.
Definition MR r a := @monadR register type_of_register a r unit.
Definition M a := @monad register type_of_register a unit.
Definition returnM {A:Type} := @returnm register type_of_register A unit.
Definition returnR {A:Type} (R:Type) := @returnm register type_of_register A (R + unit).
Definition register_ref := @register_ref register type_of_register.