(*Generated by Sail from upstream_ptw.*)


From stdpp Require Import base countable pretty.
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.

Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.

Definition bit : Type := mword 1.

Definition bits (n : Z) : Type := mword n.

Inductive ptw_res {a : Type} {b : Type} :=
| Ok : a -> ptw_res
| Err : b -> ptw_res.
Arguments ptw_res : clear implicits.

Definition sail_ptw_res_encode {a : Type} {b : Type} `{Countable a} `{Countable b}
  (x : (ptw_res a b)) := match x with
  | Ok x' => encode (0, encode x')
  | Err x' => encode (1, encode x') end.
Definition sail_ptw_res_decode {a : Type} {b : Type} `{Countable a} `{Countable b} x
  : option (ptw_res a b) := match decode x with
  | Some (0, x') => Ok <$> decode x'
  | Some (1, x') => Err <$> decode x'
  | _ => None end.
Lemma sail_ptw_res_decode_encode {a : Type} {b : Type} `{Countable a} `{Countable b} :
  forall (x : (ptw_res a b)), sail_ptw_res_decode (sail_ptw_res_encode x)  = Some x.
Proof.
  unfold sail_ptw_res_decode, sail_ptw_res_encode;
  intros [x|x]; rewrite !decode_encode; reflexivity.
Qed.

#[export]
Instance Decidable_eq_ptw_res {a : Type} {b : Type} `{Countable a} `{Countable b} :
  EqDecision (ptw_res a b) := decode_encode_eq_dec sail_ptw_res_encode sail_ptw_res_decode
  sail_ptw_res_decode_encode .

#[export]
Instance Countable_ptw_res {a : Type} {b : Type} `{Countable a} `{Countable b} : Countable
  (ptw_res a b) := {|
  encode := sail_ptw_res_encode;
  decode := sail_ptw_res_decode;
  decode_encode := sail_ptw_res_decode_encode
|}.
#[export]
Instance dummy_ptw_res {a : Type} {b : Type} `{Inhabited a} `{Inhabited b} :
  Inhabited (ptw_res a b) := {
  inhabitant := Ok inhabitant
}.

Definition pte_flags_bits : Type := bits 8.

Definition pte_ext_bits : Type := bits 10.

Definition PTE_Flags : Type := mword 8.

Definition PTE_Ext : Type := mword 10.

Inductive PTW_Error := PTW_No_Access | PTW_Invalid_PTE | PTW_Misaligned.
Definition num_of_PTW_Error (arg_ : PTW_Error) : Z :=
   match arg_ with | PTW_No_Access => 0 | PTW_Invalid_PTE => 1 | PTW_Misaligned => 2 end.

Definition PTW_Error_of_num (arg_ : Z) (*(0 <=? arg_) && (arg_ <=? 2)*) : PTW_Error :=
   let l__0 := arg_ in
   if Z.eqb (l__0) (0) then PTW_No_Access
   else if Z.eqb (l__0) (1) then PTW_Invalid_PTE
   else PTW_Misaligned.

Lemma PTW_Error_num_of_roundtrip (x : PTW_Error) : PTW_Error_of_num (num_of_PTW_Error x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_PTW_Error_injective (x y : PTW_Error) : num_of_PTW_Error x = num_of_PTW_Error y -> x = y.
  intro.
  rewrite <- (PTW_Error_num_of_roundtrip x).
  rewrite <- (PTW_Error_num_of_roundtrip y).
  congruence.
Qed.
Definition PTW_Error_eq_dec (x y : PTW_Error) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_PTW_Error x) (num_of_PTW_Error y) with
  | left e => left (num_of_PTW_Error_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition PTW_Error_beq (x y : PTW_Error) : bool :=
  Z.eqb (num_of_PTW_Error x) (num_of_PTW_Error y).
Lemma PTW_Error_beq_iff x y : PTW_Error_beq x y = true <-> x = y.
  unfold PTW_Error_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_PTW_Error_injective | congruence].
Qed.
Lemma PTW_Error_beq_refl x : PTW_Error_beq x x = true.
apply PTW_Error_beq_iff; reflexivity.
Qed.
#[export]
Instance Decidable_eq_PTW_Error : EqDecision PTW_Error := PTW_Error_eq_dec.
#[export]
Instance Countable_PTW_Error : Countable PTW_Error.
refine {|
  encode x := encode (num_of_PTW_Error x);
  decode x := z ← decode x; mret (PTW_Error_of_num z);
|}.
abstract (
  intro s; rewrite decode_encode;
  simpl;
  rewrite PTW_Error_num_of_roundtrip;
  reflexivity).
Defined.
#[export]
Instance dummy_PTW_Error : Inhabited PTW_Error := { inhabitant := PTW_No_Access }.


Inductive page_based_mem_type := PBMT_PMA | PBMT_NC | PBMT_IO.
Definition num_of_page_based_mem_type (arg_ : page_based_mem_type) : Z :=
   match arg_ with | PBMT_PMA => 0 | PBMT_NC => 1 | PBMT_IO => 2 end.

Definition page_based_mem_type_of_num (arg_ : Z) (*(0 <=? arg_) && (arg_ <=? 2)*)
: page_based_mem_type :=
   let l__0 := arg_ in
   if Z.eqb (l__0) (0) then PBMT_PMA
   else if Z.eqb (l__0) (1) then PBMT_NC
   else PBMT_IO.

Lemma page_based_mem_type_num_of_roundtrip (x : page_based_mem_type) : page_based_mem_type_of_num (num_of_page_based_mem_type x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_page_based_mem_type_injective (x y : page_based_mem_type) : num_of_page_based_mem_type x = num_of_page_based_mem_type y -> x = y.
  intro.
  rewrite <- (page_based_mem_type_num_of_roundtrip x).
  rewrite <- (page_based_mem_type_num_of_roundtrip y).
  congruence.
Qed.
Definition page_based_mem_type_eq_dec (x y : page_based_mem_type) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_page_based_mem_type x) (num_of_page_based_mem_type y) with
  | left e => left (num_of_page_based_mem_type_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition page_based_mem_type_beq (x y : page_based_mem_type) : bool :=
  Z.eqb (num_of_page_based_mem_type x) (num_of_page_based_mem_type y).
Lemma page_based_mem_type_beq_iff x y : page_based_mem_type_beq x y = true <-> x = y.
  unfold page_based_mem_type_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_page_based_mem_type_injective | congruence].
Qed.
Lemma page_based_mem_type_beq_refl x : page_based_mem_type_beq x x = true.
apply page_based_mem_type_beq_iff; reflexivity.
Qed.
#[export]
Instance Decidable_eq_page_based_mem_type : EqDecision page_based_mem_type :=
  page_based_mem_type_eq_dec.
#[export]
Instance Countable_page_based_mem_type : Countable page_based_mem_type.
refine {|
  encode x := encode (num_of_page_based_mem_type x);
  decode x := z ← decode x; mret (page_based_mem_type_of_num z);
|}.
abstract (
  intro s; rewrite decode_encode;
  simpl;
  rewrite page_based_mem_type_num_of_roundtrip;
  reflexivity).
Defined.
#[export]
Instance dummy_page_based_mem_type : Inhabited page_based_mem_type := { inhabitant := PBMT_PMA }.


Record PTW_Output := {
  PTW_Output_ppn : bits 44;
  PTW_Output_pte : bits 64;
  PTW_Output_pteAddr : bits 56;
  PTW_Output_level : Z;
  PTW_Output_pbmt : page_based_mem_type;
  PTW_Output_global : bool;
}.
Arguments PTW_Output : clear implicits.
#[export]
Instance Decidable_eq_PTW_Output : EqDecision PTW_Output.
   intros [x0 x1 x2 x3 x4 x5].
   intros [y0 y1 y2 y3 y4 y5].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
  cmp_record_field x2 y2.
  cmp_record_field x3 y3.
  cmp_record_field x4 y4.
  cmp_record_field x5 y5.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_PTW_Output : Countable PTW_Output.
refine {|
  encode x := encode (PTW_Output_ppn x, PTW_Output_pte x, PTW_Output_pteAddr x, PTW_Output_level x, PTW_Output_pbmt x, PTW_Output_global x);
  decode x := '(x0, x1, x2, x3, x4, x5) ← decode x;
              mret (Build_PTW_Output x0 x1 x2 x3 x4 x5)
|}.
abstract (
  intros [x0 x1 x2 x3 x4 x5];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'PTW_Output_ppn' := e ]}" :=
  match r with Build_PTW_Output _ (_ as f1) (_ as f2) (_ as f3) (_ as f4) (_ as f5) =>
    Build_PTW_Output e f1 f2 f3 f4 f5 end (at level 0).
Notation "{[ r 'with' 'PTW_Output_pte' := e ]}" :=
  match r with Build_PTW_Output (_ as f0) _ (_ as f2) (_ as f3) (_ as f4) (_ as f5) =>
    Build_PTW_Output f0 e f2 f3 f4 f5 end (at level 0).
Notation "{[ r 'with' 'PTW_Output_pteAddr' := e ]}" :=
  match r with Build_PTW_Output (_ as f0) (_ as f1) _ (_ as f3) (_ as f4) (_ as f5) =>
    Build_PTW_Output f0 f1 e f3 f4 f5 end (at level 0).
Notation "{[ r 'with' 'PTW_Output_level' := e ]}" :=
  match r with Build_PTW_Output (_ as f0) (_ as f1) (_ as f2) _ (_ as f4) (_ as f5) =>
    Build_PTW_Output f0 f1 f2 e f4 f5 end (at level 0).
Notation "{[ r 'with' 'PTW_Output_pbmt' := e ]}" :=
  match r with Build_PTW_Output (_ as f0) (_ as f1) (_ as f2) (_ as f3) _ (_ as f5) =>
    Build_PTW_Output f0 f1 f2 f3 e f5 end (at level 0).
Notation "{[ r 'with' 'PTW_Output_global' := e ]}" :=
  match r with Build_PTW_Output (_ as f0) (_ as f1) (_ as f2) (_ as f3) (_ as f4) _ =>
    Build_PTW_Output f0 f1 f2 f3 f4 e end (at level 0).
#[export]
Instance dummy_PTW_Output : Inhabited (PTW_Output) := {
  inhabitant := {|
    PTW_Output_ppn := inhabitant;
    PTW_Output_pte := inhabitant;
    PTW_Output_pteAddr := inhabitant;
    PTW_Output_level := inhabitant;
    PTW_Output_pbmt := inhabitant;
    PTW_Output_global := inhabitant
|} }.


Definition Mem : Type := list ((bits 56 * bits 64)).

Inductive Extension := Ext_Svnapot | Ext_Sv39.
Definition num_of_Extension (arg_ : Extension) : Z :=
   match arg_ with | Ext_Svnapot => 0 | Ext_Sv39 => 1 end.

Definition Extension_of_num (arg_ : Z) (*(0 <=? arg_) && (arg_ <=? 1)*) : Extension :=
   let l__0 := arg_ in
   if Z.eqb (l__0) (0) then Ext_Svnapot
   else Ext_Sv39.

Lemma Extension_num_of_roundtrip (x : Extension) : Extension_of_num (num_of_Extension x) = x.
  destruct x; reflexivity.
Qed.
Lemma num_of_Extension_injective (x y : Extension) : num_of_Extension x = num_of_Extension y -> x = y.
  intro.
  rewrite <- (Extension_num_of_roundtrip x).
  rewrite <- (Extension_num_of_roundtrip y).
  congruence.
Qed.
Definition Extension_eq_dec (x y : Extension) : {x = y} + {x <> y}.
  refine (match Z.eq_dec (num_of_Extension x) (num_of_Extension y) with
  | left e => left (num_of_Extension_injective x y e)
  | right ne => right _
  end).
  congruence.
Defined.
Definition Extension_beq (x y : Extension) : bool :=
  Z.eqb (num_of_Extension x) (num_of_Extension y).
Lemma Extension_beq_iff x y : Extension_beq x y = true <-> x = y.
  unfold Extension_beq.
  rewrite Z.eqb_eq.
  split; [apply num_of_Extension_injective | congruence].
Qed.
Lemma Extension_beq_refl x : Extension_beq x x = true.
apply Extension_beq_iff; reflexivity.
Qed.
#[export]
Instance Decidable_eq_Extension : EqDecision Extension := Extension_eq_dec.
#[export]
Instance Countable_Extension : Countable Extension.
refine {|
  encode x := encode (num_of_Extension x);
  decode x := z ← decode x; mret (Extension_of_num z);
|}.
abstract (
  intro s; rewrite decode_encode;
  simpl;
  rewrite Extension_num_of_roundtrip;
  reflexivity).
Defined.
#[export]
Instance dummy_Extension : Inhabited Extension := { inhabitant := Ext_Svnapot }.







Variant register : Type :=

.

Definition type_of_register (r : register) : Type :=
  match r with

  end.

Instance Decidable_eq_register : EqDecision register := fun r _ => match r with end.

Instance Countable_register : Countable register := {|
  encode _ := 1%positive;
  decode _ := None;
  decode_encode (r : register) := match r with end
|}.

Definition register_transport {P : Type -> Type} {r r' : register} :
  r = r' -> P (type_of_register r) -> P (type_of_register r') :=
  match r, r' with
  end.

Lemma register_transport_sound {P} {r : register} (e : r = r) (p : P (type_of_register r)) : register_transport e p = p.
Proof.
  destruct r.
Qed.


Definition register_beq (r r' : register) : bool :=
  match r, r' with

  | _, _ => false
  end.

Lemma register_beq_refl (r : register) : register_beq r r = true.
destruct r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Definition register_eq_cast (P : Type -> Type) (r r' : register) : P (type_of_register r) -> option (P (type_of_register r')) :=
  match r, r' with

  | _, _ => fun _ => None
  end.

Definition register_list : list (string * register) := List.concat [

].

Definition string_of_register (r : register) : string :=
  match List.find (fun '(_s, r') => register_beq r r') register_list with
  | Some (s, _r) => s
  | None => "<impossible>"
  end.

Instance Pretty_register : Pretty register :=
  fun reg => string_of_register reg.

Definition register_of_string (s : string) : option register :=
  match List.find (fun '(s', _r) => String.eqb s s') register_list with
  | Some (_s, r) => Some r
  | None => None
  end.

Lemma string_of_register_roundtrip (r : register) :
  register_of_string (string_of_register r) = Some r.
case r; intro r'; destruct r'; reflexivity.
Qed.

#[export] Instance string_of_register_inj : Inj (=) (=) string_of_register.
Proof.
  intros r r' H.
  specialize (string_of_register_roundtrip r) as H1.
  specialize (string_of_register_roundtrip r') as H2.
  rewrite H in H1.
  rewrite H2 in H1.
  congruence.
Qed.
#[export] Hint Extern 1 (register _) => assumption : typeclass_instances.
#[export] Instance Decidable_eq_register_values `(r : register) : EqDecision (type_of_register r) | 100 :=
match r with

end.
#[export] Instance Inhabited_register_values `(r : register) : Inhabited (type_of_register r) | 100 :=
  match r with

end.
#[export] Instance Countable_register_values `(r : register) : Countable (type_of_register r) | 100.
refine {|
  encode := match r with

  end;
  decode := match r with

  end;
|}.
abstract (destruct r; apply decode_encode).
Defined.



(* Definitions to support the lifting to the sequential monad *)
Record regstate := {

}.


Definition init_regstate : regstate := Build_regstate

.

Definition register_lookup (reg : register) (rs : regstate) : type_of_register reg :=
  match reg with

  end.

Definition register_set (reg : register) : type_of_register reg -> regstate -> regstate :=
  match reg with

  end.

Lemma register_lookup_set (r : register) regs v: register_lookup r (register_set r v regs) = v.
destruct regs, r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Lemma irrelevant_register_set (r r' : register) regs v:
  register_beq r r' = false ->
  register_lookup r (register_set r' v regs) = register_lookup r regs.
destruct regs, r, r'; simpl; intro EQ; rewrite ?EQ; reflexivity.
Qed.

Arguments register_set : simpl never.
Arguments register_lookup : simpl never.

Definition register_accessors : register_accessors regstate register type_of_register := (@register_lookup, @register_set).


(* Instantiate library definitions with types. *)

Definition read_reg {E} := @read_reg register type_of_register E.
Definition write_reg {E} := @write_reg register type_of_register E.
Definition MR r a := @monadR register type_of_register a r unit.
Definition M a := @monad register type_of_register a unit.
Definition returnM {A:Type} := @returnm register type_of_register A unit.
Definition returnR {A:Type} (R:Type) := @returnm register type_of_register A (R + unit).
Definition register_ref := @register_ref register type_of_register.