(*Generated by Sail from upstream_vmem_pte.*)
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.
Require Import upstream_vmem_pte_types.
Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.


Definition neq_int (x : Z) (y : Z) : bool := negb ((Z.eqb (x) (y))).

Definition neq_bool (x : bool) (y : bool) : bool := negb ((Bool.eqb (x) (y))).

Definition __id (x : Z) : Z := x.

Definition _shl_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shl_int (m) (n) else shr_int (m) ((Z.opp (n))).

Definition _shr_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shr_int (m) (n) else shl_int (m) ((Z.opp (n))).

Definition fdiv_int (n : Z) (m : Z) : Z :=
   if andb ((Z.ltb (n) (0))) ((Z.gtb (m) (0))) then Z.sub ((Z.quot ((Z.add (n) (1))) (m))) (1)
   else if andb ((Z.gtb (n) (0))) ((Z.ltb (m) (0))) then Z.sub ((Z.quot ((Z.sub (n) (1))) (m))) (1)
   else Z.quot (n) (m).

Definition fmod_int (n : Z) (m : Z) : Z := Z.sub (n) ((Z.mul (m) ((fdiv_int (n) (m))))).

Definition sail_mask {v0 : Z} (len : Z) (v : mword v0) (*(len >=? 0) && (v0 >=? 0)*) : mword len :=
   if Z.leb (len) v0 then vector_truncate (v) (len) else zero_extend (v) (len).

Definition sail_ones (n : Z) (*n >=? 0*) : mword n := not_vec ((zeros (n))).

Definition slice_mask (n : Z) (i : Z) (l : Z) (*n >=? 0*) : mword n :=
   if Z.geb (l) (n) then shiftl ((sail_ones (n))) (i)
   else
     let one : bits n := sail_mask (n) ((('b"1")  : bits 1)) in
     shiftl ((sub_vec ((shiftl (one) (l))) (one))) (i).

Definition to_bytes_le (n : Z) (b : mword (8 * n)) (*n >? 0*) : vec (mword 8) n :=
   let res := vector_init (n) ((zeros (8))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       vec_update_dec (res) (i)
         ((autocast (T := mword)
           (subrange_vec_dec (b) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))))))).

Definition from_bytes_le (n : Z) (v : vec (mword 8) n) (*n >? 0*) : mword (8 * n) :=
   let res := zeros ((Z.mul (8) (n))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       update_subrange_vec_dec (res) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))
         ((autocast (T := mword)
           (vec_access_dec (v) (i)))))).

Definition is_none {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => false | None => true end.

Definition is_some {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => true | None => false end.

Definition concat_str_bits {n : Z} (str : string) (x : mword n) : string :=
   String.append (str) ((string_of_bits (x))).

Definition concat_str_dec (str : string) (x : Z) : string := String.append (str) ((dec_str (x))).

Definition bool_bit_forwards (arg_ : bool) : mword 1 :=
   match arg_ with | false => ('b"0") | true => ('b"1") end.

Definition bool_bit_backwards (arg_ : mword 1) : bool :=
   let p0_ := arg_ in
   if eq_vec (p0_) (('b"0")) then false
   else true.

Definition bool_bit_forwards_matches (arg_ : bool) : bool :=
   match arg_ with | false => true | true => true end.

Definition bool_bit_backwards_matches (arg_ : mword 1) : bool :=
   let p0_ := arg_ in
   if eq_vec (p0_) (('b"0")) then true
   else if eq_vec (p0_) (('b"1")) then true
   else false.

Definition not (b : bool) : bool := negb (b).

Definition bit_to_bool (x : mword 1) : bool := bool_bit_backwards (x).

Definition undefined_PTE_Ext '(tt : unit) : M (mword 10) :=
   (undefined_bitvector (10))  : M (mword 10).

Definition Mk_PTE_Ext (v : mword 10) : mword 10 := v.

Definition _get_PTE_Ext_bits (v : mword 10) : mword 10 :=
   subrange_vec_dec (v) ((Z.sub (10) (1))) (0).

Definition _update_PTE_Ext_bits (v : mword 10) (x : mword 10) : mword 10 :=
   update_subrange_vec_dec (v) ((Z.sub (10) (1))) (0) (x).

Definition _update_PTE_Flags_bits (v : mword 8) (x : mword 8) : mword 8 :=
   update_subrange_vec_dec (v) ((Z.sub (8) (1))) (0) (x).

Definition _set_PTE_Ext_bits (r_ref : register_ref (mword 10)) (v : mword 10) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Ext_bits (r) (v))  : M (unit).

Definition _get_PTE_Flags_bits (v : mword 8) : mword 8 :=
   subrange_vec_dec (v) ((Z.sub (8) (1))) (0).

Definition _set_PTE_Flags_bits (r_ref : register_ref (mword 8)) (v : mword 8) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_bits (r) (v))  : M (unit).

Definition _get_PTE_Ext_N (v : mword 10) : mword 1 := subrange_vec_dec (v) (9) (9).

Definition _update_PTE_Ext_N (v : mword 10) (x : mword 1) : mword 10 :=
   update_subrange_vec_dec (v) (9) (9) (x).

Definition _set_PTE_Ext_N (r_ref : register_ref (mword 10)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Ext_N (r) (v))  : M (unit).

Definition _get_PTE_Ext_PBMT (v : mword 10) : mword 2 := subrange_vec_dec (v) (8) (7).

Definition _update_PTE_Ext_PBMT (v : mword 10) (x : mword 2) : mword 10 :=
   update_subrange_vec_dec (v) (8) (7) (x).

Definition _set_PTE_Ext_PBMT (r_ref : register_ref (mword 10)) (v : mword 2) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Ext_PBMT (r) (v))  : M (unit).

Definition _get_PTE_Ext_RSW_60t59b (v : mword 10) : mword 2 := subrange_vec_dec (v) (6) (5).

Definition _update_PTE_Ext_RSW_60t59b (v : mword 10) (x : mword 2) : mword 10 :=
   update_subrange_vec_dec (v) (6) (5) (x).

Definition _set_PTE_Ext_RSW_60t59b (r_ref : register_ref (mword 10)) (v : mword 2) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r =>
   write_reg_ref r_ref (_update_PTE_Ext_RSW_60t59b (r) (v))
    : M (unit).

Definition _get_PTE_Ext_reserved (v : mword 10) : mword 5 := subrange_vec_dec (v) (4) (0).

Definition _update_PTE_Ext_reserved (v : mword 10) (x : mword 5) : mword 10 :=
   update_subrange_vec_dec (v) (4) (0) (x).

Definition _set_PTE_Ext_reserved (r_ref : register_ref (mword 10)) (v : mword 5) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r =>
   write_reg_ref r_ref (_update_PTE_Ext_reserved (r) (v))
    : M (unit).

Definition default_sv32_ext_pte : pte_ext_bits := ('b"0000000000").
#[export] Hint Unfold default_sv32_ext_pte : sail.
Definition ext_bits_of_PTE {pte_size : Z} (pte : mword pte_size) (*member_Z_list pte_size [32; 64]*)
: mword 10 :=
   Mk_PTE_Ext
     ((if Z.eqb pte_size (64) then subrange_vec_dec (pte) (63) (54)
       else default_sv32_ext_pte)).

Definition PPN_of_PTE {pte_size : Z} (pte : mword pte_size) (*member_Z_list pte_size [32; 64]*)
: mword ((if pte_size =? 32 then 22 else 44)) :=
   if Z.eqb pte_size (32) then autocast (T := mword) (subrange_vec_dec (pte) (31) (10))
   else autocast (T := mword) (subrange_vec_dec (pte) (53) (10)).

Definition undefined_PTE_Flags '(tt : unit) : M (mword 8) :=
   (undefined_bitvector (8))  : M (mword 8).

Definition Mk_PTE_Flags (v : mword 8) : mword 8 := v.

Definition _get_PTE_Flags_A (v : mword 8) : mword 1 := subrange_vec_dec (v) (6) (6).

Definition _update_PTE_Flags_A (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (6) (6) (x).

Definition _set_PTE_Flags_A (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_A (r) (v))  : M (unit).

Definition _get_PTE_Flags_D (v : mword 8) : mword 1 := subrange_vec_dec (v) (7) (7).

Definition _update_PTE_Flags_D (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (7) (7) (x).

Definition _set_PTE_Flags_D (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_D (r) (v))  : M (unit).

Definition _get_PTE_Flags_G (v : mword 8) : mword 1 := subrange_vec_dec (v) (5) (5).

Definition _update_PTE_Flags_G (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (5) (5) (x).

Definition _set_PTE_Flags_G (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_G (r) (v))  : M (unit).

Definition _get_PTE_Flags_R (v : mword 8) : mword 1 := subrange_vec_dec (v) (1) (1).

Definition _update_PTE_Flags_R (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (1) (1) (x).

Definition _set_PTE_Flags_R (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_R (r) (v))  : M (unit).

Definition _get_PTE_Flags_U (v : mword 8) : mword 1 := subrange_vec_dec (v) (4) (4).

Definition _update_PTE_Flags_U (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (4) (4) (x).

Definition _set_PTE_Flags_U (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_U (r) (v))  : M (unit).

Definition _get_PTE_Flags_V (v : mword 8) : mword 1 := subrange_vec_dec (v) (0) (0).

Definition _update_PTE_Flags_V (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (0) (0) (x).

Definition _set_PTE_Flags_V (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_V (r) (v))  : M (unit).

Definition _get_PTE_Flags_W (v : mword 8) : mword 1 := subrange_vec_dec (v) (2) (2).

Definition _update_PTE_Flags_W (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (2) (2) (x).

Definition _set_PTE_Flags_W (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_W (r) (v))  : M (unit).

Definition _get_PTE_Flags_X (v : mword 8) : mword 1 := subrange_vec_dec (v) (3) (3).

Definition _update_PTE_Flags_X (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (3) (3) (x).

Definition _set_PTE_Flags_X (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_X (r) (v))  : M (unit).

Definition pte_is_non_leaf (pte_flags : mword 8) : bool :=
   andb ((eq_vec ((_get_PTE_Flags_X (pte_flags))) (('b"0"))))
     ((andb ((eq_vec ((_get_PTE_Flags_W (pte_flags))) (('b"0"))))
         ((eq_vec ((_get_PTE_Flags_R (pte_flags))) (('b"0")))))).

Definition pte_is_invalid (pte_flags : mword 8) (pte_ext : mword 10) : bool :=
   orb ((eq_vec ((_get_PTE_Flags_V (pte_flags))) (('b"0"))))
     ((orb
         ((andb ((eq_vec ((_get_PTE_Flags_R (pte_flags))) (('b"0"))))
             ((andb ((eq_vec ((_get_PTE_Flags_W (pte_flags))) (('b"1"))))
                 ((eq_vec ((_get_PTE_Flags_X (pte_flags))) (('b"0"))))))))
         ((orb
             ((andb ((eq_vec ((_get_PTE_Flags_R (pte_flags))) (('b"0"))))
                 ((andb ((eq_vec ((_get_PTE_Flags_W (pte_flags))) (('b"1"))))
                     ((eq_vec ((_get_PTE_Flags_X (pte_flags))) (('b"1"))))))))
             ((orb
                 ((andb ((pte_is_non_leaf (pte_flags)))
                     ((orb ((eq_vec ((_get_PTE_Flags_A (pte_flags))) (('b"1"))))
                         ((orb ((eq_vec ((_get_PTE_Flags_D (pte_flags))) (('b"1"))))
                             ((orb ((eq_vec ((_get_PTE_Flags_U (pte_flags))) (('b"1"))))
                                 ((neq_vec (pte_ext) (('b"0000000000"))))))))))))
                 ((orb ((neq_vec ((_get_PTE_Ext_PBMT (pte_ext))) (('b"00"))))
                     ((orb ((neq_vec ((_get_PTE_Ext_RSW_60t59b (pte_ext))) (('b"00"))))
                         ((neq_vec ((_get_PTE_Ext_reserved (pte_ext))) (('b"00000")))))))))))))).

Definition initialize_registers '(tt : unit) : unit := tt.

Definition sail_model_init (_ : unit) : unit := initialize_registers (tt).



