(*Generated by Sail from upstream_ptw.*)
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.
Require Import upstream_ptw_types.
Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.


Definition neq_int (x : Z) (y : Z) : bool := negb ((Z.eqb (x) (y))).

Definition neq_bool (x : bool) (y : bool) : bool := negb ((Bool.eqb (x) (y))).

Definition __id (x : Z) : Z := x.

Definition _shl_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shl_int (m) (n) else shr_int (m) ((Z.opp (n))).

Definition _shr_int_general (m : Z) (n : Z) : Z :=
   if Z.geb (n) (0) then shr_int (m) (n) else shl_int (m) ((Z.opp (n))).

Definition fdiv_int (n : Z) (m : Z) : Z :=
   if andb ((Z.ltb (n) (0))) ((Z.gtb (m) (0))) then Z.sub ((Z.quot ((Z.add (n) (1))) (m))) (1)
   else if andb ((Z.gtb (n) (0))) ((Z.ltb (m) (0))) then Z.sub ((Z.quot ((Z.sub (n) (1))) (m))) (1)
   else Z.quot (n) (m).

Definition fmod_int (n : Z) (m : Z) : Z := Z.sub (n) ((Z.mul (m) ((fdiv_int (n) (m))))).

Definition sail_mask {v0 : Z} (len : Z) (v : mword v0) (*(len >=? 0) && (v0 >=? 0)*) : mword len :=
   if Z.leb (len) v0 then vector_truncate (v) (len) else zero_extend (v) (len).

Definition sail_ones (n : Z) (*n >=? 0*) : mword n := not_vec ((zeros (n))).

Definition slice_mask (n : Z) (i : Z) (l : Z) (*n >=? 0*) : mword n :=
   if Z.geb (l) (n) then shiftl ((sail_ones (n))) (i)
   else
     let one : bits n := sail_mask (n) ((('b"1")  : bits 1)) in
     shiftl ((sub_vec ((shiftl (one) (l))) (one))) (i).

Definition to_bytes_le (n : Z) (b : mword (8 * n)) (*n >? 0*) : vec (mword 8) n :=
   let res := vector_init (n) ((zeros (8))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       vec_update_dec (res) (i)
         ((autocast (T := mword)
           (subrange_vec_dec (b) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))))))).

Definition from_bytes_le (n : Z) (v : vec (mword 8) n) (*n >? 0*) : mword (8 * n) :=
   let res := zeros ((Z.mul (8) (n))) in
   let '(loop_i_lower) := 0 in
   let '(loop_i_upper) := Z.sub (n) (1) in
   (foreach_Z_up loop_i_lower loop_i_upper 1 res
     (fun i res =>
       update_subrange_vec_dec (res) ((Z.add ((Z.mul (8) (i))) (7))) ((Z.mul (8) (i)))
         ((autocast (T := mword)
           (vec_access_dec (v) (i)))))).

Definition is_none {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => false | None => true end.

Definition is_some {a : Type} (opt : option a) : bool :=
   match opt with | Some _ => true | None => false end.

Definition concat_str_bits {n : Z} (str : string) (x : mword n) : string :=
   String.append (str) ((string_of_bits (x))).

Definition concat_str_dec (str : string) (x : Z) : string := String.append (str) ((dec_str (x))).

Definition bool_bit_forwards (arg_ : bool) : mword 1 :=
   match arg_ with | false => ('b"0") | true => ('b"1") end.

Definition bool_bit_backwards (arg_ : mword 1) : bool :=
   let p0_ := arg_ in
   if eq_vec (p0_) (('b"0")) then false
   else true.

Definition bool_bit_forwards_matches (arg_ : bool) : bool :=
   match arg_ with | false => true | true => true end.

Definition bool_bit_backwards_matches (arg_ : mword 1) : bool :=
   let p0_ := arg_ in
   if eq_vec (p0_) (('b"0")) then true
   else if eq_vec (p0_) (('b"1")) then true
   else false.

Definition not (b : bool) : bool := negb (b).

Definition undefined_PTE_Flags '(tt : unit) : M (mword 8) :=
   (undefined_bitvector (8))  : M (mword 8).

Definition Mk_PTE_Flags (v : mword 8) : mword 8 := v.

Definition _get_PTE_Flags_bits (v : mword 8) : mword 8 :=
   subrange_vec_dec (v) ((Z.sub (8) (1))) (0).

Definition _update_PTE_Flags_bits (v : mword 8) (x : mword 8) : mword 8 :=
   update_subrange_vec_dec (v) ((Z.sub (8) (1))) (0) (x).

Definition _update_PTE_Ext_bits (v : mword 10) (x : mword 10) : mword 10 :=
   update_subrange_vec_dec (v) ((Z.sub (10) (1))) (0) (x).

Definition _set_PTE_Flags_bits (r_ref : register_ref (mword 8)) (v : mword 8) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_bits (r) (v))  : M (unit).

Definition _get_PTE_Ext_bits (v : mword 10) : mword 10 :=
   subrange_vec_dec (v) ((Z.sub (10) (1))) (0).

Definition _set_PTE_Ext_bits (r_ref : register_ref (mword 10)) (v : mword 10) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Ext_bits (r) (v))  : M (unit).

Definition _get_PTE_Flags_A (v : mword 8) : mword 1 := subrange_vec_dec (v) (6) (6).

Definition _update_PTE_Flags_A (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (6) (6) (x).

Definition _set_PTE_Flags_A (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_A (r) (v))  : M (unit).

Definition _get_PTE_Flags_D (v : mword 8) : mword 1 := subrange_vec_dec (v) (7) (7).

Definition _update_PTE_Flags_D (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (7) (7) (x).

Definition _set_PTE_Flags_D (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_D (r) (v))  : M (unit).

Definition _get_PTE_Flags_G (v : mword 8) : mword 1 := subrange_vec_dec (v) (5) (5).

Definition _update_PTE_Flags_G (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (5) (5) (x).

Definition _set_PTE_Flags_G (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_G (r) (v))  : M (unit).

Definition _get_PTE_Flags_R (v : mword 8) : mword 1 := subrange_vec_dec (v) (1) (1).

Definition _update_PTE_Flags_R (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (1) (1) (x).

Definition _set_PTE_Flags_R (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_R (r) (v))  : M (unit).

Definition _get_PTE_Flags_U (v : mword 8) : mword 1 := subrange_vec_dec (v) (4) (4).

Definition _update_PTE_Flags_U (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (4) (4) (x).

Definition _set_PTE_Flags_U (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_U (r) (v))  : M (unit).

Definition _get_PTE_Flags_V (v : mword 8) : mword 1 := subrange_vec_dec (v) (0) (0).

Definition _update_PTE_Flags_V (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (0) (0) (x).

Definition _set_PTE_Flags_V (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_V (r) (v))  : M (unit).

Definition _get_PTE_Flags_W (v : mword 8) : mword 1 := subrange_vec_dec (v) (2) (2).

Definition _update_PTE_Flags_W (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (2) (2) (x).

Definition _set_PTE_Flags_W (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_W (r) (v))  : M (unit).

Definition _get_PTE_Flags_X (v : mword 8) : mword 1 := subrange_vec_dec (v) (3) (3).

Definition _update_PTE_Flags_X (v : mword 8) (x : mword 1) : mword 8 :=
   update_subrange_vec_dec (v) (3) (3) (x).

Definition _set_PTE_Flags_X (r_ref : register_ref (mword 8)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Flags_X (r) (v))  : M (unit).

Definition undefined_PTE_Ext '(tt : unit) : M (mword 10) :=
   (undefined_bitvector (10))  : M (mword 10).

Definition Mk_PTE_Ext (v : mword 10) : mword 10 := v.

Definition _get_PTE_Ext_N (v : mword 10) : mword 1 := subrange_vec_dec (v) (9) (9).

Definition _update_PTE_Ext_N (v : mword 10) (x : mword 1) : mword 10 :=
   update_subrange_vec_dec (v) (9) (9) (x).

Definition _set_PTE_Ext_N (r_ref : register_ref (mword 10)) (v : mword 1) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Ext_N (r) (v))  : M (unit).

Definition _get_PTE_Ext_PBMT (v : mword 10) : mword 2 := subrange_vec_dec (v) (8) (7).

Definition _update_PTE_Ext_PBMT (v : mword 10) (x : mword 2) : mword 10 :=
   update_subrange_vec_dec (v) (8) (7) (x).

Definition _set_PTE_Ext_PBMT (r_ref : register_ref (mword 10)) (v : mword 2) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r => write_reg_ref r_ref (_update_PTE_Ext_PBMT (r) (v))  : M (unit).

Definition _get_PTE_Ext_RSW_60t59b (v : mword 10) : mword 2 := subrange_vec_dec (v) (6) (5).

Definition _update_PTE_Ext_RSW_60t59b (v : mword 10) (x : mword 2) : mword 10 :=
   update_subrange_vec_dec (v) (6) (5) (x).

Definition _set_PTE_Ext_RSW_60t59b (r_ref : register_ref (mword 10)) (v : mword 2) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r =>
   write_reg_ref r_ref (_update_PTE_Ext_RSW_60t59b (r) (v))
    : M (unit).

Definition _get_PTE_Ext_reserved (v : mword 10) : mword 5 := subrange_vec_dec (v) (4) (0).

Definition _update_PTE_Ext_reserved (v : mword 10) (x : mword 5) : mword 10 :=
   update_subrange_vec_dec (v) (4) (0) (x).

Definition _set_PTE_Ext_reserved (r_ref : register_ref (mword 10)) (v : mword 5) : M (unit) :=
   (reg_deref (r_ref)) >>= fun r =>
   write_reg_ref r_ref (_update_PTE_Ext_reserved (r) (v))
    : M (unit).

Definition default_sv32_ext_pte : pte_ext_bits := ('b"0000000000").
#[export] Hint Unfold default_sv32_ext_pte : sail.
Definition ext_bits_of_PTE {pte_size : Z} (pte : mword pte_size) (*member_Z_list pte_size [32; 64]*)
: mword 10 :=
   Mk_PTE_Ext
     ((if Z.eqb pte_size (64) then subrange_vec_dec (pte) (63) (54)
       else default_sv32_ext_pte)).

Definition PPN_of_PTE {pte_size : Z} (pte : mword pte_size) (*member_Z_list pte_size [32; 64]*)
: mword ((if pte_size =? 32 then 22 else 44)) :=
   if Z.eqb pte_size (32) then autocast (T := mword) (subrange_vec_dec (pte) (31) (10))
   else autocast (T := mword) (subrange_vec_dec (pte) (53) (10)).

Definition pte_is_non_leaf (f : mword 8) : bool :=
   andb ((eq_vec ((_get_PTE_Flags_X (f))) (('b"0"))))
     ((andb ((eq_vec ((_get_PTE_Flags_W (f))) (('b"0"))))
         ((eq_vec ((_get_PTE_Flags_R (f))) (('b"0")))))).

Definition pte_is_invalid (f : mword 8) (e : mword 10) : bool :=
   orb ((eq_vec ((_get_PTE_Flags_V (f))) (('b"0"))))
     ((orb
         ((andb ((eq_vec ((_get_PTE_Flags_R (f))) (('b"0"))))
             ((andb ((eq_vec ((_get_PTE_Flags_W (f))) (('b"1"))))
                 ((eq_vec ((_get_PTE_Flags_X (f))) (('b"0"))))))))
         ((orb
             ((andb ((eq_vec ((_get_PTE_Flags_R (f))) (('b"0"))))
                 ((andb ((eq_vec ((_get_PTE_Flags_W (f))) (('b"1"))))
                     ((eq_vec ((_get_PTE_Flags_X (f))) (('b"1"))))))))
             ((orb
                 ((andb ((pte_is_non_leaf (f)))
                     ((orb ((eq_vec ((_get_PTE_Flags_A (f))) (('b"1"))))
                         ((orb ((eq_vec ((_get_PTE_Flags_D (f))) (('b"1"))))
                             ((orb ((eq_vec ((_get_PTE_Flags_U (f))) (('b"1"))))
                                 ((neq_vec (e) (('b"0000000000"))))))))))))
                 ((orb ((neq_vec ((_get_PTE_Ext_PBMT (e))) (('b"00"))))
                     ((orb ((neq_vec ((_get_PTE_Ext_RSW_60t59b (e))) (('b"00"))))
                         ((neq_vec ((_get_PTE_Ext_reserved (e))) (('b"00000")))))))))))))).

Definition undefined_PTW_Error '(tt : unit) : M (PTW_Error) :=
   (internal_pick ([PTW_No_Access; PTW_Invalid_PTE; PTW_Misaligned]))  : M (PTW_Error).

Definition undefined_page_based_mem_type '(tt : unit) : M (page_based_mem_type) :=
   (internal_pick ([PBMT_PMA; PBMT_NC; PBMT_IO]))  : M (page_based_mem_type).

Definition undefined_PTW_Output '(tt : unit) : M (PTW_Output) :=
   (undefined_bitvector (44)) >>= fun (w__0 : mword 44) =>
   (undefined_bitvector (64)) >>= fun (w__1 : mword 64) =>
   (undefined_bitvector (56)) >>= fun (w__2 : mword 56) =>
   (undefined_range (0) (2)) >>= fun (w__3 : Z) =>
   (undefined_page_based_mem_type (tt)) >>= fun (w__4 : page_based_mem_type) =>
   (undefined_bool (tt)) >>= fun (w__5 : bool) =>
   returnM (({| PTW_Output_ppn := w__0;
                PTW_Output_pte := w__1;
                PTW_Output_pteAddr := w__2;
                PTW_Output_level := w__3;
                PTW_Output_pbmt := w__4;
                PTW_Output_global := w__5 |})).

Fixpoint read_pte_sw (mem : list ((mword 56 * mword 64))) (addr : mword 56) : option (mword 64) :=
   match mem with
   | [] => None
   | pair' :: rest =>
      match pair' with
      | (a, v) => if eq_vec (a) (addr) then Some (v) else read_pte_sw (rest) (addr)
      end
   end.

Definition undefined_Extension '(tt : unit) : M (Extension) :=
   (internal_pick ([Ext_Svnapot; Ext_Sv39]))  : M (Extension).

Definition currentlyEnabled (e : Extension) : bool :=
   match e with | Ext_Sv39 => true | Ext_Svnapot => true end.

Fixpoint _rec_pt_walk
(mem : list ((mword 56 * mword 64))) (vpn : mword 27) (pt_base : mword 44) (level : Z)
(_reclimit : Z) (*(0 <=? level) && (level <=? 2)*) (_acc : Acc (Zwf 0) _reclimit)
{struct _acc} : M (ptw_res PTW_Output PTW_Error).
exact (
   catch_early_return
     (liftR (assert_exp' (Z.geb (_reclimit) (0)) "recursion limit reached") >>= fun _ =>
      let vpn_i_size := 9 in
      let vpn_i :=
        subrange_vec_dec (vpn) ((Z.sub ((Z.mul ((Z.add (level) (1))) (vpn_i_size))) (1)))
          ((Z.mul (level) (vpn_i_size))) in
      let pte_addr := concat_vec (pt_base) ((concat_vec (vpn_i) (('b"000")))) in
      match read_pte_sw (mem) ((autocast (T := mword)  pte_addr)) with
      | None => returnR (ptw_res PTW_Output PTW_Error) ((Err (PTW_No_Access)))
      | Some pte =>
         let pte_flags := Mk_PTE_Flags ((subrange_vec_dec (pte) (7) (0))) in
         let pte_ext := ext_bits_of_PTE (pte) in
         (if pte_is_invalid (pte_flags) (pte_ext) then
            returnR (ptw_res PTW_Output PTW_Error) ((Err (PTW_Invalid_PTE)))
          else
            let ppn := PPN_of_PTE (pte) in
            (if pte_is_non_leaf (pte_flags)
               return
               MR (ptw_res PTW_Output PTW_Error) (ptw_res PTW_Output PTW_Error) then
               (if Z.gtb (level) (0)
                  return
                  MR (ptw_res PTW_Output PTW_Error) (ptw_res PTW_Output PTW_Error) then
                  liftR ((_rec_pt_walk (mem) (vpn) ((autocast (T := mword)  ppn))
                            ((Z.sub (level) (1))) ((Z.sub (_reclimit) (1)))
                            (_limit_reduces_bool _acc ltac:(assumption))))
                   : MR (ptw_res PTW_Output PTW_Error) (ptw_res PTW_Output PTW_Error)
                else returnR (ptw_res PTW_Output PTW_Error) ((Err (PTW_Invalid_PTE))))
                : MR (ptw_res PTW_Output PTW_Error) (ptw_res PTW_Output PTW_Error)
             else if andb ((Z.eqb (level) (2)))
                       ((neq_vec ((subrange_vec_dec (ppn) (17) (0))) (('b"000000000000000000"))))
             then
               returnR (ptw_res PTW_Output PTW_Error) ((Err (PTW_Misaligned)))
             else if andb ((Z.eqb (level) (1)))
                       ((neq_vec ((subrange_vec_dec (ppn) (8) (0))) (('b"000000000")))) then
               returnR (ptw_res PTW_Output PTW_Error) ((Err (PTW_Misaligned)))
             else
               (if andb ((currentlyEnabled (Ext_Svnapot)))
                     ((eq_vec ((_get_PTE_Ext_N (pte_ext))) (('b"1"))))
                  return
                  MR (ptw_res PTW_Output PTW_Error) (mword ((if 64 =? 32 then 22 else 44))) then
                  (if neq_vec ((subrange_vec_dec (ppn) (3) (0))) (('b"1000"))
                     return
                     MR (ptw_res PTW_Output PTW_Error) (mword ((if 64 =? 32 then 22 else 44))) then
                     (early_return ((Err (PTW_Invalid_PTE))
                      : ptw_res PTW_Output PTW_Error) :
                       MR (ptw_res PTW_Output PTW_Error) (mword ((if 64 =? 32 then 22 else 44))))
                      : MR (ptw_res PTW_Output PTW_Error) (mword ((if 64 =? 32 then 22 else 44)))
                   else
                     returnR (ptw_res PTW_Output PTW_Error) ((update_subrange_vec_dec (ppn) (3) (0)
                                                                ((subrange_vec_dec (vpn) (3) (0))))))
                   : MR (ptw_res PTW_Output PTW_Error) (mword ((if 64 =? 32 then 22 else 44)))
                else returnR (ptw_res PTW_Output PTW_Error) (ppn)) >>= fun final_ppn =>
               returnR (ptw_res PTW_Output PTW_Error) ((Ok
                                                          (({| PTW_Output_ppn :=
                                                                 autocast (T := mword) 
                                                                 final_ppn;
                                                               PTW_Output_pte := pte;
                                                               PTW_Output_pteAddr :=
                                                                 autocast (T := mword) 
                                                                 pte_addr;
                                                               PTW_Output_level := level;
                                                               PTW_Output_pbmt := PBMT_PMA;
                                                               PTW_Output_global := false |})))))
             : MR (ptw_res PTW_Output PTW_Error) (ptw_res PTW_Output PTW_Error))
          : MR (ptw_res PTW_Output PTW_Error) (ptw_res PTW_Output PTW_Error)
      end
       : MR (ptw_res PTW_Output PTW_Error) (ptw_res PTW_Output PTW_Error))
).
Defined.


Definition pt_walk
(_arg0 : list ((mword 56 * mword 64))) (_arg1 : mword 27) (_arg2 : mword 44) (level : Z)
(*(0 <=? level) && (level <=? 2)*)
: M (ptw_res PTW_Output PTW_Error) :=
   (_rec_pt_walk (_arg0) (_arg1) (_arg2) (level) ((level  : Z)) (Zwf_guarded _))
    : M (ptw_res PTW_Output PTW_Error).

Definition initialize_registers '(tt : unit) : unit := tt.

Definition sail_model_init (_ : unit) : unit := initialize_registers (tt).



